<?php
   $this->headTitle('Panel');
   $this->headMeta()->appendName('description', 'Details of the selection panel for dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Panel</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Panel</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>




<div class="page-header"> 
   <h1><small>Shortlisting Panel</small></h1>
             </div> 
            

<div class="row">

<div class="span3">

<h3>Tony Heaton OBE</h3>

<img src="/images/Tony-Heaton.jpg" title="Tony Heaton, dot-art Schools Selection Panel" 
alt="Tony Heaton, dot-art Schools Selection Panel"/>

<p><br>Tony is a practising Sculptor, Chair of Shape Arts and Consultant/Advisor to many 
major cultural organisations, including: The British Council, Tate and the 
Research Centre for Museums and Galleries. He is the initiator of NDACA – 
the National Disability Arts Collection and Archive.</p> 

<p>THis sculpture, Gold Lamé, recently occupied The Liverpool Plinth and his "Monument to the Unintended Performer"
 was installed on the Big 4 at the entrance to Channel 4 TV Centre in celebration of the 2012 Paralympics. 
His sculpture "Squarinthecircle?" is situated outside the school of architecture, Portsmouth University.
</p> 

<p>He was awarded an OBE in the Queen's Birthday Honours, 2013, for services to the arts 
and the disability arts movement and has an Alumni Award from Lancaster University and 
honorary Doctorates from both the University of Leicester and the new University Bucks. </p>

</div>

     <div class="span3">

<h3>Deborah Riding</h3>

<img src="/images/Deborah-Riding.jpg" title="Deborah Riding, dot-art Schools Selection Panel" 
alt="Deborah Riding, dot-art Schools Selection Panel"/>

<p><br>Dr Deborah Riding has worked in gallery education for over twenty years, 
managing and delivering programmes for a range of audiences and undertaking research. 
Deborah’s research interests are around collaborative practices in galleries and her 
doctoral thesis focused specifically on the co-creation of knowledge in the public 
art museum. Deborah leads the team for children and young people at Tate Liverpool, 
working collaboratively with audiences to support deep engagement with the arts and 
the gallery and its collection.</p> 

<p>Deborah is committed to making children and young 
people’s learning and voices visible in the gallery and has recently co- curated a 
new Collection display, Ideas Depot, with curator Darren Pih and local teachers and 
children. Deborah is a co-editor of the International Journal of Art and Design 
Education and co-leads the Cultural Education task group for Liverpool Cultural Education Partnership.
</p> 


</div>



<div class="span3">

<h3>Sandra Penketh</h3>

<img src="/images/sandra-penketh-web.jpg" title="Sandra Penketh, dot-art Schools Selection Panel" 
alt="Sandra Penketh, dot-art Schools Selection Panel"/>

<p><br>Sandra Penketh has responsibility for <a href="http://www.liverpoolmuseums.org.uk/">National Museums
Liverpool's</a> fine and decorative art collections and venue management responsibility for the Walker Art Gallery, Lady Lever Art Gallery, 
Sudley House and the Oratory. Sandra studied History of Art at the Sainsbury Centre, University 
of East Anglia and then obtained a Masters Degree in Medieval Studies from the University of Liverpool.</p> 

<p>In 1989 she joined the staff of National Museums Liverpool as an assistant curator at the Walker 
Art Gallery before moving on to work in the Art Galleries Education department. 
From 1998 until 2002, Sandra worked on the development of new display galleries at World Museum, 
part of the £45 million capital project Into the Future. Sandra also taught History of Art 
regularly for the University of Liverpool Centre for Continuing Education from 1991 until 2002. 
Between 2003 and 2012 she was Head of the Lady Lever Art Gallery. Sandra specialises in 
Medieval and Victorian Art and has published on Medieval Books of Hours, British nineteenth-century 
sculpture and painting, and the Fine Art collections of the Walker Art Gallery and Lady 
Lever Art Gallery. She has curated a wide range of exhibitions on Victorian art.</p>
</div>



<div class="span3">

<h3>Caroline Wilkinson</h3>

<img src="/images/caroline-wilkinson-web.jpg" title="Caroline Wilkinson, dot-art Schools Selection Panel" 
alt="Caroline Wilkinson, dot-art Schools Selection Panel"/>

<p><br>Caroline took up the post of Director of the <a href="https://www.ljmu.ac.uk/about-us/faculties/faculty-of-arts-professional-and-social-studies/liverpool-school-of-art-and-design">
School of Art & Design at Liverpool John Moores University</a> in October 2014. 
She has a background in art and science and her research and creative work sits at the forefront of art-science fusion and 
includes subjects as diverse as forensic art, human anatomy, medical art, face recognition, forensic science, anthropology, 
3D visualisation, digital art and craniofacial identification.</p>
 
<p>Caroline is a graduate of the University of Manchester, where she also led the Unit of Art in Medicine 2000-2005 
and received a NESTA fellowship to develop a 3D computerised facial reconstruction system for use in forensic and 
archaeological depiction. She moved to LJMU from the University of Dundee, where she was Head of Human Identification 
in the award-winning Centre for Anatomy & Human Identification. Her high profile facial depiction work includes facial 
depictions of Richard III, St Nicolas, J.S. Bach, Rameses II and Mary, Queen of Scots.</p></p>

<p>Caroline has a high profile in public engagement relating to art and science. She is a Fellow of the Royal Society of 
Edinburgh and received the 2013 RSE Senior Award for Public Engagement. She also delivered the 2013 RSE Christmas Lecture. 
Her work is exhibited in museums around the world and she has appeared on TV and radio as an expert in relation 
to facial depiction and historical interpretation. Previous appearances include; Meet the Ancestors (BBC), 
History Cold Case (BBC), Secrets of the Dead (C4), Mummies Unwrapped (Discovery) and (R4).</p>
</div>

</div>


<div class="page-header"> 

<h1><small>Overall Judge</small></h1>
</div> 
            
<div class="row">

<div class="span4">

<h3>Susan M Coles</h3>

<a><img src="/images/susan-m-coles.jpg" title="Susan M Coles, dot-art Schools Guest Judge" 
alt="Susan M Coles, dot-art Schools Guest Judge"/></a>
  
<p><br>Susan is a past president, member of council and member of the professional development board of NSEAD,
is secretariat to the All Party Parliamentary Group on Art, Craft and Design Education and an Associate of
The Big Draw.</p> 

<p>She says: “I am totally absorbed in the world of art craft and design education, 
as artist, teacher, adviser, and critical friend and as part of NSEAD. Nationally (and beyond) 
I am a campaigner and advocate for the subject. I strongly believe that every child has an entitlement 
to a high quality visual art education and will do all that I can to remind people of that. 
I agreed to be a judge for this because it is a chance to showcase and to celebrate all the 
wonderful work being done in schools by teachers and young people. I can't wait to see the art work.”
</p>               
</div>

</div>





</div>
