<?php
   $this->headTitle('Schools List');
   $this->headMeta()->appendName('description', 'List of schools taking part in the dot-art Schools program, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $entryCount = 0;
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">Schools</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <?php if ($this->type != 'All Schools'): ?>
    <li><a href="/schools">All Schools</a> <span class="divider">/</span></li>
  <?php endif; ?>
  <li class="active"><?php echo $this->type ?></li>
</ul>

<?php if ($this->comingsoon): ?>

<div class="hero-unit" id="coming-soon">
  <h1>Coming Soon...</h1>
  <p>The 2020 competition entries for the dot-art Schools programme will appear here from March,
  and public voting will begin in April.
  Why not visit the <a href="/archive">Archive</a> to browse entries from previous years?</p>
</div>
<a href="/index" class="btn">Go back to home page</a>

<?php else: ?>

<!--- 

<p>Our <a href="/panel">panel of art experts</a> are currently selecting their top three entries from each school from the
submissions below. Public voting will be open from 28th March - 28th April 2020. The first-placed entry from 
each school will be included in an exhibition at Liverpool School of Art and Design starting on the 17th June.</p>

 <h2>VOTE NOW!</h2>
 
 <p>Public voting is open from 28th March - 28th April 2020. 
You can see the competition entries for each school by clicking the <strong>Browse Entries</strong> buttons below, then select your favourite by clicking the <strong>vote</strong> button. For full details please see the <a href="http://schools.dot-art.com/vote/howtovote">How To Vote</a> page.</p>


-->


 
<p>Following a judges shortlist, public voting took place from 28th March - 28th April. 
You can now see the winning art work from each school by clicking on the links below.
Due to the current coronavirus situation, details of the exhibition for the first-placed entry from each school will 
be announced as soon as possible.</p>


<?php foreach ($this->entries as $entry):?>
<?php if ($entryCount == 0): ?>
    <div class="row">
<?php endif; ?>

<div class="span4 school-panel">
    <h4><?php echo $this->escape($entry['name']) ?></h4>
    <img src="/images/<?php echo $this->escape($entry['image_folder']) ?>/<?php echo $this->escape($entry['image']) ?>" />
    <p><a class="btn" href="<?= $this->url(array('controller' => 'school', 'action' => 'index', 'name' => $entry['url_path'])) ?>">Browse entries &raquo;</a></p>
</div>

<?php $entryCount++; ?>
<?php if ($entryCount == 3): ?>
    <?php $entryCount = 0; ?>
    </div>
<?php endif; ?>

<?php endforeach;?>

<?php endif; ?>

</div>
