<?php
   $this->headTitle("Workshops");
   $this->headMeta()->appendName("description", "dot-art Schools offers artist led workshops and artists in schools across the Liverpool City Region.");
   $this->headScript()->appendFile("/scripts/bootstrap-transition.js", "text/javascript");
   $this->headScript()->appendFile("/scripts/bootstrap-tab.js", "text/javascript");
      
?>

<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">Workshops</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Workshops</li>
</ul>

<div class="row">
<div class="span12">

<div class="tabbable" id="stages">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-workshops" data-toggle="tab">
            Artist Led Workshops
        </a></li>
        <li><a href="#tab-artists" data-toggle="tab">
            Meet The Artists
        </a></li>
    </ul>
    
    
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab-workshops">
        
        <div class="row row-entry">

            <div class="span4">
            <img src="/images/Artist-Workshops-5.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
            <div class="span4">
            <img src="/images/Artist-Workshops-6.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
            <div class="span4">
            <img src="/images/Artist-Workshops-2.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            </div>
            
        
            <h2>Artist Led Workshops</h2>
    
            <p>dot-art Schools works with a wide range of artists to offer your school
            artist-led workshops, from one day to an entire project or arts week, in a variety of different techniques, 
            media and subjects. All our
            workshops are delivered by experienced artists with full DBS clearance and public
            liability insurance, and can be tailored to meet your specific requirements.</p>
            
          
            <h2>Cost</h2>
    
            <p>We have a flat day rate of &pound;275 for those participating in dot-art Schools and &pound;295 
            for non-participants, plus materials.</p>
            
            
            <h2>How It Works</h2>
            
            <p>We know that you may not have the time to search for reliable, professional and 
            talented artists to work with your school. We have done the hard work for you and put together a 
            range of single day, hands on sessions for your pupils to get creative.</p>
            
            <p>If you don't see what you are looking for below, or would like a tailored session for a particular
             topic, activity or event, just <a href="mailto:schools@dot-art.com">get in touch</a> - we are happy to help!</p>

               <div class="row row-entry">

            <div class="span4">
            
            <p><b>PRIMARY ONLY</b></p>
            
            
             <ul>
             
             <li>
                <a href="/docs/dot-art-Schools-Chinese-Brush-Painting.pdf" target="_blank">Chinese Brush Painting</a>
                </li>
                
            
                  <li>
                <a href="/docs/dot-art-Schools-Bring-A-Book-To-Life.pdf" target="_blank">Bring a Book to Life</a>
                </li>
                
                
                <li>
                <a href="/docs/dot-art-Schools-Tremendous-Trees.pdf" target="_blank">Tremendous Trees</a>
                </li>
                
                <li>
                <a href="/docs/dot-art-Schools-Colour-Blending.pdf" target="_blank">Colour Blending</a>
                </li>
                
                <li>
                <a href="/docs/dot-art-Schools-Drawing-Tips.pdf" target="_blank">Drawing Tips and Tricks</a>
                </li>
                
                  <li>
                <a href="/docs/dot-art-Schools-Colour-Theory.pdf" target="_blank">Colour Theory: Kandinsky and Klimt</a>
                </li>
                
                 <li>
                <a href="/docs/dot-art-Schools-Hand-Painting.pdf" target="_blank">Hand Painting and Creating</a>
                </li>
                
                 <li>
                 <a href="/docs/dot-art-Schools-Felt-Fruit-18.pdf" target="_blank">Fantastic Felt Fruit</a>
                 </li>
                
                 <li>
                 <a href="/docs/dot-art-Schools-Textile-Sea-Creatures-18.pdf" target="_blank">Textile Sea Creatures</a>
                 </li>
                
                 <li>
                 <a href="/docs/dot-art-Schools-Bird-Sculptures-18.pdf" target="_blank">3D Bird Sculpture</a>
                 </li>
                
                 </ul>
           </div>
            
           
           
            <div class="span4">
            
              <p><b>PRIMARY AND SECONDARY</b></p>
              
              <ul>  
           
        
           <li>
            <a href="/docs/dot-art-Schools-Street-Art.pdf" target="_blank">Street Art</a>
                </li>
           
            <li>
            <a href="/docs/dot-art-Schools-Anna-Atkins.pdf" target="_blank">Anna Atkins / Sunprints</a>
                </li>
                
            <li>
            <a href="/docs/dot-art-Schools-Stars.pdf" target="_blank">Stars!</a>
                </li>
              
              <li>
                <a href="/docs/dot-art-Schools-Shipbuilding.pdf" target="_blank">Shipbuilding</a>
                </li>
                
                <li>
                   <a href="/docs/dot-art-Schools-3D-Wallpaper-18.pdf" target="_blank">3D Wallpaper Using Recycled Materials</a>
                </li>
                
            
                
                <li>
                <a href="/docs/dot-art-Schools-Analogue-Adventures.pdf" target="_blank">Analogue Adventures</a>
                </li>
                          
                <li>
                <a href="/docs/dot-art-Schools-Featuring-Faces.pdf" target="_blank">Featuring Faces</a>
                </li>
                
                </ul>
                </div>
           
      <div class="span4">
            
              <p><b>SECONDARY ONLY</b></p>
              
              <ul>  
           
        
           <li>
            <a href="/docs/dot-art-Schools-Protest-Plants-Anti-Racism" target="_blank">Protest Plants - Anti Racism</a>
                </li>
           
                 </ul>
             </div>   
            </ul>
            
            </div>
            </div>
            
            <h2>INSET Days & CPD Sessions</h2>
            
             <p>dot-art Schools can also offer artist led INSET days for teachers and staff. 
            Please <a href="mailto:schools@dot-art.com">get in touch</a> for more details.</p>
           
            
             <div class="row row-entry">

            <div class="span4">
            <img src="/images/INSET-3.jpg" title="INSET Days from dot-art" alt="INSET Days from dot-art"/>
            </div>
            
            <div class="span4">
           <img src="/images/INSET-4.jpg" title="INSET Days from dot-art" alt="INSET Days from dot-art"/>
            </div>
            
            <div class="span4">
           <img src="/images/INSET-2.jpg" title="INSET Days from dot-art" alt="INSET Days from dot-art"/>
            </div>
            </div>
            
            
            <h2>Booking</h2>
            
            <p>To book a session or to find out more, please call us on 0345 017 6660
            or email <a href="mailto:schools@dot-art.com">schools@dot-art.com</a>.</p>
            
            
            <p>
           
                
               
                
            </p>

        </div>
        
            
       <div class="tab-pane fade in" id="tab-artists">
      

        <div class="row row-entry">

            <div class="span4">
            <img src="/images/Faith-Bebbington.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
            <div class="span4">
            <img src="/images/Emily-Bartlett.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
             <div class="span4">
            <img src="/images/Rachel-Brewster-Wright.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            </div>
            
                        
          <div class="row row-entry">
          
          <div class="span4">
          <h2>Faith Bebbington</h2>
          </div>
          
          <div class="span4">
          <h2>Emily Bartlett</h2>
          </div>
          
          <div class="span4">
          <h2>Rachel Brewster-Wright</h2>
          </div>
            </div>
            
            <div class="row row-entry">
            
            <div class="span4">
            <p>Faith is a professional sculptor with a studio in Liverpool. She is a qualified art teacher with a PGCE Secondary 
            Art & Design from Liverpool John Moores University, so understands the principles of how students learn, classroom 
            management and the demands of the national curriculum.  She works regularly with schools across the North West 
            devising and leading short, one day workshops through to longer residencies. She develops 3D sculpture projects 
            suitable for Key Stage 1, 2, 3 and also offers INSET sessions.</p>
            <p>The simple construction techniques she has developed working with recycled materials such as newspaper, wire, 
            cardboard and tape enable children and young people of varying abilities to create successful sculptures quickly, 
            either individually or in groups.  Faith has particular experience of, and an interest in working with students 
            with emotional and behavioural challenges, learning difficulties and sensory impairments, as they usually excel 
            and achieve incredible results participating in her workshops.</p>
            </div>
            
     
            <div class="span4">
            <p>Emily has 6 years of experience teaching art to students of all ages and classes of all sizes in a range of 
            settings including; 1-2-1 tuition for children, group adult art classes and young adults with learning disabilities. 
            As a full-time practicing artist in her 20s she is able to effectively relate to and inspire young people!</p>
            </div>

            
            <div class="span4">
            <p>I"m Rachel and I am a vintage photographer, artist, sessional musician and university lecturer. I work with a 
            wide variety of arts, community and educational organisations across all ages (8+ to adult) through my business 
            Little Vintage Photography, looking at mindful analogue photographic processes, visual storytelling and the 
            convergence of traditional and modern technology through STEM and the arts. I work across both education and 
            entertainment, running "Discover & Create" workshops and courses and collaborate closely with heritage, craft, 
            art, literacy, science and tech sectors to combine the science and engineering of traditional photography with 
            modern technology in order to produce creative and artistic output in a slower, more mindful way.</p>
            <p>I also co-host the UK"s Analogue Photography Podcast and am contributing author for analogue photography 
            industry blogs. I was honoured to be listed as a Role Model for Innovate Her/Liverpool Girl Geeks and given the 
            opportunity to exhibit for several galleries across the UK.</p>
            </div>  
            
            
        </div>
        
        
         <div class="row row-entry">

            <div class="span4">
            <img src="/images/Madeleine-Pires.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
            <div class="span4">
            <img src="/images/Julie-James-Turner.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
             <div class="span4">
            <img src="/images/Phil-Disley.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            </div>
            
                        
          <div class="row row-entry">
          
          <div class="span4">
          <h2>Madeleine Pires</h2>
          </div>
          
          <div class="span4">
          <h2>Julie James-Turner</h2>
          </div>
          
          <div class="span4">
          <h2>Phil Disley</h2>
          </div>
            </div>
            
            <div class="row row-entry">
            
            <div class="span4">
            <p>Madeleine Pires is an artist who produces colourful and vivid oil paintings. She also has a qualification in 
            teaching English as a Foreign Language from Cambridge University. She worked as a bilingual teaching assistant 
            in a Montessori nursery school and Early Years department at Oporto British School, Portugal, while gaining a level 
            2 qualification in professional practice from the London College of Teachers. Since being back in the UK, Madeleine 
            has worked part-time as a private tutor of primary and secondary school aged children in English and Art, and is 
            actively involved in her own children's school where she runs an after-school "Fine Art" course.</p>
            </div>
            
     
            <div class="span4">
            <p>Julie James- Turner is an artist working in textiles and mixed media, she currently works as a community arts 
            tutor for the Worker''s Educational Association, as a textile tutor for The Open College of Arts Textile degree 
            and as a sessional lecturer for Liverpool John Moores University. She also runs artist led workshops for local 
            galleries, schools and dot-art in Liverpool.</p>
            </div>
            
      
            
            <div class="span4">
            <p>Born in 1971 Phil moved from a Diploma in Art to studying a Graphics degree at Northumbria University. 
            Today, Phil is acknowledged as one of Britain''s foremost Illustrators.  From modest beginnings with a first 
            illustration in the Big Issue in 1993, his work has regularly appeared in such esteemed publications as The 
            Times, The Guardian, The Spectator, The Financial Times, The London Evening Standard, Esquire, GQ Magazine, 
            Tatler and MarketingWeek. Oxford University Press has commissioned illustrations for many educational publications 
            with Harper Collins and Little, Brown Book Group engaging Phil for several book covers.</p>
            <p>Working in numerous schools, Phil has spoken at workshops for teachers, careers talks for year 12 
            students and delivered art lessons for all ages from reception class upwards.</p>
            </div>
            
            
        </div>
        
           <div class="row row-entry">

           
            <div class="span4">
            <img src="/images/Julie-Lawrence.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
                </div>
            
                        
          <div class="row row-entry">
          
          <div class="span4">
          <h2>Julie Lawrence</h2>
          </div>
          
          <div class="span4">
          <h2></h2>
          </div>
         
          <div class="span4">
          <h2></h2>
          </div>
            </div>
            
            <div class="row row-entry">
            
            <div class="span4">
            <p>Julie has practised widely as an contemporary landscape painter using the language of romanticism and the 
            responses of Turner, Blake and Palmer. She has exhibited widely across the UK and was recently awarded "North of 
            England artist of the Year" by the National Open Art Competition in London.</p>
            <p>She has also worked as a teacher for children with severe and complex learning difficulties for the last 
            eighteen years, and has a special interest in multi-sensory art. She has contributed to an art and sensory needs 
            book, and also worked alongside therapeutic practitioners to deliver multi sensory art workshops hosted by the 
            Lyndale School in Eastham.</p>
            </div>
            
            
            <div class="span4">
            <p></p>
            </div>
          
            
            <div class="span4">
            <p></p>
            </div>  
            
            
        </div>
        
            
                        
          <div class="row row-entry">
          
          <div class="span4">
          
          </div>
          
         
            </div>
            
            <div class="row row-entry">
            
            
            
     
            
            
          </div>
        
        
        </div>
        
    </div>
    
</div>
</div>

</div>

