<?
   $this->headTitle('2014-15');
   $this->headMeta()->appendName('description', 'Register for more information about the dot-art Schools programmes 2014-15; an interactive, 
   inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">2014-15</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">2014-15</li>
</ul>

 <p><a href="/docs/dot-art-Schools-Overview-2014-15.pdf" target="_blank">Download a PDF overview of dot-art Schools</a></p>
  <p><a href="/docs/dot-art-Schools-Sign-Up-Form-2014-15.pdf" target="_blank">Download a PDF of the dot-art Schools Sign Up Form for 2014-15</a></p>           
  <p><a href="/docs/dot-art-Schools-Sign-Up-Form-2014-15.doc" target="_blank">Download a Word document of the dot-art Schools Sign Up Form for 2014-15</a></p>

<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>

<h3>Send me more information about the dot-art Schools programme 2014-15</h3>

<div id="mc_embed_signup" class="span6">
<form action="http://dot-art.us7.list-manage.com/subscribe/post?u=7a47545ee447b15126626bfa3&amp;id=fedcddfeeb"
	method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
	class="validate" target="_blank" novalidate>

	<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
	<div class="mc-field-group">
		<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span></label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
	</div>
	<div class="mc-field-group">
		<label for="mce-FNAME">First Name  <span class="asterisk">*</span></label>
		<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
	</div>
	<div class="mc-field-group">
		<label for="mce-LNAME">Last Name  <span class="asterisk">*</span></label>
		<input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
	</div>
	<div class="mc-field-group">
		<label for="mce-MMERGE3">School </label>
		<input type="text" value="" name="MMERGE3" class="" id="mce-MMERGE3">
	</div>
	<div class="mc-field-group">
		<label for="mce-MMERGE4">Job Title </label>
		<input type="text" value="" name="MMERGE4" class="" id="mce-MMERGE4">
	</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;">
    	<input type="text" name="b_7a47545ee447b15126626bfa3_fedcddfeeb" tabindex="-1" value="">
    </div>
    <div class="clear">
    	<input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
    </div>
</form>
</div>

</div>
