<?php
   $this->headTitle('Schools List');
   $this->headMeta()->appendName('description', 'List of schools taking part in the dot-art Schools program, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $entryCount = 0;
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">Schools</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <?php if ($this->type != 'All Schools'): ?>
    <li><a href="/schools">All Schools</a> <span class="divider">/</span></li>
  <?php endif; ?>
  <li class="active"><?php echo $this->type ?></li>
</ul>

<?php if ($this->comingsoon): ?>
<div class="hero-unit">
  <h1>Coming Soon...</h1>
  <p>The 2019 competition entries for the dot-art Schools programme will appear here from March,
  and public voting will begin in April.</p>
</div>

<a href="/index" class="btn">Go back to home page</a>

<?php else: ?>

<!--- <p>You can see the competition entries for each school by clicking the <strong>Browse
Entries</strong> buttons below.</p>

<h2>VOTE NOW!</h2>

<p>Public voting is open from 29th March - 30th April. You can see the competition entries for each school by clicking 
the <strong>Browse Entries</strong> buttons below, then select your favourite by clicking the <strong>vote</strong> button.
For full details please see the <a href="http://schools.dot-art.com/vote/howtovote">How To Vote</a> page.</p>



 <p>Following a judges shortlist, public voting took place from 4th - 28th April. You can now see the winning art work
 from each school which will go into our exhibition at Storyhouse in Chester from the 8th June, 
 by clicking on the links below.</p>
-->


 <p>Public voting will be open from 1st - 29th April 2019. You can see the competition entries for each school by clicking 
the <strong>Browse Entries</strong> buttons below, then select your favourite by clicking the <strong>vote</strong> button.
For full details please see the <a href="http://schools.dot-art.com/vote/howtovote">How To Vote</a> page.</p>
 
 

<?php foreach ($this->entries as $entry):?>
<?php if ($entryCount == 0): ?>
    <div class="row">
<?php endif; ?>

<div class="span4 school-panel">
    <h4><?php echo $this->escape($entry['name']) ?></h4>
    <img src="/images/<?php echo $this->escape($entry['image_folder']) ?>/<?php echo $this->escape($entry['image']) ?>" />
    <p><a class="btn" href="<?= $this->url(array('controller' => 'school', 'action' => 'index', 'name' => $entry['url_path'])) ?>">Browse entries &raquo;</a></p>
</div>

<?php $entryCount++; ?>
<?php if ($entryCount == 3): ?>
    <?php $entryCount = 0; ?>
    </div>
<?php endif; ?>

<?php endforeach;?>

<?php endif; ?>

</div>
