<?php $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8" /> 
<?php  $this->headLink()->appendStylesheet('/styles/bootstrap-1.3.css', 'screen');
    echo $this->headLink();
    
    $this->headTitle()->append('dot-art Schools');
    $this->headTitle()->setSeparator(' - ');
    echo $this->headTitle();
    
    $this->headMeta()->appendName('keywords', 'dot-art, dot-art Schools, Liverpool schools, art in schools, Merseyside schools, art competition, Art exhibition Liverpool, Art Merseyside, online art exhibition');
    $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headMeta();
    
    $this->headScript()->prependFile('/scripts/jquery-2.1.4.min.js', 'text/javascript');
    $this->headScript()->appendFile('/scripts/bootstrap-collapse.js', 'text/javascript');
    $this->headScript()->appendFile('/scripts/bootstrap-dropdown.js', 'text/javascript');
    echo $this->headScript();
?>

<?php if (getenv('APPLICATION_ENV') != 'development'): ?>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-401715-9', 'auto');
    ga('send', 'pageview');

  </script>
<?php endif; ?>
</head>

<body>

<!-- NAVBAR
================================================== -->
<div class="navbar-wrapper">
  <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
  <div class="container">
    <div class="navbar">
      <div class="navbar-inner">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">dot-art Schools Liverpool</a>
        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Schools <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/schools">All 2018 Schools</a></li>
                <li><a href="/schools/primary">2018 Primary Schools</a></li>
                <li><a href="/schools/secondary">2018 Secondary Schools</a></li>
                <li class="divider"></li>
                <li><a href="/archive">Archive of Previous Years</a></li>
                <li class="divider"></li>
                <li><a href="/vote/howtovote">How To Vote</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Exhibition <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/exhibition/year2018">2018</a></li>
                <li><a href="/exhibition/year2017">2017</a></li>
                <li><a href="/exhibition/year2016">2016</a></li>
                <li><a href="/exhibition/year2015">2015</a></li>
                <li><a href="/exhibition/year2014">2014</a></li>
                <li><a href="/exhibition/year2013">2013</a></li>
              </ul>
            </li>
            <li><a href="/what">What?</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Support <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/support/supporters">Supporters</a></li>
                <li><a href="/support/getinvolved">Get Involved</a></li>
              </ul>
            </li>
            <li><a href="/panel">Panel</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">News <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/news">News</a></li>
                <li><a href="/news/press">Press Releases</a></li>
              </ul>
            </li>
            <li><a href="/workshops">Workshops</a></li>
            <li><a href="/contact">Contact</a></li>
            <li><a href="http://dot-art.co.uk" target="_blank">dot-art Home</a></li>
          </ul>
        </div>
      </div><!-- /.navbar-inner -->
    </div><!-- /.navbar -->

  </div> <!-- /.container -->
</div><!-- /.navbar-wrapper -->

<?= $this->layout()->content ?>

<script type="text/javascript">
$(document).ready(function(){
    $('.dropdown-toggle').dropdown();
});
</script>

</body>

</html>
