<?
   $this->headTitle('News');
   $this->headMeta()->appendName('description', 'News from participants in dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">News</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">News <span class="divider">/</span></li>
  <li class="active">News</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>

<!-- Put SPAN6 DIVs here for each news item:  -->

<div class="row">
	<div class="span6">
		<h3>dotartSchools Twitter Feed</h3>
		<a class="twitter-timeline" height="700" href="https://twitter.com/dotartschools" data-widget-id="381020540489584641">Tweets by @dotartschools</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
			</div>
      
      
      	<div class="span6">
		<h3>2015 Winners Announced!</h3>

    <img src="/images/news/dot-art-Schools-Overall-Winner-2015-2-web" title="2015 Winners Announced"
		alt="2015 Winners Announced">
    
    <p><small>Overall winner Georgia Allen of Rainhill High and her teacher Anthony Bennett, receiving her prize from the Lord Mayor.</small></p>
    
		<img src="/images/news/dot-art-Schools-2015-winning-work-web" title="2015 Winners Announced"
		alt="2015 Winners Announced">
    
    <p><b>More details and full list of winners can be found on the 
    <a href="http://schools.dot-art.com/exhibition/year2015">Exhibition Page.</a></b</p>
    
	</div>
	      </div>
        
        
<div class="row">    


	<div class="span6">
		<h3>Principal Sponsor 2015 Announced</h3>
		<img src="/images/news/DMR-logo-web.jpg" title="David M Robinson Principal Sponsor" alt="David M Robinson Principal Sponsor"/>
		<p><b>dot-art Schools are delighted to announce David M Robinson as their principal sponsor for the third
annual inter-school art competition. David M Robinson commented: <i>As a boy, other than playing football for the school, there was only one other
place I wanted to spend my time – in the art room... great memories of my art teacher, John Hughes. This
passion for art has followed me through life and supporting the arts in the North West has become an
integral part of our business. It is my absolute pleasure to be helping dot-art Schools inspire the imaginations
of the school children of Merseyside.</i></p>
		<p><a href="http://www.davidmrobinson.co.uk/">Find out more about David M Robinson.</b></a></p> 
	</div>
      
			
			<div class="span6">
		<h3>Partnership with St Georges Hall Announced</h3>
		<img src="/images/news/web-news-sgh.jpg" title="St Georges Hall and dot-art Schools" alt="St Georges Hall and dot-art Schools"/>
		<p><b>We are delighted to announce that the dot-art Schools Exhibition 2015 will take place at the iconic St Georges Hall, 
    from 5th - 20th June.</p>
		<p>Read the <a href="http://schools.dot-art.com/docs/dot-art-schools-press-release-21-11-14.pdf">
    full press release here.</b></a></p> 
	</div>
	
				
		 	</div>
      
      
      
		<div class="row">
	
	
	<div class="span6">
		<h3>2014 Winners Announced!</h3>

		<img src="/images/news/2014-winners-web.jpg" title="2014 Winners Announced"
		alt="2014 Winners Announced">
		<p><small>Prizegiving with Lord Mayor Cllr Gary Millar</small></p>

	
    
    <p><b>More details and full list of winners can be found on the 
    <a href="http://schools.dot-art.com/exhibition/year2014">Exhibition Page.</a></b</p>
    
	</div>
	
	<div class="span6">
		<h3>Overall Judge Announced: Award winning artist, Tabitha Moses.</h3>

		<img src="/images/news/tabitha-moses.jpg" title="Overall judge: Tabitha Moses"
		alt="Overall judge: Tabitha Moses">
		<p><small>Photo courtesy of McCoy Wynne</small></p>

		<p>Tabitha Moses is an artist whose practice is rooted in the meanings and 
		possibilities of materials. Fabric and stitch are central to her practice - through 
		the language of textiles Tabitha uncovers rich connections and latent emotions. 
		She is interested in the transformation of discarded or overlooked subjects and 
		matter into objects that speak with eloquence of the human experience.</p>

		<p>Tabitha was winner of the Liverpool Art Prize 2013. She is currently
		developing the theme for a solo exhibition at Walker Art Gallery later this year.</p>

		<p>Tabitha has exhibited nationally and internationally and is a visiting lecturer at 
		Manchester Metropolitan University.</p>

		<p><strong>Tabitha has selected the overall winners and runners up from both Primary
		and Secondary Schools.</strong></p>
	</div>  
	
	</div>

	

<div class="row">
	<div class="span6">
		<h3>Welcome New Sponsors: Cassell Moore</h3>

		<a href="http://schools.dot-art.com/exhibition/"><img src="/images/news/cassell-moore.jpg"
		title="dot-art Schools New Sponsors" alt="dot-art Schools New Sponsors"/></a>

		<p><b>Employment law continues to evolve at a rate of knots and at Cassell Moore we 
		recognise the challenges that this presents for our clients in balancing compliance 
		against commercial and other objectives.  We will work in partnership with you 
		providing bespoke practical advice across the full spectrum of employment law.  
		</b></p>

		<p>At Cassell Moore we recognise the challenges that constant developments in employment law present for our clients, 
		particularly in the Education Sector. Our specialist employment team will work with you to provide bespoke 
		practical advice at each stage. We advise across the full range of issues from ad hoc HR queries, internal 
		disciplinary and grievances, resolving disputes, representation at tribunal and advice on more complex 
		strategic projects such as reorganisations, redundancy, TUPE and corporate transactions.</p>

		<p><b>Contact: Liz Cotton, Partner – Head of Employment (pictured) 
		lizcotton@cassellmoore.com / www.cassellmoore.com<b></p>
	</div>
 
 
	<div class="span6">
		<h3>Partnership with Walker Art Gallery Announced</h3>
		<a href="http://blog.liverpoolmuseums.org.uk/2013/11/calling-all-art-teachers/"><img src="/images/Walker-med.jpg"
		title="Walker Art Gallery and dot-art Schools" alt="Walker Art Gallery and dot-art Schools"/></a>
		<p>We are delighted to announce that the dot-art Schools Exhibition 2014 will take place at the prestigious Walker Art Gallery, from 17th May - 8th June.</p>
		<p><a href="http://blog.liverpoolmuseums.org.uk/2013/11/calling-all-art-teachers/">Read the Walker blog article here</a> and
		<a href="http://www.liverpoolmuseums.org.uk/about/mediacentre/2013/school-work-on-display-at-the-walker.aspx"> full press release here.</a></p> 
	</div> 
  

</div>



<div class="row">  
		
	<div class="span6">
		<h3>2013 Winners Announced!</h3>
		<a href="http://schools.dot-art.com/exhibition/"><img src="/images/news/winners.jpg"
		title="dot-art Schools 2013 Winners Announced" alt="dot-art Schools 2013 Winners Announced"/></a>
	</div>
	
</div>

</div>

<!--
	<div class="span6">
		<h3>Video: Beth Explains dot-art Schools</h3>
		<iframe width="550" height="396" src="http://www.baytvliverpool.com/vod/iframe/?vid=JBV527cd70c99492" frameborder="0" scrolling="no" style="overflow:hidden;"></iframe>
	</div> 
--->