<?
   $this->headTitle('What?');
   $this->headMeta()->appendName('description', 'dot-art Schools is an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">What?</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">What?</li>
</ul>

<div class="row">
<div class="span12">

<div class="tabbable" id="stages">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-program" data-toggle="tab">
            <span class="hidden-phone">The Programme</span>
            <span class="visible-phone">Programme</span>
        </a></li>
        <li><a href="#tab-teachers" data-toggle="tab">
            <span class="hidden-phone">Information for Teachers</span>
            <span class="visible-phone">Info. for Teachers</span>
        </a></li>
        <li><a href="#tab-background" data-toggle="tab">
            Background
        </a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab-program">
            <h2>The Programme</h2>
    
            <p>Students in <strong>Year 6</strong> and <strong>Year 9</strong> are given a public platform to display their art work, the
            chance to enter into friendly inter-school competition, and an insight into the way the commercial
            art world works. This provides a fantastic way of celebrating the art work created and the
            school's commitment to arts education, and demonstrates the quality of art produced to parents,
            families, local authorities and the wider community.</p>
            
            <p>Each participating school creates and selects up to twenty five pieces of student work which they 
            feel best represent the talents of their students. These art works are put on display to the
            world via the dot-art Schools website. Students from all the schools in the Programme, as well as
            the general public, will be able to <strong>vote</strong> for their favourite piece of art, then the top rated
            pieces of work from across all participating schools will be displayed on the home page of the
            dot-art Schools site. An <strong>exhibition</strong> will be held showcasing the top works from each participating
            school, at the <strong>Domino Gallery</strong> in Liverpool city centre. In addition a <strong>scholarship</strong> will be
            awarded to the top student across the programme, giving them a year's membership to dot-art's
            network, allowing them to showcase and sell their work alongside professional artists. (See:
            <a href="http://services.dot-art.com">http://services.dot-art.com</a>)</p>
            
            <p>This annual programme will encourage healthy competition between students and schools, as well
            as driving traffic to the site and therefore increasing the audience for the students' work and
            the profile of the school. The final exhibition will also provide a wonderful opportunity for
            the successful students to show their work in a public setting. Finally the programme can help
            participating schools meet many of the KS2 and 3 <strong>National Curriculum</strong> requirements for Art and
            Design, the criteria outlined in the <strong>OFSTED</strong> evaluation framework, as well as providing a
            valuable tool for schools working towards <strong>Artsmark</strong> status.</p>
            
            <blockquote>
                <p>Pupils benefited greatly from the feedback received when their work was shared locally or more widely...</p>
                <p>Schools should... build sustained partnerships with art galleries and creative practitioners.</p>
                <p>Pupils who met with inspectors reported consistently the motivational impact of seeing their own work displayed professionally and publicly...</p>
                <p>The public exhibition of students' work was highly effective in strengthening links between schools and the local community, including diverse community groups, different generations and those living in contrasting socio-economic circumstances.</p>
                <small>Extracts from: Ofsted Report - Making a mark: art, craft and design education, 2008/11</small>
            </blockquote>
        </div>
        
        <div class="tab-pane fade in" id="tab-teachers">
            <h2>Information for Teachers</h2>
            <p>The pilot programme launches in January 2013, with 22 schools from across the Liverpool City Region taking
            part. From September 2013 we will be accepting new schools onto the programme, with the aim of including all
            schools, both primary and secondary, within 3 years.</p>

            <p>Please download the document below for more details about how the programme works and the benefits it can
            bring:</p>
            <ul>
                <li><a href="/docs/dot-art-Schools-Yr6.pdf" target="_blank">dot-art Schools for Year 6</a></li>
                <li><a href="/docs/dot-art-Schools-Yr9.pdf" target="_blank">dot-art Schools for Year 9</a></li>
                <li><a href="/docs/dot-art-Schools-NC-Ofsted-KS2-3.pdf" target="_blank">dot-art Schools and the National Curriculum / OFSTED</a></li>
                <li><a href="/docs/dot-art-Schools-Artsmark.pdf" target="_blank">dot-art Schools and Artsmark</a></li>
            </ul>

            <p>If you would like more details about taking part, please complete and return the following Expression of
            Interest Form:</p>
            <ul>
                <li><a href="/docs/dot-art-Schools-Primary-EofI.doc" target="_blank">dot-art Schools Expression of Interest - Primary (Word format)</a></li>
                <li><a href="/docs/dot-art-Schools-Secondary-EofI.doc" target="_blank">dot-art Schools Expression of Interest - Secondary (Word format)</a></li>
            </ul>
        </div>
        
        <div class="tab-pane fade in" id="tab-background">
            <h2>Background</h2>
            <p>The dot-art Schools programme has been developed by dot-art, a Liverpool based arts organisation which has
            been supporting artists and developing innovative and creative visual arts projects and initiatives since 2005.</p>

            <p>We are now using our skills, experience and expertise to give the young people of the region access to an
            exciting new public platform for their creative output, and a taste of the way the art world works.</p>

            <p>dot-art is made up of two arms:</p>

            <p><strong>dot-art Ltd</strong> is an art gallery and consultancy based in Liverpool city centre, specialising in affordable,
            high quality, locally sourced art, on a sale, commission and rental basis, as well as offering a range of
            complementary services including; art consultancy, exhibition planning and implementation, bespoke
            framing, art valuation and restoration and artist sourcing. See <a href="http://www.dot-art.com">www.dot-art.com</a></p>
            
            <p><strong>dot-art Services CIC</strong> is a not-for-profit organisation which exists to support North-West based visual artists,
            both emerging and established, through a range of services and activities designed to help them develop
            their careers and gain exposure and promotion for their work. A Social Enterprise with artists at it's heart,
            dot-art Services CIC functions in a unique fashion, operating a membership system which gives artists a
            range of benefits including their own web page, access to exhibition, career development and promotional
            opportunities, as well as help and advice, networking events and discounts on art supplies and framing. See
            <a href="http://services.dot-art.com">services.dot-art.com</a>.</p>
            
            <p><i>This project is supported using public funding by the National Lottery through Arts Council England.</i></p>
            <img src="/images/ace-med-white.jpg">
            
        </div>
    </div>
    
</div>
</div>
</div>

</div>