<?php
   $this->headTitle('News');
   $this->headMeta()->appendName('description', 'Details of the selection panel for dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Panel</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Panel</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>




<div class="page-header"> 
   <h1><small>Shortlisting Panel</small></h1>
             </div> 
            
<div class="row">

<div class="span3">

<h3>Ryan Gander</h3>

<img src="/images/ryan-gander.jpg" title="Ryan Gander, dot-art Schools Selection Panel" 
alt="Ryan Gander, dot-art Schools Selection Panel"/>

<p><br>Ryan Gander is a visual artist who has established an international reputation through artworks that
materialise in many different forms – from sculpture to film, writing, graphic design,
installation, performance and more besides.</p> 

<p>Through associative thought processes that connect the everyday and the esoteric, the
overlooked and the commonplace, Gander’s work involves a questioning of language
and knowledge, as well as a reinvention of both the modes of appearance and the
creation of an artwork. His work can be reminiscent of a puzzle, or a network with
multiple connections and the fragments of an embedded story. It is ultimately a huge
set of hidden clues to be deciphered, encouraging viewers to make their own
associations and invent their own narrative in order to unravel the complexities staged
by the artist.</p> 

<p>Ryan lives and works in Suffolk and London. He studied at
Manchester Metropolitan University, UK, the Rijksakademie van Beeldende Kunsten,
Amsterdam, NL and the Jan van Eyck Akademie, Maastricht, NL. The artist has been
a Professor of Visual Art at the University of Huddersfield and holds an honorary
Doctor of the Arts at the Manchester Metropolitan University and the University of
Suffolk. In 2017 he was awarded an OBE for services to contemporary arts.</p>

<p>After meeting past judge Polly Brannan, Education Curator at Liverpool Biennial at the dot-art Schools exhibition 2016, 
Knotty Ash School were introduced to Ryan and subsequently five children from the school worked with the artist to 
 create art work for the 2018 Biennial. 
 See: <a href="http://www.biennial.com/2018/exhibition/artists/ryan-gander">the Biennial website
 </a>for more information.</p>
</div>


<div class="span3">

<h3>Susan M Coles</h3>

<a><img src="/images/susan-m-coles.jpg" title="Susan M Coles, dot-art Schools Guest Judge" 
alt="Susan M Coles, dot-art Schools Guest Judge"/></a>
  
<p><br>Susan is a past president, member of council and member of the professional development board of NSEAD,
is secretariat to the All Party Parliamentary Group on Art, Craft and Design Education and an Associate of
The Big Draw.</p> 

<p>She says: “I am totally absorbed in the world of art craft and design education, 
as artist, teacher, adviser, and critical friend and as part of NSEAD. Nationally (and beyond) 
I am a campaigner and advocate for the subject. I strongly believe that every child has an entitlement 
to a high quality visual art education and will do all that I can to remind people of that. 
I agreed to be a judge for this because it is a chance to showcase and to celebrate all the 
wonderful work being done in schools by teachers and young people. I can't wait to see the art work.”
</p>               
</div>

<div class="span3">

<h3>Kaety Moon</h3>

<img src="/images/kaety-moon-web.jpg" title="Kaety Moon, dot-art Schools Selection Panel" 
alt="Kaety Moon, dot-art Schools Selection Panel"/>

<p><br>Kaety Moon is a multidisciplinary artist who is passionate about using creativity as a form of expression, 
and a means to communicate. As a member of Chester Library Engagement Team at <a href="https://www.storyhouse.com/">
Storyhouse,</a> Kaety can be found assisting 
patrons with books and computers, making art with families at the craft table, and singing with babies in The Den at Rhyme Time.
</p> 

<p>Kaety is part of Woodhouse Studio in Chester and engaged in a studio practice involving drawing, painting, spoken word and 
song. The visual work combines spontaneous mark making and a variety of textures. These form into artworks which can be 
abstract, sometimes figurative and sometimes decorative. The visual work is left to incubate for a period of time and goes 
on to inform the spoken word and song. Once it is returned to, a narrative is attached, and meaning is found, revealed or given. 
In this way, the work follows a natural rhythm. Kaety delivers workshops in expressive art making at Woodhouse Studio, 
and believes in the power of creativity to bring people together to explore ideas of belonging, health and wellbeing. 
This interest led to the postgraduate study of art psychotherapy at the University of Chester where art making is used 
as a form of communication and a powerful means of healing and change.</p>
</div>



<div class="span3">

<h3>Caroline Wilkinson</h3>

<img src="/images/caroline-wilkinson-web.jpg" title="Caroline Wilkinson, dot-art Schools Selection Panel" 
alt="Caroline Wilkinson, dot-art Schools Selection Panel"/>

<p><br>Caroline took up the post of Director of the <a href="https://www.ljmu.ac.uk/about-us/faculties/faculty-of-arts-professional-and-social-studies/liverpool-school-of-art-and-design">
School of Art & Design at Liverpool John Moores University</a> in October 2014. 
She has a background in art and science and her research and creative work sits at the forefront of art-science fusion and 
includes subjects as diverse as forensic art, human anatomy, medical art, face recognition, forensic science, anthropology, 
3D visualisation, digital art and craniofacial identification.</p>
 
<p>Caroline is a graduate of the University of Manchester, where she also led the Unit of Art in Medicine 2000-2005 
and received a NESTA fellowship to develop a 3D computerised facial reconstruction system for use in forensic and 
archaeological depiction. She moved to LJMU from the University of Dundee, where she was Head of Human Identification 
in the award-winning Centre for Anatomy & Human Identification. Her high profile facial depiction work includes facial 
depictions of Richard III, St Nicolas, J.S. Bach, Rameses II and Mary, Queen of Scots.</p></p>

<p>Caroline Wilkinson is Director of the Face Lab, a LJMU research group based in Liverpool Science Park. 
The Face Lab carries out forensic/archaeological research and consultancy work and this includes craniofacial 
analysis, facial depiction and forensic art. Craniofacial analysis involves the depiction and identification of 
unknown bodies for forensic investigation or historical figures for archaeological interpretation. This may involve 
post-mortem depiction, facial reconstruction, craniofacial superimposition and skull reassembly. 
Forensic art also involves witness interviews to produce facial sketches/composites, age progression images and 
facial image comparison.</p>

<p>Caroline has a high profile in public engagement relating to art and science. She is a Fellow of the Royal Society of 
Edinburgh and received the 2013 RSE Senior Award for Public Engagement. She also delivered the 2013 RSE Christmas Lecture. 
Her work is exhibited in museums around the world and she has appeared on TV and radio as an expert in relation 
to facial depiction and historical interpretation. Previous appearances include; Meet the Ancestors (BBC), 
History Cold Case (BBC), Secrets of the Dead (C4), Mummies Unwrapped (Discovery) and (R4).</p>
</div>

</div>

<div class="page-header"> 
<h1><small>Overall Judge</small></h1>
</div> 
            
<div class="row">

<div class="span4">

<h3>Una Meehan</h3>

<img src="/images/una-meehan-web.jpg" title="Una Meehan, dot-art Schools Overall Judge" 
alt="Una Meehan, dot-art Schools Overall Judge"/>

<p><br>Uná Meehan is the Young People and Children’s Lead at The Philip Barker Centre for Creative Learning housed at The 
University of Chester and Senior Lecturer in Drama and Creative Education within the faculty of Education. The guiding 
principle of The Philip Barker Centre for Creative learning are Innovate- Generate –Advocate for creativity within the
 fields of Education and Healthcare.  Uná’s work including leading on creative thinking within initial teacher education 
 via a Disruption week, which challenges how beginning teachers collaborate without agencies to affect learning through 
 creativity, partners include Chester Zoo, Into Film and Mufti Games.  Alongside schools, she is currently working with 
 a number of external cultural, heritage and arts organisations to strengthen Project Based Learning opportunities within 
 the curriculum, as well as building evidence for the inclusion of cultural and creative education.  In addition, 
 she has spent the past three years working with colleagues in Catalonia to develop student teachers confidence in The 
 Arts addressing issues of isolation and otherness through Applied Theatre.  Uná sits on a number of panels including 
 the strategy group for the Cheshire Local Cultural Education Partnership and the Chester Zoo Curriculum advisory panel.</p> 

<p>She believes strongly that "young people deserve a world class education that goes beyond the 3 o’clock bell".  
Arts education matters more than ever, Creative Industries generates approximately £90 billion to the UK economy. 
Uná and the centre, are currently working on opportunities to enhance the quality of advice for Creative Careers 
in schools and added "dot-art Schools is such an important initiative that should be accessed by all young people and 
it is a privilege and honour to invited as this year’s guest judge".  Una is passionate about cultural and creative 
education and believes "it is every young person’s right to experience a creative curriculum that will equip them 
with the creative and innovative thinking skills to thrive in the twenty first century".</p>

</div>

</div>
   
</div>
