<?php
   $this->headTitle('News');
   $this->headMeta()->appendName('description', 'Details of the selection panel for dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Panel</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Panel</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>




<div class="page-header"> 
   <h1><small>Shortlisting Panel</small></h1>
             </div> 
            
<div class="row">
<div class="span4">

<h3>Susan M Coles</h3>

<a><img src="/images/susan-m-coles.jpg" title="Susan M Coles, dot-art Schools Guest Judge" 
alt="Susan M Coles, dot-art Schools Guest Judge"/></a>
  
<p><br>Susan is a past president, member of council and member of the professional development board of NSEAD,
is secretariat to the All Party Parliamentary Group on Art, Craft and Design Education and an Associate of
The Big Draw.</p> 

<p>She says: “I am totally absorbed in the world of art craft and design education, 
as artist, teacher, adviser, and critical friend and as part of NSEAD. Nationally (and beyond) 
I am a campaigner and advocate for the subject. I strongly believe that every child has an entitlement 
to a high quality visual art education and will do all that I can to remind people of that. 
I agreed to be a judge for this because it is a chance to showcase and to celebrate all the 
wonderful work being done in schools by teachers and young people. I can't wait to see the art work.”
</p>               
</div>

<div class="span4">

<h3>Kaety Moon</h3>

<img src="/images/kaety-moon-web.jpg" title="Kaety Moon, dot-art Schools Selection Panel" 
alt="Kaety Moon, dot-art Schools Selection Panel"/>

<p><br>Kaety Moon is a multidisciplinary artist who is passionate about using creativity as a form of expression, 
and a means to communicate. As a member of Chester Library Engagement Team at <a href="https://www.storyhouse.com/">
Storyhouse,</a> Kaety can be found assisting 
patrons with books and computers, making art with families at the craft table, and singing with babies in The Den at Rhyme Time.
</p> 

<p>Kaety is part of Woodhouse Studio in Chester and engaged in a studio practice involving drawing, painting, spoken word and 
song. The visual work combines spontaneous mark making and a variety of textures. These form into artworks which can be 
abstract, sometimes figurative and sometimes decorative. The visual work is left to incubate for a period of time and goes 
on to inform the spoken word and song. Once it is returned to, a narrative is attached, and meaning is found, revealed or given. 
In this way, the work follows a natural rhythm. Kaety delivers workshops in expressive art making at Woodhouse Studio, 
and believes in the power of creativity to bring people together to explore ideas of belonging, health and wellbeing. 
This interest led to the postgraduate study of art psychotherapy at the University of Chester where art making is used 
as a form of communication and a powerful means of healing and change.</p>
</div>



<div class="span4">

<h3>Caroline Wilkinson</h3>

<img src="/images/caroline-wilkinson-web.jpg" title="Caroline Wilkinson, dot-art Schools Selection Panel" 
alt="Caroline Wilkinson, dot-art Schools Selection Panel"/>

<p><br>Caroline took up the post of Director of the <a href="https://www.ljmu.ac.uk/about-us/faculties/faculty-of-arts-professional-and-social-studies/liverpool-school-of-art-and-design">
School of Art & Design at Liverpool John Moores University</a> in October 2014. 
She has a background in art and science and her research and creative work sits at the forefront of art-science fusion and 
includes subjects as diverse as forensic art, human anatomy, medical art, face recognition, forensic science, anthropology, 
3D visualisation, digital art and craniofacial identification.</p>
 
<p>Caroline is a graduate of the University of Manchester, where she also led the Unit of Art in Medicine 2000-2005 
and received a NESTA fellowship to develop a 3D computerised facial reconstruction system for use in forensic and 
archaeological depiction. She moved to LJMU from the University of Dundee, where she was Head of Human Identification 
in the award-winning Centre for Anatomy & Human Identification. Her high profile facial depiction work includes facial 
depictions of Richard III, St Nicolas, J.S. Bach, Rameses II and Mary, Queen of Scots.</p></p>

<p>Caroline Wilkinson is Director of the Face Lab, a LJMU research group based in Liverpool Science Park. 
The Face Lab carries out forensic/archaeological research and consultancy work and this includes craniofacial 
analysis, facial depiction and forensic art. Craniofacial analysis involves the depiction and identification of 
unknown bodies for forensic investigation or historical figures for archaeological interpretation. This may involve 
post-mortem depiction, facial reconstruction, craniofacial superimposition and skull reassembly. 
Forensic art also involves witness interviews to produce facial sketches/composites, age progression images and 
facial image comparison.</p>

<p>Caroline has a high profile in public engagement relating to art and science. She is a Fellow of the Royal Society of 
Edinburgh and received the 2013 RSE Senior Award for Public Engagement. She also delivered the 2013 RSE Christmas Lecture. 
Her work is exhibited in museums around the world and she has appeared on TV and radio as an expert in relation 
to facial depiction and historical interpretation. Previous appearances include; Meet the Ancestors (BBC), 
History Cold Case (BBC), Secrets of the Dead (C4), Mummies Unwrapped (Discovery) and (R4).</p>
</div>

</div>

<!--

<div class="page-header"> 
<h1><small>Overall Judge</small></h1>
</div> 
            
<div class="row">
<div class="span4">

<h3>Susan M Coles</h3>

<a><img src="/images/susan-m-coles.jpg" title="Susan M Coles, dot-art Schools Guest Judge" 
alt="Susan M Coles, dot-art Schools Guest Judge"/></a>
  
<p><br>Susan is a past president, member of council and member of the professional development board of NSEAD,
is secretariat to the All Party Parliamentary Group on Art, Craft and Design Education and an Associate of
The Big Draw.</p> 

<p>She says: “I am totally absorbed in the world of art craft and design education, 
as artist, teacher, adviser, and critical friend and as part of NSEAD. Nationally (and beyond) 
I am a campaigner and advocate for the subject. I strongly believe that every child has an entitlement 
to a high quality visual art education and will do all that I can to remind people of that. 
I agreed to be a judge for this because it is a chance to showcase and to celebrate all the 
wonderful work being done in schools by teachers and young people. I can't wait to see the art work.”
</p>               
</div>
</div>

   -->
   
</div>
