<?php
   $this->headTitle('News');
   $this->headMeta()->appendName('description', 'Details of the selection panel for dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Panel</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Panel</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>




<div class="page-header"> 
   <h1><small>Shortlisting Panel</small></h1>
             </div> 
            
<div class="row">
<div class="span4">
<h3>Polly Brannan</h3>

<img src="/images/biennial-polly.jpg" title="Polly Brannan, dot-art Schools Selection Panel" 
alt="Polly Brannan, dot-art Schools Selection Panel"/>

<p><br>Polly Brannan is Education Curator at <a href="http://www.biennial.com/2016">Liverpool Biennial.</a>
She is an artist and educator who has produced projects at Frieze Art Fair, Lisbon Experimenta Festival
and Nottingham Contemporary, amongst others. She was Collaborations Curator at Studio Voltaire from 2006-9,
and Education Curator at Serpentine Gallery from 2011-13. She is co-founder of network Avant Gardening,
and was a member of the collective public works from 2005-11.</p> 

<p>For the 9th edition of Liverpool Biennial
2016, a curatorial team has been assembled to work together, sharing different interests and expertise,
the team of curators includes Polly who will be leading on the Children’s Episode where artists are
invited to consider children as the primary audience: sometimes making work with them, sometimes for them.
Children imagine the space between fiction and reality differently, sometimes seeing it as the same thing.
This will be an occasion to explore a fictional universe invented by children for artists, and realised
by artists for children. Liverpool Biennial will also be working with Childwall Academy and The Studio
school to create online learning resources, interpretation and exhibition guides for children.</p>
</div>


<div class="span4">

<h3>Sandra Penketh</h3>

<img src="/images/sandra-penketh-web.jpg" title="Sandra Penketh, dot-art Schools Selection Panel" 
alt="Sandra Penketh, dot-art Schools Selection Panel"/>

<p><br>Sandra Penketh has responsibility for <a href="http://www.liverpoolmuseums.org.uk/">National Museums
Liverpool's</a> fine and decorative art collections and venue management responsibility for the Walker Art Gallery, Lady Lever Art Gallery, 
Sudley House and the Oratory. Sandra studied History of Art at the Sainsbury Centre, University 
of East Anglia and then obtained a Masters Degree in Medieval Studies from the University of Liverpool.</p> 

<p>In 1989 she joined the staff of National Museums Liverpool as an assistant curator at the Walker 
Art Gallery before moving on to work in the Art Galleries Education department. 
From 1998 until 2002, Sandra worked on the development of new display galleries at World Museum, 
part of the £45 million capital project Into the Future. Sandra also taught History of Art 
regularly for the University of Liverpool Centre for Continuing Education from 1991 until 2002. 
Between 2003 and 2012 she was Head of the Lady Lever Art Gallery. Sandra specialises in 
Medieval and Victorian Art and has published on Medieval Books of Hours, British nineteenth-century 
sculpture and painting, and the Fine Art collections of the Walker Art Gallery and Lady 
Lever Art Gallery. She has curated a wide range of exhibitions on Victorian art.</p>
</div>



<div class="span4">

<h3>Caroline Wilkinson</h3>

<img src="/images/caroline-wilkinson-web.jpg" title="Caroline Wilkinson, dot-art Schools Selection Panel" 
alt="Caroline Wilkinson, dot-art Schools Selection Panel"/>

<p><br>Caroline took up the post of Director of the <a href="https://www.ljmu.ac.uk/about-us/faculties/faculty-of-arts-professional-and-social-studies/liverpool-school-of-art-and-design">
School of Art & Design at Liverpool John Moores University</a> in October 2014. 
She has a background in art and science and her research and creative work sits at the forefront of art-science fusion and 
includes subjects as diverse as forensic art, human anatomy, medical art, face recognition, forensic science, anthropology, 
3D visualisation, digital art and craniofacial identification.</p>
 
<p>Caroline is a graduate of the University of Manchester, where she also led the Unit of Art in Medicine 2000-2005 
and received a NESTA fellowship to develop a 3D computerised facial reconstruction system for use in forensic and 
archaeological depiction. She moved to LJMU from the University of Dundee, where she was Head of Human Identification 
in the award-winning Centre for Anatomy & Human Identification. Her high profile facial depiction work includes facial 
depictions of Richard III, St Nicolas, J.S. Bach, Rameses II and Mary, Queen of Scots.</p></p>

<p>Caroline Wilkinson is Director of the Face Lab, a LJMU research group based in Liverpool Science Park. 
The Face Lab carries out forensic/archaeological research and consultancy work and this includes craniofacial 
analysis, facial depiction and forensic art. Craniofacial analysis involves the depiction and identification of 
unknown bodies for forensic investigation or historical figures for archaeological interpretation. This may involve 
post-mortem depiction, facial reconstruction, craniofacial superimposition and skull reassembly. 
Forensic art also involves witness interviews to produce facial sketches/composites, age progression images and 
facial image comparison.</p>

<p>Caroline has a high profile in public engagement relating to art and science. She is a Fellow of the Royal Society of 
Edinburgh and received the 2013 RSE Senior Award for Public Engagement. She also delivered the 2013 RSE Christmas Lecture. 
Her work is exhibited in museums around the world and she has appeared on TV and radio as an expert in relation 
to facial depiction and historical interpretation. Previous appearances include; Meet the Ancestors (BBC), 
History Cold Case (BBC), Secrets of the Dead (C4), Mummies Unwrapped (Discovery) and (R4).</p>
</div>

</div>

<!--

<div class="page-header"> 
<h1><small>Overall Judge</small></h1>
</div> 
            
<div class="row">
<div class="span4">

<h3>Susan M Coles</h3>

<a><img src="/images/susan-m-coles.jpg" title="Susan M Coles, dot-art Schools Guest Judge" 
alt="Susan M Coles, dot-art Schools Guest Judge"/></a>
  
<p><br>Susan is a past president, member of council and member of the professional development board of NSEAD,
is secretariat to the All Party Parliamentary Group on Art, Craft and Design Education and an Associate of
The Big Draw.</p> 

<p>She says: “I am totally absorbed in the world of art craft and design education, 
as artist, teacher, adviser, and critical friend and as part of NSEAD. Nationally (and beyond) 
I am a campaigner and advocate for the subject. I strongly believe that every child has an entitlement 
to a high quality visual art education and will do all that I can to remind people of that. 
I agreed to be a judge for this because it is a chance to showcase and to celebrate all the 
wonderful work being done in schools by teachers and young people. I can't wait to see the art work.”
</p>               
</div>
</div>

   -->
   
</div>
