<?php
   $this->headTitle("Workshops");
   $this->headMeta()->appendName("description", "dot-art Schools offers artist led workshops and artists in schools across the Liverpool City Region.");
   $this->headScript()->appendFile("/scripts/bootstrap-transition.js", "text/javascript");
   $this->headScript()->appendFile("/scripts/bootstrap-tab.js", "text/javascript");
      
?>

<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">Workshops</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Workshops</li>
</ul>

<div class="row">
<div class="span12">

<div class="tabbable" id="stages">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-workshops" data-toggle="tab">
            Artist Led Workshops
        </a></li>
        <li><a href="#tab-artists" data-toggle="tab">
            Meet The Artists
        </a></li>
    </ul>
    
    
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab-workshops">
        
        <div class="row row-entry">

            <div class="span4">
            <img src="/images/Artist-Workshops-5.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
            <div class="span4">
            <img src="/images/Artist-Workshops-6.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
            <div class="span4">
            <img src="/images/Artist-Workshops-2.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            </div>
            
        
            <h2>Artist Led Workshops</h2>
    
            <p>dot-art Schools works with a wide range of artists to offer your school one-day
            artist-led workshops in a variety of different techniques, media and subjects. All our
            workshops are delivered by experienced artists with full DBS clearance and public
            liability insurance, and can be tailored to meet your specific requirements.</p>
            
            <h2>Cost</h2>
    
            <p>We have a flat day rate of &pound;275 for those participating in dot-art Schools and &pound;295 
            for non-participants, plus materials.</p>
            
            <h2>How It Works</h2>
            
            <p>We know that you may not have the time to search for reliable, professional and 
            talented artists to work with your school. We have done the hard work for you and put together a 
            range of single day, hands on sessions for your pupils to get creative.</p>
            
            <p>If you don"t see what you are looking for below, or would like a tailored session for a particular
             topic, activity or event, just <a href="mailto:schools@dot-art.com">get in touch</a> - we are happy to help!</p>

             <div class="row row-entry">

            <div class="span4">
             <ul>
            
            <li>
            <a href="/docs/dot-art-Schools-Sensory-Seascapes.pdf" target="_blank">Sensory Seascapes</a>
                </li>
                
                <li>
                <a href="/docs/dot-art-Schools-Analogue-Adventures.pdf" target="_blank">Analogue Adventures</a>
                </li>
                
                <li>
                <a href="/docs/dot-art-Schools-Hand-Painting.pdf" target="_blank">Hand Painting and Creating</a>
                </li>
                
                <li>
                <a href="/docs/dot-art-Schools-Featuring-Faces.pdf" target="_blank">Featuring Faces</a>
                </li>
                
                
                </ul>
            </div>
            
            <div class="span4">
            <li>
                <a href="/docs/dot-art-Schools-Art-of-Maths-18.pdf" target="_blank">The Art of Maths</a>
                </li>
                
                <li>
                   <a href="/docs/dot-art-Schools-3D-Wallpaper-18.pdf" target="_blank">3D Wallpaper Using Recycled Materials</a>
                </li>
                
                
                <li>
                <a href="/docs/dot-art-Schools-Colour-Pattern-Symbols-18.pdf" target="_blank">Explore Colour, Pattern and Symbols</a>
                </li>
                
                <li>
                <a href="/docs/dot-art-Schools-Street-Art-18.pdf" target="_blank">Street Art Isn"t Graffiti!</a>
                </li>
            </div>
            
            <div class="span4">
              <ul>  
                 
                 <li>
                 <a href="/docs/dot-art-Schools-Felt-Fruit-18.pdf" target="_blank">Fantastic Felt Fruit</a>
                 </li>
                
                 <li>
                 <a href="/docs/dot-art-Schools-Textile-Sea-Creatures-18.pdf" target="_blank">Textile Sea Creatures</a>
                 </li>
                
                 <li>
                 <a href="/docs/dot-art-Schools-Bird-Sculptures-18.pdf" target="_blank">3D Bird Sculpture</a>
                 </li>
            </ul>
            
            </div>
            </div>
            
            <h2>INSET Days & CPD Sessions</h2>
            
             <p>dot-art Schools can also offer artist led INSET days for teachers and staff. 
            Please <a href="mailto:schools@dot-art.com">get in touch</a> for more details.</p>
           
            
             <div class="row row-entry">

            <div class="span4">
            <img src="/images/INSET-3.jpg" title="INSET Days from dot-art" alt="INSET Days from dot-art"/>
            </div>
            
            <div class="span4">
           <img src="/images/INSET-4.jpg" title="INSET Days from dot-art" alt="INSET Days from dot-art"/>
            </div>
            
            <div class="span4">
           <img src="/images/INSET-2.jpg" title="INSET Days from dot-art" alt="INSET Days from dot-art"/>
            </div>
            </div>
            
            
            <h2>Booking</h2>
            
            <p>To book a session or to find out more, please call us on 0345 017 6660
            or email <a href="mailto:schools@dot-art.com">schools@dot-art.com</a>.</p>
            
            
            <p>
           
                
               
                
            </p>

        </div>
        
            
        <div class="tab-pane fade in" id="tab-artists">
      

        <div class="row row-entry">

            <div class="span4">
            <img src="/images/Faith-Bebbington.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
            <div class="span4">
            <img src="/images/Julie-Lawrence.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
             <div class="span4">
            <img src="/images/Rachel-Brewster-Wright.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            </div>
            
                        
          <div class="row row-entry">
          
          <div class="span4">
          <h2>Faith Bebbington</h2>
          </div>
          
          <div class="span4">
          <h2>Julie Lawrence</h2>
          </div>
          
          <div class="span4">
          <h2>Rachel Brewster-Wright</h2>
          </div>
            </div>
            
            <div class="row row-entry">
            
            <div class="span4">
            <p>Faith is a professional sculptor with a studio in Liverpool. She is a qualified art teacher with a PGCE Secondary 
            Art & Design from Liverpool John Moores University, so understands the principles of how students learn, classroom 
            management and the demands of the national curriculum.  She works regularly with schools across the North West 
            devising and leading short, one day workshops through to longer residencies. She develops 3D sculpture projects 
            suitable for Key Stage 1, 2, 3 and also offers INSET sessions.</p>
            <p>The simple construction techniques she has developed working with recycled materials such as newspaper, wire, 
            cardboard and tape enable children and young people of varying abilities to create successful sculptures quickly, 
            either individually or in groups.  Faith has particular experience of, and an interest in working with students 
            with emotional and behavioural challenges, learning difficulties and sensory impairments, as they usually excel 
            and achieve incredible results participating in her workshops.</p>
            </div>
            
     
            <div class="span4">
            <p>Julie has practised widely as an contemporary landscape painter using the language of romanticism and the 
            responses of Turner, Blake and Palmer. She has exhibited widely across the UK and was recently awarded "North of 
            England artist of the Year" by the National Open Art Competition in London.</p>
            <p>She has also worked as a teacher for children with severe and complex learning difficulties for the last 
            eighteen years, and has a special interest in multi-sensory art. She has contributed to an art and sensory needs 
            book, and also worked alongside therapeutic practitioners to deliver multi sensory art workshops hosted by the 
            Lyndale School in Eastham.</p>
            </div>
            
      
            
            <div class="span4">
            <p>I"m Rachel and I am a vintage photographer, artist, sessional musician and university lecturer. I work with a 
            wide variety of arts, community and educational organisations across all ages (8+ to adult) through my business 
            Little Vintage Photography, looking at mindful analogue photographic processes, visual storytelling and the 
            convergence of traditional and modern technology through STEM and the arts. I work across both education and 
            entertainment, running "Discover & Create" workshops and courses and collaborate closely with heritage, craft, 
            art, literacy, science and tech sectors to combine the science and engineering of traditional photography with 
            modern technology in order to produce creative and artistic output in a slower, more mindful way.</p>
            <p>I also co-host the UK"s Analogue Photography Podcast and am contributing author for analogue photography 
            industry blogs. I was honoured to be listed as a Role Model for Innovate Her/Liverpool Girl Geeks and given the 
            opportunity to exhibit for several galleries across the UK.</p>
            </div>  
            
            
        </div>
        
        
         <div class="row row-entry">

            <div class="span4">
            <img src="/images/Eimear-Kavanagh.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
            <div class="span4">
            <img src="/images/Julie-James-Turner.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
             <div class="span4">
            <img src="/images/David-Andrews.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            </div>
            
                        
          <div class="row row-entry">
          
          <div class="span4">
          <h2>Eimear Kavanagh</h2>
          </div>
          
          <div class="span4">
          <h2>Julie James-Turner</h2>
          </div>
          
          <div class="span4">
          <h2>David-Andrews</h2>
          </div>
            </div>
            
            <div class="row row-entry">
            
            <div class="span4">
            <p>Born in Ireland in 1973, Eimear studied BA Hons in Textiles and Surface Pattern Design at Bretton Hall University 
            of Leeds, graduating in 1999. Based in Liverpool, Eimear works as a mixed media artist with a varied wealth of 
            experience in the arts. Her body of work and previous commissions have taken her to India, Australia and back to 
            Ireland. She has worked within fashion, public street art, textiles, illustration, album cover design; stage set
            design, tattoo art, schools education & community workshops.</p>
            <p>Eimear has experience of working with children of all ages within gallery settings, care home and community 
            settings. Workshops included a wide range of art & craft activities and well-being activities (such as yoga, massage 
            and meditation). For the past three years Eimear has enjoyed delivering workshops through dot-art, within primary 
            schools across the North West.</p>
            </div>
            
     
            <div class="span4">
            <p>Julie James- Turner is an artist working in textiles and mixed media, she currently works as a community arts 
            tutor for the Worker''s Educational Association, as a textile tutor for The Open College of Arts Textile degree 
            and as a sessional lecturer for Liverpool John Moores University. She also runs artist led workshops for local 
            galleries, schools and dot-art in Liverpool.</p>
            </div>
            
      
            
            <div class="span4">
            <p>David Andrews is a graphic designer and street artist who paints portraits and nature murals across the country 
            under the pseudonym AndAtWhatCost. He has experience teaching stencil art workshops to a wide range of people, 
            including those with challenging behaviour and additional needs. David has also recently finished a large project 
            for Liverpool FC where he ran workshops for 500 pupils over 5 weeks to draw key events from the club"s history, 
            then turned the drawings into a digitally coloured mural to be printed and installed at Anfield.</p>
            
            </div>  
            
            
        </div>
        
           <div class="row row-entry">

            <div class="span4">
            <img src="/images/Phil-Disley.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
           
            </div>
            
                        
          <div class="row row-entry">
          
          <div class="span4">
          <h2>Phil Disley</h2>
          </div>
          
         
            </div>
            
            <div class="row row-entry">
            
            <div class="span4">
            <p>Born in 1971 Phil moved from a Diploma in Art to studying a Graphics degree at Northumbria University. 
            Today, Phil is acknowledged as one of Britain''s foremost Illustrators.  From modest beginnings with a first 
            illustration in the Big Issue in 1993, his work has regularly appeared in such esteemed publications as The 
            Times, The Guardian, The Spectator, The Financial Times, The London Evening Standard, Esquire, GQ Magazine, 
            Tatler and MarketingWeek. Oxford University Press has commissioned illustrations for many educational publications 
            with Harper Collins and Little, Brown Book Group engaging Phil for several book covers.</p>
            <p>Working in numerous schools, Phil has spoken at workshops for teachers, careers talks for year 12 
            students and delivered art lessons for all ages from reception class upwards.</p>
            </div>
            
     
            
            
          </div>
        
        
        </div>
        
    </div>
    
</div>
</div>

</div>

