<?php
   $this->headTitle('Thank You');
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">Thank You For Confirming</h1>
</div>

<p>Thank you for confirming your vote in the dot-art Schools competition 2016!</p>

<p>You are only allowed to vote once. However, if you wish to change your mind, just vote again to
replace this one.</p>

<p>The winners will be announced on this website after voting closes; we'll send you an email with the link 
so you can see if your favourite won. An exhibition will take place at St Georges Hall in Liverpool from the 27th May - 
11th June showcasing the winning artwork from each school. For more information, visit
the <a href="http://schools.dot-art.com/exhibition/year2016">Exhibition</a> page.</p>

<!---
<p>This year's dot-art Schools programme has been made possible thanks to the generous support of our 
principal sponsor, David M Robinson; please take a look at their 
<a href="http://www.davidmrobinson.co.uk/">website.</a></p>
<a href="http://www.davidmrobinson.co.uk/"><img src="/images/logos/dmr-270.jpg" class="span3" alt="David M Robinson logo"/></a>
-->           

</div>
