<?php
   $this->headTitle('Workshops');
   $this->headMeta()->appendName('description', 'dot-art Schools offers artist led workshops and artists in schools across the Liverpool City Region.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">Get Involved</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Get Involved</li>
</ul>

<div class="row">
<div class="span12">

<div class="tabbable" id="stages">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-sponsorship" data-toggle="tab">
            Sponsorship
        </a></li>
        <li><a href="#tab-champions" data-toggle="tab">
            dot-art Schools Champions
        </a></li>
    </ul>
    
    
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab-sponsorship">
        
        <div class="row row-entry">

            <div class="span6">
            <h2>Sponsorship</h2>
    
            <p>We rely on the generosity of our sponsors to run the dot-art Schools programme every year. Please consider 
            talking to us about how your business can help us to support the next generation develop their creativity.</p>
            
            <p>dot-art Schools is always looking for businesses that value the importance of a creative education, who
             can help ensure we continue to offer hundreds of children and young people every year, an invaluable and unique
             experience and nurture the creative talent of the future. In return we can offer a fantastic package of website, 
             press and social media promotion, involvement in our annual prizegiving events, prints of our winning artworks and
             much more.
              </p>
              
              <h2>Costs</h2>
            
            <p>Sponsorship packages start from &pound;2500. We are always happy to discuss support in kind and bespoke arrangements.</p>
            
            <h2>Interested?</h2>
            
            <p>Give us a call on 0345 0176660 or email <a href="mailto:schools@dot-art.com">schools@dot-art.com</a></p>

            
            </div>
            
            <div class="span6">
            <img src="/images/sponsors-2.jpg" title="dot-art Schools Sponsorship" alt="dot-art Schools Sponsorship"/>
            </div>
            
             </div>
                      
           
            
                        
        </div>
        
        <div class="tab-pane fade in" id="tab-champions">
      
      <div class="row row-entry">
      
            <div class="span6">
            <h2>Champions</h2>
    
            <p>Could YOU be a dot-art Schools Champion?</p>
            
            <ul><b>
            <li>Do you believe in the importance of art education?</li>
            <li>Do you think ALL children should be given the opportunity to express themselves creatively?</li>
            <li>Would you like to support the work of dot-art Schools to nurture talent in children?</li>
            </b></ul>
            
            <p>Due to continued cuts to the arts curriculum in schools, more and more children and young people are not 
            being offered the chance of a rounded, creative education. This is despite the fact that the Creative Industries 
            are currently growing at TWICE the rate of the rest of the economy and a huge proportion of future jobs will 
            have creativity at their core. Many schools would love to take part in dot-art Schools, but budget cuts have 
            made it a challenge. We need people and businesses like you to make a small contribution to allow them to get involved.
              </p>
              
           <p>In return, as well as the knowledge you are making a huge difference to the lives of children and young people 
           in your region, you will receive: Your logo and weblink on the portfolio page of the school you are supporting 
           (we can either assign you a school in need of help or you can pick one close to your heart!) Your company name 
           listed as a dot-art Schools Champion on the website. A special dot-art Schools Champion logo to use on your own 
           website. Invitations to the Prize Giving Event and Exhibition launch in June 2018.
</p>
              
              <h2>Costs</h2>
            
            <ul>
            <li>For a donation of &pound;250 a school can take part for one year.</li>
            <li>For a donation of &pound;500, a school can take part for one year AND host an artist led workshop.</li>
               </ul>
            
            <h2>Interested?</h2>
            
            <p>Give us a call on 0345 0176660 or email <a href="mailto:schools@dot-art.com">schools@dot-art.com</a></p>

            </div>
            
            <div class="span6">
            <img src="/images/sponsors-1.jpg" title="dot-art Schools Sponsorship" alt="dot-art Schools Sponsorship"/>
            <img src="/images/champion-logo-300.jpg" title="dot-art Schools Champion Logo" alt="dot-art Schools Champion Logo"/>
            </div>
            
             </div>
                   
        </div>
        </div>
        
    </div>
    
</div>
</div>

</div>

