<?php
   $this->headTitle('Workshops');
   $this->headMeta()->appendName('description', 'dot-art Schools offers artist led workshops and artists in schools across the Liverpool City Region.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">Get Involved</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Get Involved</li>
</ul>

<div class="row">
<div class="span12">

<div class="tabbable" id="stages">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-workshops" data-toggle="tab">
            Sponsorship
        </a></li>
        <li><a href="#tab-artists" data-toggle="tab">
            dot-art Champions
        </a></li>
    </ul>
    
    
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab-workshops">
        
        <div class="row row-entry">

            <div class="span4">
            <img src="/images/Artist-Workshops-1.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
            <div class="span4">
            <img src="/images/Artist-Workshops-4.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            
            <div class="span4">
            <img src="/images/Artist-Workshops-2.jpg" title="Artists in Schools from dot-art" alt="Artists in Schools from dot-art"/>
            </div>
            </div>
            
        
            <h2>Sponsorship</h2>
    
            <p>We rely on the generosity of our sponsors to run the dot-art Schools programme every year. Please read on to 
            see how your business can help us to support the next generation develop thier creativity.</p>
            
            
            <h2>How It Works</h2>
            
            <p>COMING SOON</p>
            
            <p></p>

            
            
                        
        </div>
        
        <div class="tab-pane fade in" id="tab-artists">
      
            <h2>dot-art Schools Champions</h2>
            
            <p>We rely on the generosity of our sponsors to run the dot-art Schools programme every year. Please read on to 
            see how your business can help us to support the next generation develop thier creativity.</p>
            
            
            <h2>How It Works</h2>
            
            <p>COMING SOON</p>
            
            <p></p>
 
            
        </div>
        </div>
        
    </div>
    
</div>
</div>

</div>

