<?php
   $this->headTitle('Supporters');
   $this->headMeta()->appendName('description', 'dot-art Schools is an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<script type="text/javascript">twttr.conversion.trackPid('nu3ux', { tw_sale_amount: 0, tw_order_quantity: 0 });</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
</noscript>


<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">Supporters</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Supporters</li>
</ul>
 
            
            <div class="page-header">
            <h1><small>Project Funder</small></h1>
            </div>
           
            <div class="row">
            
            <a href="https://www.artscouncil.org.uk/" target="_blank">
                <img src="/images/ACE-logo-black.jpg" class="span6" alt="Arts Council England" />
            </a>
             </div>
            
            <p>.</p>  
         <!--   
            <div class="page-header">
            <h1><small>Principal Sponsor 2017-18</small></h1>
            </div>
           
            <div class="row">
            
            <a href="https://www.tangleteezer.com/" target="_blank">
                <img src="/images/logos/TT-540.jpg" class="span6" alt="Tangle Teezer logo" />
            </a>
             </div>
             
             -->
             
            <div class="page-header"> 
            <h1><small>Supporters 2019-20</small></h1>
             </div> 
              
            <div class="row">
            
                 <a href="https://www.medicash.org/" target="_blank">
                <img src="/images/logos/Medicash-270.jpg" class="span3" alt="Medicash logo" />
            </a>
            
             <a href="https://www.arrivabus.co.uk/north-west/" target="_blank">
                <img src="/images/logos/Arriva-270.jpg" class="span3" alt="Arriva logo" />
            </a>
           
              <a href="https://www.servicegraphics.co.uk/" target="_blank">
                <img src="/images/logos/service-graphics-270.jpg" class="span3" alt="Service Graphics logo" />
            </a>
            
         <a href="https://www.liverpoolbidcompany.com/" target="_blank">
                <img src="/images/Liverpool-BID-logo.jpg" class="span3" alt="Liverpool BID Company"></a>   
              
                 </div>
           
                
             <div class="page-header">
            <h1><small>Champions</small></h1>
            </div>
           
                 <ul>
               <li>Medicash</li>
               <li>Liverpool City Council</li>
               <li>Royal Liver Building</li>
               <li>HSBC</li>
               <li>Morecrofts</li>
               <li>Jan McDermott & Co</li>
               <li>Maggie Mullen Architects</li>
               <li>Hyperion Executive Search</li>
               <li>Go3 Partners</li>
               <li>Derwent Lodge Estates</li>
               </ul>
               
               
               
               <!--
            
            <div class="row">
                   <a href="http://www.rhodesbrook.co.uk/" target="_blank">
                <img src="/images/logos/rhodes-brook-270.jpg" class="span3" alt="Rhodes Brook Financial Management logo" />
               </a>   
                  
                  <a href="http://www.maggiemullanarchitects.co.uk/" target="_blank">
                <img src="/images/logos/maggie-mullen-architects-270.jpg" class="span3" alt="Maggie Mullen Architects logo" />
               </a>  
               
                <a href="http://hyperionsearch.co.uk/" target="_blank">
                <img src="/images/logos/hyperion-270.jpg" class="span3" alt="Hyperion Executive Search logo" />
               </a>  
               
                
            <a>
                <img src="/images/logos/go3-270.jpg" class="span3" alt="Go3 logo" />
               </a>
                  
           
                  </div>

                  <div class="row">
                  
                   <a>
                <img src="/images/logos/derwent-lodge-270.jpg" class="span3" alt="Derwent Lodge logo" />
               </a> 
               
                  -->
                  
           
                  

                
                <p>.</p>  
                  
             <div class="page-header">
            <h1><small>Past Supporters</small></h1>
            </div>
            
            <div class="row">
                   <a href="https://www.ljmu.ac.uk/" target="_blank">
                <img src="/images/logos/LJMU-web.jpg" class="span3" alt="Liverpool John Moores University" />
               </a>   
                  
                  <a href="https://www.tangleteezer.com/" target="_blank">
                <img src="/images/logos/TT-540.jpg" class="span3" alt="Tangle Teezer" />
               </a>  
               
                <a href="https://www.cassart.co.uk/" target="_blank">
                <img src="/images/logos/cass-art-270.jpg" class="span3" alt="Cass Art" />
               </a>  
               
                  <a href="https://www.merseyrail.org/" target="_blank">
                <img src="/images/logos/merseyrail-270.JPG" class="span3" alt="Mersey Rail" />
               </a>  
           
                  </div>
            
            <div class="row">
                   <a href="http://www.bigpartnership.co.uk" target="_blank">
                <img src="/images/logos/big-270.jpg" class="span3" alt="The Big Partnership logo" />
               </a>   
                  
                  <a href="http://www.renniesartsandcrafts.co.uk/" target="_blank">
                <img src="/images/logos/Rennies-270.jpg" class="span3" alt="Rennies logo" />
               </a>  
               
                <a href="http://www.albertdock.com/" target="_blank">
                <img src="/images/logos/Albert-Dock-Logo-270.jpg" class="span3" alt="Albert Dock logo" />
               </a>  
               
                
            <a href="http://www.artscouncil.org.uk/" target="_blank">
                <img src="/images/logos/ace-270.jpg" class="span3" alt="Arts Council England logo" />
               </a>
                  
           
                  </div>

            <div class="row">
            
            <a href="http://www.davidmrobinson.co.uk/" target="_blank">
                <img src="/images/logos/DMR-logo.jpg" class="span3" alt="David M Robinson logo" />
            </a>
            
            <a href="http://www.liverpoolmuseums.org.uk/walker/" target="_blank">
                <img src="/images/logos/Walker-270.jpg" class="span3" alt="Walker Art Gallery logo" />
            </a>
            
             <a href="http://www.cassellmoore.com/" target="_blank">
                <img src="/images/logos/Cassell-Moore-web.jpg" class="span3" alt="Cassell Moore logo" />
            </a>
                
                <a href="http://citycentralbid.com/" target="_blank">
                <img src="/images/logos/city-central-bid-270.jpg" class="span3" alt="City Central Bid logo" />
            </a> 
                

            
          </div>
          
           <div class="row">
        
                
            
          <a href="http://www.cfmerseyside.org.uk/index.php?p=145" target="_blank">
                <img src="/images/logos/L1-Foundation-270.jpg" class="span3" alt="Liverpool One Foundation logo" />
            </a>
            
                 <a href="http://www.cfmerseyside.org.uk/" target="_blank">
                <img src="/images/logos/CFM-270.jpg" class="span3" alt="Community Foundation for Merseyside logo" />
            </a>
                 <a href="http://www.rathbones.co.uk/" target="_blank">
                <img src="/images/logos/rathbones-270.jpg" class="span3" alt="Rathbones logo" />
            </a>
            
            <a href="http://liverpoolcityhalls.co.uk/st-georges-hall" target="_blank">
                <img src="/images/logos/SGH-270.jpg" class="span3" alt="St Georges Hall logo" />
            </a>
            
          </div>
          </div>
          
          
   <!--     
        <div class="tab-pane fade in" id="tab-partners">
            <h2>Partners</h2>   

           <div class="row">
            <a href="http://liverpool.gov.uk/">
                <img src="/images/logos/lcc-270.jpg" class="span3" alt="Liverpool City Council logo" />
            </a>
               <a href="http://www.liverpoolchamber.org.uk/">
                <img src="/images/logos/chamber-270.jpg" class="span3" alt="Liverpool and Sefton Chamber of Commerce logo" />
            </a>
              <a href="http://www.curiousminds.org.uk/">
                <img src="/images/logos/curious-minds-270.jpg" class="span3" alt="Curious Minds logo" />
            </a>  
            <a href="http://www.as-creatives.com/">
                <img src="/images/logos/as-creatives-270.jpg" class="span3" alt="As Creatives logo" />
            </a>
              </div>
                 <div class="row">
             <a href="http://www.ifb2014.com/">
                <img src="/images/logos/ifb-270.jpg" class="span3" alt="International Festival for Business logo" />
            </a> 
              <a href="http://www.ljmu.ac.uk/" >
                <img src="/images/logos/ljmu-270.jpg" class="span3" alt="Liverpool John Moores University logo" />
            </a>

              <a href="http://www.artsaward.org.uk/site/?id=1763/">
                <img src="/images/logos/arts-award-270.jpg" class="span3" alt="Arts Award Supporter logo" />
            </a>
              <a href="http://www.sthelens.gov.uk/">
                <img src="/images/logos/st-helens-council-270.jpg" class="span3" alt="St Helens Council logo" />
            </a>
            </div>
            
            -->
            
        </div>
        
    </div>
    
</div>
</div>
</div>

</div>
