<?php
   $this->headTitle('Thank You');
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">Thank You For Confirming</h1>
</div>

<p>Thank you for confirming your vote in the dot-art Schools competition 2017!</p>

<p>You are only allowed to vote once. However, if you wish to change your mind, just vote again to
replace this one.</p>

<p>The winners will be announced on this website after voting closes; we'll send you an email with the link 
so you can see if your favourite won. An exhibition will take place at in the gallery at Mid Cheshire College from the 8th to the 
17th June 2017 showcasing the winning artwork. For more information, visit
the <a href="http://cheshire.schools.dot-art.com/exhibition/year2017">Exhibition</a> page.</p>

<div class="container marketing">
<div class="row">
<div class="span12">
<img src="/images/LJMU-banner.jpg"
</div>
</div>
</div>


<!---
<p>This year's dot-art Schools programme has been made possible thanks to the generous support of our 
principal sponsor, David M Robinson; please take a look at their 
<a href="http://www.davidmrobinson.co.uk/">website.</a></p>
<a href="http://www.davidmrobinson.co.uk/"><img src="/images/logos/dmr-270.jpg" class="span3" alt="David M Robinson logo"/></a>
-->           

</div>
