<?php
   $this->headTitle('How To Vote');
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">How To Vote</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">How To Vote</li>
</ul>

<h3>Voting for the 2016-17 competition is open from 3rd April - 5th May 2017.</h3>

<p>During the Autumn and Spring terms, each participating school produces and submits up to 25 pieces of student work; 
these will be displayed on the project website from late March. A panel of art experts then selects the top 3 artworks from
each school. At this stage, staff, friends, family and the general public will be able to vote online for their favourite piece; 
the top art work from each school will be included in the final exhibition, which will take place at Mid Cheshire College in Northwich 
from 8th to the 17th of June 2017.</p> 

<p>On Thursday 7th June there will be two Prize Giving events (primary and secondary) for invited guests, 
at which we will announce the overall winner and two runners up for each age group. 
These winners will receive a selection of prizes including tickets to the next exhibition at Tate Liverpool, art materials and 
others yet to be announced, plus certificates will be presented to all three shortlisted pupils from each partipating school.
In addition we will be announcing the "dot-art Scholarship" which gives one exceptional Year 9 
student the opportunity to become part of dot-art's Artist Membership scheme for 12 months and display 
their work alongside professional artists.</p>

<p>Please see below for how the voting process works, and feel free to email 
<a href="mailto:schools@dot-art.com">schools@dot-art.com</a> with any questions.</p>

<h3>How To Vote</h3>

<ul>
<li>Select <b>Vote</b> from the menu along the top of the screen. View all the entries by choosing
either the <a href="/schools/secondary">Secondary Schools</a> or
<a href="/schools/primary">Primary Schools</a> page, where you will find all the schools taking part.
Click the <b>Browse Entries</b> button under each school logo to view their artwork; the three shortlisted entries are at the top of each page.</li>
<li>When you have selected your favourite piece from ALL the shortlisted entries, click the blue <b>Vote...</b> button under that piece. </li>
<li>A box will appear asking for your email address; please type this carefully and click the <b>Place your Vote</b> button.</li>
<li>You will then be sent an email containing a <b>confirmation link</b> 
(this is to ensure the system is not abused and everyone has one vote only), which you MUST CLICK to confirm your vote.</li>
</ul>

<h3>Voting Rules</h3>

<ul>
<li>One vote per person. If you change your mind, you can vote again, but your original vote will be cancelled.</li>
<li>Your vote will not be counted until you click the registration link sent to the email address you provide.</li>
<li>All votes must be placed before midnight on 5th May 2017.</li>
</ul>

<p>For more details about how the dot-art Schools Programme operates, visit the <a href="/what">What?</a> page.</p>

</div>
