<?php
   $this->headTitle('Contact');
   $this->headMeta()->appendName('description', 'Contact the dot-art Schools program, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">Contact</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Contact</li>
</ul>

<div class="row">

<div class="span12">

 <div class="row row-entry">

            <div class="span4">
            <img src="/images/2015-Exhibition/dot-art-Schools-2015-79.jpg" title="dot-art Schools Exhibition 2015" alt="dot-art Schools Exhibition 2015"/>
            </div>
            
            <div class="span4">
            <img src="/images/2015-Exhibition/dot-art-Schools-2015-53.jpg" title="dot-art Schools Exhibition 2015" alt="dot-art Schools Exhibition 2015"/>
            </div>
            
            <div class="span4">
            <img src="/images/2015-Exhibition/dot-art-Schools-2015-187.jpg" title="dot-art Schools Exhibition 2015" alt="dot-art Schools Exhibition 2015"/>
            </div>
            </div>




<p>If you are interested in getting involved in dot-art Schools, please see the <a href="/what">What?</a> page for further details, 
take a look at our <a href="http://liverpool.schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet-New.pdf">
Teachers Information Leaflet.</a></p>

     <p><a href="http://liverpool.schools.dot-art.com/docs/dot-art-Schools-Sign-Up-Form 2019-20.pdf">Download the Sign Up Form as PDF.</a></p>
    <p><a href="http://liverpool.schools.dot-art.com/docs/dot-art-Schools-Sign-Up-Form 2019-20.docx">Download the Sign Up Form as Word Doc.</a></p>
           
<!--

<p>**The deadline for entering dot-art Schools 2016-17 has now passed. If you are interested in taking part next
academic year, please download the leaflet below for more information and sign up to our SCHOOLS MAILING LIST
below.**</p>
<p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Entry-Form.pdf">Download the 2016-17 Entry Form</a></p>


-->        

<p>Alternatively, please contact us via email or phone:</p>

<table class="table table-condensed">
    <tr>
        <td>Email:</td>
        <td><a href="mailto:schools@dot-art.com">schools@dot-art.com</a></td>
    </tr>
    <tr>
        <td>Telephone:</td>
        <td>0345 017 6660</td>
    </tr>
    <tr>
        <td>Social Media:</td>
        <td><a href="https://twitter.com/dotartschools" target="_blank">
                <img src="/images/icons/twitter.png" title="Follow dot-art Schools on Twitter" alt="Twitter logo" />
            </a>
            <a href="https://www.facebook.com/dotartSchools" target="_blank">
                <img src="/images/icons/facebook.png" title="Like dot-art Schools on Facebook" alt="Facebook logo" />
            </a>
        </td>
    </tr>
</table>


</div>

</div>

<h3>Mailing Lists</h3>

<div class="span12">

 <div class="row row-entry">

            <div class="span6">
            
             <a class="btn btn-large btn-primary" href="http://eepurl.com/dtKE0H">Subscribe to the Liverpool City Region Schools List</a>

            </div>
            
            <div class="span6">
            
            <a class="btn btn-large btn-primary" href="http://eepurl.com/dtKC3H">Subscribe to the dot-art Schools Supporter List</a>
            
            </div>
            
            </div>


</div>