DROP TABLE IF EXISTS judging;

CREATE TABLE judging (
 entry_id     smallint,
 school       varchar(50),
 title        varchar(50),
 artist       varchar(50)
);

INSERT INTO judging (school, title, artist) VALUES ('Alder Hey Childrens'' Hospital School','The Rachelagiraffe','Rachel Kay');
INSERT INTO judging (school, title, artist) VALUES ('Alder Hey Childrens'' Hospital School','Ffion''s fishes','Ffion Davies');
INSERT INTO judging (school, title, artist) VALUES ('Alder Hey Childrens'' Hospital School','Penguin','Jozef Rostaf');
INSERT INTO judging (school, title, artist) VALUES ('Alsop High School','One Summers Day','Emma Fitzgerald');
INSERT INTO judging (school, title, artist) VALUES ('Alsop High School','Portrait','Emily Dooley');
INSERT INTO judging (school, title, artist) VALUES ('Alsop High School','Floral Folk Art 1','Charlie-Ann Grimes');
INSERT INTO judging (school, title, artist) VALUES ('Archbishop Beck Catholic School','Economic Self Portrait 12','Luis Duffy');
INSERT INTO judging (school, title, artist) VALUES ('Archbishop Beck Catholic School','Economic Self Portrait 8','Phil Doherty');
INSERT INTO judging (school, title, artist) VALUES ('Archbishop Beck Catholic School','Economic Self Portrait 6','Georgina Plews');
INSERT INTO judging (school, title, artist) VALUES ('Arnot St Mary Cofe Primary School','Trees','Tarryn Pepper');
INSERT INTO judging (school, title, artist) VALUES ('Arnot St Mary Cofe Primary School','The Sea of Fungus','Charlie Brasier');
INSERT INTO judging (school, title, artist) VALUES ('Arnot St Mary Cofe Primary School','Morning Dew','Jamie-lee Curran');
INSERT INTO judging (school, title, artist) VALUES ('Bellerive FCJ Catholic College','Pop Art portrait','Shauna Connor-Ashton');
INSERT INTO judging (school, title, artist) VALUES ('Bellerive FCJ Catholic College','The Stag','Emma Quinn');
INSERT INTO judging (school, title, artist) VALUES ('Bellerive FCJ Catholic College','Untitled 3','Lilybelle Carroll');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen International School','Hindu Dream','Hannah Jones');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen International School','Flowers of India','Nethu Armadooru');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen International School','Portrait Inspired by Picasso','Jessica Stringer');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen Primary School','Spirals','Summer Taylor');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen Primary School','Walk of Inspiration','Ella Wake');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen Primary School','Natures beautiful greatness','Joe Bowles');
INSERT INTO judging (school, title, artist) VALUES ('Broughton Hall Catholic High School','Japanese Landscape 6','Katherin Barry-Magowan');
INSERT INTO judging (school, title, artist) VALUES ('Broughton Hall Catholic High School','The Kimono 1','Olivia Lester');
INSERT INTO judging (school, title, artist) VALUES ('Broughton Hall Catholic High School','The Kimono 2','Ellie Bickley');
INSERT INTO judging (school, title, artist) VALUES ('Cardinal Heenan','Craig and Carl Influenced Portrait 3','Cameron Murphy');
INSERT INTO judging (school, title, artist) VALUES ('Cardinal Heenan','Craig and Carl Influenced Portrait 7','James Washington');
INSERT INTO judging (school, title, artist) VALUES ('Cardinal Heenan','Craig and Carl Influenced Portrait 4','Dillon Loftus');
INSERT INTO judging (school, title, artist) VALUES ('Childwall Academy','Marilyn Monroe','Freya Baxter');
INSERT INTO judging (school, title, artist) VALUES ('Childwall Academy','Pop art graffitti','Erin Atherton');
INSERT INTO judging (school, title, artist) VALUES ('Childwall Academy','Pop Farah','Mischa Evans-Foster');
INSERT INTO judging (school, title, artist) VALUES ('Deyes High School','India in Wonderland','India Edwards');
INSERT INTO judging (school, title, artist) VALUES ('Deyes High School','What if I fly','Oleena Aggarwal');
INSERT INTO judging (school, title, artist) VALUES ('Deyes High School','Alien Jigsaw','Thomas Armitage');
INSERT INTO judging (school, title, artist) VALUES ('ESLA','Self Image','Eleanor Murphy');
INSERT INTO judging (school, title, artist) VALUES ('ESLA','Realistic Eye','Lisa Chan');
INSERT INTO judging (school, title, artist) VALUES ('ESLA','Coloured Eye','Fabian Ennis');
INSERT INTO judging (school, title, artist) VALUES ('Evelyn Community Primary School','Rainbow Tears','Jack Foster');
INSERT INTO judging (school, title, artist) VALUES ('Evelyn Community Primary School','Splat','Elizabeth Wood');
INSERT INTO judging (school, title, artist) VALUES ('Evelyn Community Primary School','Tree of truth','Poppy Lester');
INSERT INTO judging (school, title, artist) VALUES ('Florence Melly Community Primary','Footballer','Cameron Smith');
INSERT INTO judging (school, title, artist) VALUES ('Florence Melly Community Primary','Pearly Cat','Emily Nicholls');
INSERT INTO judging (school, title, artist) VALUES ('Florence Melly Community Primary','Mickey Mouse','Lewis Taylor');
INSERT INTO judging (school, title, artist) VALUES ('Gateacre School','The Joker','Chloe Timmins-Young');
INSERT INTO judging (school, title, artist) VALUES ('Gateacre School','Comic art joshua','Joshua Heron');
INSERT INTO judging (school, title, artist) VALUES ('Gateacre School','Comic art Chloe','Chloe Dean');
INSERT INTO judging (school, title, artist) VALUES ('Greenbank High School','Orange Flower','Sofia Sargeeva');
INSERT INTO judging (school, title, artist) VALUES ('Greenbank High School','Foxglove','Holly Gardner');
INSERT INTO judging (school, title, artist) VALUES ('Greenbank High School','Eye 2','Sian Isobel-Fitzgerald');
INSERT INTO judging (school, title, artist) VALUES ('Gwladys Street Primary School','Pop Art Portrait 23','Melissa Scott');
INSERT INTO judging (school, title, artist) VALUES ('Gwladys Street Primary School','Pop Art Portrait 21','Lucas Whelan');
INSERT INTO judging (school, title, artist) VALUES ('Gwladys Street Primary School','Pop Art Portrait 15','Joshua Williams');
INSERT INTO judging (school, title, artist) VALUES ('Harmonize Academy','Number 1','Connor Tomlinson');
INSERT INTO judging (school, title, artist) VALUES ('Harmonize Academy','In the Stars','Dominic Dang');
INSERT INTO judging (school, title, artist) VALUES ('Harmonize Academy','Block','Liam Redmound');
INSERT INTO judging (school, title, artist) VALUES ('Hillside High School','Dia de los muertos','Jude Evans');
INSERT INTO judging (school, title, artist) VALUES ('Hillside High School','Death becomes her','Grace Lees Hampson');
INSERT INTO judging (school, title, artist) VALUES ('Hillside High School','Day of the Dead','Haider Heydari');
INSERT INTO judging (school, title, artist) VALUES ('Holly Lodge Girls College','Macaw','Sadie Clarke');
INSERT INTO judging (school, title, artist) VALUES ('Holly Lodge Girls College','Abstract Bubbles','Lucy Shone');
INSERT INTO judging (school, title, artist) VALUES ('Holly Lodge Girls College','Neon Galaxy','Christina Ketsani');
INSERT INTO judging (school, title, artist) VALUES ('Hope School','Portrait 4','Jamie Manning');
INSERT INTO judging (school, title, artist) VALUES ('Hope School','Portrait 3','Connor Dunn');
INSERT INTO judging (school, title, artist) VALUES ('Hope School','Animal Kingdom 1','Beau Balzan');
INSERT INTO judging (school, title, artist) VALUES ('Knotty Ash Primary','Red Skull','Finley Wilson');
INSERT INTO judging (school, title, artist) VALUES ('Knotty Ash Primary','Grass Hospital','Holly Brown');
INSERT INTO judging (school, title, artist) VALUES ('Knotty Ash Primary','Poppy Trail','Tamika Michaels');
INSERT INTO judging (school, title, artist) VALUES ('Liverpool College','The Hulk','Tito Carrasco Brenan');
INSERT INTO judging (school, title, artist) VALUES ('Liverpool College','Sahil Self portrait','Sahil Dugg');
INSERT INTO judging (school, title, artist) VALUES ('Liverpool College','Feel The Force','Marcus Lathar');
INSERT INTO judging (school, title, artist) VALUES ('Maghull High School','Clown Portrait 24','Holly-Jo Litherland');
INSERT INTO judging (school, title, artist) VALUES ('Maghull High School','Clown Portrait 22','Amy Haston');
INSERT INTO judging (school, title, artist) VALUES ('Maghull High School','Clown Portrait 13','Heather Sullivan-Marsha');
INSERT INTO judging (school, title, artist) VALUES ('Maricourt High School','Dan and Phil','Chelle Houseman');
INSERT INTO judging (school, title, artist) VALUES ('Maricourt High School','Fun house','Rachel Callaghan');
INSERT INTO judging (school, title, artist) VALUES ('Maricourt High School','Jazz hands','Rachel Gaffney');
INSERT INTO judging (school, title, artist) VALUES ('Merton Bank Primary School','Musical Planets','Robert Rowlands');
INSERT INTO judging (school, title, artist) VALUES ('Merton Bank Primary School','4 Soldiers Silhouettes','Rhian Prescott');
INSERT INTO judging (school, title, artist) VALUES ('Merton Bank Primary School','Soldiers Silhouette','Aaron Deane');
INSERT INTO judging (school, title, artist) VALUES ('Much Woolton Primary School','Art work in the style of Juan Miro 15','Kealan Jones');
INSERT INTO judging (school, title, artist) VALUES ('Much Woolton Primary School','Portrait in the style of Picasso 3','Emma Murray-Lunt');
INSERT INTO judging (school, title, artist) VALUES ('Much Woolton Primary School','Portrait in the style of Picasso 9','Ella Hoey');
INSERT INTO judging (school, title, artist) VALUES ('Neston High School','fish-pattern-detail','Rebecca Levene');
INSERT INTO judging (school, title, artist) VALUES ('Neston High School','Fly','Erin Coleman');
INSERT INTO judging (school, title, artist) VALUES ('Neston High School','Stick and ink insect','Ryan Hague');
INSERT INTO judging (school, title, artist) VALUES ('Norman Pannell School (Primary)','Moving Silhouette 9','Aaron Edgerton');
INSERT INTO judging (school, title, artist) VALUES ('Norman Pannell School (Primary)','Moving Silhouette 8','Brooklyn Taylor');
INSERT INTO judging (school, title, artist) VALUES ('Norman Pannell School (Primary)','Moving Silhouette 3','Kaylin Gould');
INSERT INTO judging (school, title, artist) VALUES ('Ormiston Bolingbroke Academy','Sticks and inks','Sophie Milne');
INSERT INTO judging (school, title, artist) VALUES ('Ormiston Bolingbroke Academy','Runcorn Hill Study','Owen Baines');
INSERT INTO judging (school, title, artist) VALUES ('Ormiston Bolingbroke Academy','Photo Cubism 1','Archie Mason');
INSERT INTO judging (school, title, artist) VALUES ('Our Lady of Peace Catholic Engineering College','Alice in wonderland','Emily Bridges');
INSERT INTO judging (school, title, artist) VALUES ('Our Lady of Peace Catholic Engineering College','Entrancing','Amy Meehan');
INSERT INTO judging (school, title, artist) VALUES ('Our Lady of Peace Catholic Engineering College','The humming bird','Abigail Allen');
INSERT INTO judging (school, title, artist) VALUES ('Rainhill High School','Self Portrait 1','Harry Whitworth Reitze');
INSERT INTO judging (school, title, artist) VALUES ('Rainhill High School','Cogs and Wheels','Dylan McGrath');
INSERT INTO judging (school, title, artist) VALUES ('Rainhill High School','Tentacle collage','Ethan Pilkington');
INSERT INTO judging (school, title, artist) VALUES ('Shavington Academy','ARTitecture - Ian Murphy Inspired Response 17','Tallulah Powell');
INSERT INTO judging (school, title, artist) VALUES ('Shavington Academy','ARTitecture Goodnight 13','Connor Baker');
INSERT INTO judging (school, title, artist) VALUES ('Shavington Academy','ARTitecture 1','Alfie Smith');
INSERT INTO judging (school, title, artist) VALUES ('South Wirral High School','Celtic Capital Letters w/ a Contemporary Twist 22','Josh Stocker');
INSERT INTO judging (school, title, artist) VALUES ('South Wirral High School','Celtic Capital Letters w/ a Contemporary Twist 24','Jade Muirhead');
INSERT INTO judging (school, title, artist) VALUES ('South Wirral High School','Celtic Capital Letters w/ a Contemporary Twist 17','Olivia Wilson');
INSERT INTO judging (school, title, artist) VALUES ('St Bedes Catholic Junior School','Still Life','Abigail Morris');
INSERT INTO judging (school, title, artist) VALUES ('St Bedes Catholic Junior School','Atmospheric Clouds','Jimmy Kaye');
INSERT INTO judging (school, title, artist) VALUES ('St Bedes Catholic Junior School','Boston Terrier','Aiden Owen');
INSERT INTO judging (school, title, artist) VALUES ('St Cuthberts Primary School','Minimal abstract','Jude Tennant');
INSERT INTO judging (school, title, artist) VALUES ('St Cuthberts Primary School','Spies','Lauren Bradburne');
INSERT INTO judging (school, title, artist) VALUES ('St Cuthberts Primary School','Landscape','Josh McElroy');
INSERT INTO judging (school, title, artist) VALUES ('St Chads Catholic & CofE High School','Exotic-Plants-Print-2','Emily Penlington');
INSERT INTO judging (school, title, artist) VALUES ('St Chads Catholic & CofE High School','Fossils','Mathew Davies ');
INSERT INTO judging (school, title, artist) VALUES ('St Chads Catholic & CofE High School','Seed Pods 2','Molley Hickey ');
INSERT INTO judging (school, title, artist) VALUES ('St Hildas CoE High School','Golden Tamarin','Nyah Boorman');
INSERT INTO judging (school, title, artist) VALUES ('St Hildas CoE High School','Cloud Leopard','Niamh Boorman');
INSERT INTO judging (school, title, artist) VALUES ('St Hildas CoE High School','Michael Craig Madness','Calise McGill');
INSERT INTO judging (school, title, artist) VALUES ('St John Bosco Arts College','Georgia O''Keeffe Flower 2','Guste Ditaliskaite');
INSERT INTO judging (school, title, artist) VALUES ('St John Bosco Arts College','Untitled','Chloe Mcarthy');
INSERT INTO judging (school, title, artist) VALUES ('St John Bosco Arts College','African Skull Mask','Ashliegh Louise Boot');
INSERT INTO judging (school, title, artist) VALUES ('St Julies Catholic High','Lily','Holly Robinson-Tilly');
INSERT INTO judging (school, title, artist) VALUES ('St Julies Catholic High','Flowers 2','Emma White');
INSERT INTO judging (school, title, artist) VALUES ('St Julies Catholic High','Flowers 7','Ella Wellsby');
INSERT INTO judging (school, title, artist) VALUES ('St Michael & All Angels','The Poppies of Life','Alex Hill');
INSERT INTO judging (school, title, artist) VALUES ('St Michael & All Angels','War is Over, Peace has Begun','Dillon Glinton');
INSERT INTO judging (school, title, artist) VALUES ('St Michael & All Angels','Poppy Land','Lucy Hitchmough');
INSERT INTO judging (school, title, artist) VALUES ('St Michael''s Catholic Primary','A Surrealist Dream 2','Lucy Carr');
INSERT INTO judging (school, title, artist) VALUES ('St Michael''s Catholic Primary','A Surrealist Dream 5','James Cowling ');
INSERT INTO judging (school, title, artist) VALUES ('St Michael''s Catholic Primary','A Surrealist Dream 15','Amelia Richardson');
INSERT INTO judging (school, title, artist) VALUES ('St Patrick''s Catholic Primary','Doodle Art - Owl','Rhonesha Kamara');
INSERT INTO judging (school, title, artist) VALUES ('St Patrick''s Catholic Primary','Doodle Art - Duck 1','Diana Loretto Amaral');
INSERT INTO judging (school, title, artist) VALUES ('St Patrick''s Catholic Primary','Doodle Art - Elephant','Saya Majid');
INSERT INTO judging (school, title, artist) VALUES ('St Sebastians Primary School','Big Ben','Lucy Stenson ');
INSERT INTO judging (school, title, artist) VALUES ('St Sebastians Primary School','Pastel Abstract','Sam Boyle');
INSERT INTO judging (school, title, artist) VALUES ('St Sebastians Primary School','Kandinsky Shapes','Dempsey Ager');
INSERT INTO judging (school, title, artist) VALUES ('The Academy of St Francis of Assisi','Jurrasic','Jhonn Leuffa');
INSERT INTO judging (school, title, artist) VALUES ('The Academy of St Francis of Assisi','Spiritual','Khadeja Downer');
INSERT INTO judging (school, title, artist) VALUES ('The Academy of St Francis of Assisi','Do you believe in fairies','Maria Evans');
INSERT INTO judging (school, title, artist) VALUES ('The Heath','Parallel Death','Molly Kenwright');
INSERT INTO judging (school, title, artist) VALUES ('The Heath','Uncover','Laurena Betton');
INSERT INTO judging (school, title, artist) VALUES ('The Heath','Death Doodle','Liam Charnley');
INSERT INTO judging (school, title, artist) VALUES ('The Kingsway Academy','Street Art 1','Ella Canavan');
INSERT INTO judging (school, title, artist) VALUES ('The Kingsway Academy','Street Art 2','Tayla Mercer');
INSERT INTO judging (school, title, artist) VALUES ('The Kingsway Academy','Music 1','Jessie Stanley');
INSERT INTO judging (school, title, artist) VALUES ('The Oldershaw Academy','Resilience','Maddie Luetchford');
INSERT INTO judging (school, title, artist) VALUES ('The Oldershaw Academy','Moonlit Disguise','Emily Mason');
INSERT INTO judging (school, title, artist) VALUES ('The Oldershaw Academy','Disguise','Mia Swanick');
INSERT INTO judging (school, title, artist) VALUES ('The Prescot School (Knowsley Park)','My View','Silan Bozkurt');
INSERT INTO judging (school, title, artist) VALUES ('The Prescot School (Knowsley Park)','Hiya Polly','Phoebe Harper');
INSERT INTO judging (school, title, artist) VALUES ('The Prescot School (Knowsley Park)','Sunlit','Emma Ambrose');
INSERT INTO judging (school, title, artist) VALUES ('Thomas Gray Primary School','3D op art 21','Ruby Lunt');
INSERT INTO judging (school, title, artist) VALUES ('Thomas Gray Primary School','3D op art 1','Ashton George');
INSERT INTO judging (school, title, artist) VALUES ('Thomas Gray Primary School','3D op art 4','Bobbie Speers');
INSERT INTO judging (school, title, artist) VALUES ('West Derby High','Daniel Craig 007','Charlie Parry');
INSERT INTO judging (school, title, artist) VALUES ('West Derby High','Muhammad-Ali','Callum Childs-Bandell');
INSERT INTO judging (school, title, artist) VALUES ('West Derby High','Don''t Worry About a Thing','Junior Kasavubu');
INSERT INTO judging (school, title, artist) VALUES ('West Kirby Residential','Window 1','Owen Clarke');
INSERT INTO judging (school, title, artist) VALUES ('West Kirby Residential','Window 2','Connor Swift');
INSERT INTO judging (school, title, artist) VALUES ('West Kirby Residential','Window 3','Jonny Roberts');
INSERT INTO judging (school, title, artist) VALUES ('Woodchurch High School','Window of Light','Rebecca Adams');
INSERT INTO judging (school, title, artist) VALUES ('Woodchurch High School','Butterflies are self propelled flowers','Kirsty McNelis');
INSERT INTO judging (school, title, artist) VALUES ('Woodchurch High School','They gave their tomorrow for our today','Katie Spence');

UPDATE judging j
  JOIN entry e ON j.`artist` = e.`artist` AND j.`title` = e.`title`
   SET j.`entry_id` = e.`entry_id`;

UPDATE entry e
  JOIN judging j ON j.`artist` = e.`artist` AND j.`title` = e.`title`
   SET e.`rank` = 1;
