<?php
   $this->headTitle('News');
   $this->headMeta()->appendName('description', 'News from participants in dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">News</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">News <span class="divider">/</span></li>
  <li class="active">News</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>

<!-- Put SPAN6 DIVs here for each news item:  -->

<div class="row">
	<div class="span6">
		<h3>dotartSchools Twitter Feed</h3>
		<a class="twitter-timeline" height="1000" href="https://twitter.com/dotartschools" data-widget-id="381020540489584641">Tweets by @dotartschools</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
    
    <p>.</p>
		
    	</div>
      
<div class="span6">
		<h3>Creative Careers Poster</h3>
    
     <a href="http://liverpool.schools.dot-art.com/docs/dot-art-Creative-Careers-Poster.pdf" target="_blank">
      <img src="/images/dot-art-Creative-Careers-Poster-web.jpg" class="span6" alt="dot-art Schools Creative Careers Poster" /> </a>
    

    <p><b>dot-art Schools has commissioned graphic artist Thom Isom to produce this fantastic poster, which is FREE to download
    (click the image) and will also be posted out to secondary schools across the Liverpool City Region.</b</p>
    
    <p><b>Thom worked with groups of creative industries professionals, recent graduates, current students and the general public
    to find out what barriers exist to working towards a creative career, why and how people choose to study creative
    subjects and the huge advantages this can bring. The result is this inspirational image, highlighting the huge number of 
    jobs in the creative industries (which is the fastest growing sector in the UK) and just some of the reasons why working
    towards a creative career is such a fantastic idea!</p>

    <p>We are grateful to Arts Council England for their support of this project.</p>
    
            <p>.</p>   
    
     
    
	</div>  
    
    
      
          	
	  </div>
        
        
              
  <!---ROW 2 -->  
  
    <div class="row"> 

<div class="span4">
		<h3>2017-18 Winners Announced!</h3>
    
 <p><b>The overall winners of the 2018 dot-art Schools Competition for the Cheshire region were announced at a 
prize-giving ceremony on 7th June at Storyhouse in Chester, where the top three students from each of the participating 
schools were presented with a certificate and the six overall winners and runners up received their prizes.</p> 

    
    <p><b>Pranathi Tulasi from The Catholic High School Chester won the Year 9 award for her piece "Susan Davis Painting 1".</b>
</p>

 <p><b>Tahlia Buckley from Acton CE Primary Academy won the Year 5 award for her piece "Tahlia's Wave"</b>
</p>

      <p><b>More details and full list of winners can be found on the 
    <a href="http://liverpool.schools.dot-art.com/exhibition/year2018">Exhibition Page.</a></b</p>
    
       <p>.</p>   
    </div>
    
<div class="span4">    

    <img src="/images/dot-art-Schools-Cheshire-Secondary-Winner-2018-web.JPG" class="span12" alt="dot-art Schools Cheshire Winner 2018" />
  <p>.</p>
 
 </div>
    
<div class="span4">
     
      <img src="/images/dot-art-Schools-Cheshire-Primary-Winner-2018-web.JPG" class="span12" alt="dot-art Schools Cheshire Winner 2018"/>

      
     
</div>
   </div>

  
   <!---ROW 3 -->  
   
   
  
  <div class="row">
  
  <div class="span6">
		<h3>Partnership with LJMU</h3>

    
    <p><b>Liverpool John Moores University (LJMU) has become the official partner of dot-art Schools and aims to help us 
    inspire the region’s next generation of Turners and Emins.</b</p>
    
    <p><b>Lucy Byrne, Managing Director of dot-art commented: <i>"We are absolutely delighted to be working with LJMU to increase 
    the reach and impact of the dot-art Schools programme. This long term partnership will mean we can develop and expand 
    the scheme in the Liverpool City Region as well as allowing us to fulfil a long held ambition to extend its reach into Cheshire.
    </i></b></p>

    <p><b>Professor Nigel Weatherill, Vice Chancellor at LJMU said: <i>"Our partnership with dot-art highlights the importance 
    Liverpool John Moores University places on enabling future generations of talent to benefit from the creativity that 
    Liverpool offers.  As a modern civic university, we invest in keeping young people engaged with the arts, inspiring 
    them to consider a creative career path, and encouraging their interest in the cultural community around them."</i></b></p>
    
	</div>
  
  <div class="span6">
		
    <p>.</p>

      <a href="https://www.ljmu.ac.uk/" target="_blank">
      <img src="/images/logos/LJMU-web.jpg" class="span6" alt="Liverpool John Moores University" /> </a>
      
     
	</div>
  
 </div>
  

   <!---ROW 4 -->  
  
  <div class="row"> 

<div class="span6">
		<h3>Artsmark Partner Status</h3>

     <p>We are pleased to announce that from February 2018, dot-art Schools is an 
              <a href="http://www.artsmark.org.uk/artsmark-partnership-programme">Artsmark Partner</a>.
              Artsmark is the creative quality standard for schools and education
              settings, awarded by Arts Council England, recognising their
              commitment to high quality arts and cultural education.
              dot-art Schools is proud to be supporting schools and
              education settings on their Artsmark journey, inspiring children and
                young people to create, experience, and participate in great arts and
              culture.</p>  
              
              <p>Find out more about Artsmark at <a href="http://www.artsmark.org.uk.">artsmark.org.uk</a>
              To find out how we can support your
                Artsmark journey, contact Carolyn on 0345 0176660.
              </p>  
              
               <p>.</p>   
    </div>
    
<div class="span6">   
     
      <img src="/images/artsmark-partner-600.jpg"  alt="dot-art Schools is an Artsmark Partner" />
</div>
</div>   

  <!---ROW 5 -->  
	
  
  <div class="row">   
     
      
<div class="span4">
	       <h3>2016-17 Winners Announced!</h3>
     
     <p><b>The overall winners of the 2017 dot-art Schools Competition for the Cheshire region were announced at a 
prize-giving ceremony on 7th June, where the top three students from each of the participating schools were
presented with a certificate and the six overall winners and runners up received their prizes.</p> 


<p><b>Brigid Keighran from St Nicholas Catholic High School won the Year 9 award for her piece "Ganesha".<br></p>

<p>Milo Forster from Kelsall Primary School won the Year 5 award for his piece "Barn Owl".<br></p>
     
   <p><b>More details and full list of winners can be found on the 
    <a href="http://cheshire.schools.dot-art.com/exhibition">Exhibition Page.</a></b</p>
 
	</div> 

 <div class="span4">
		
     <a><img src="http://cheshire.schools.dot-art.com/images/dot-art-Schools-Cheshire-Secondary-Winner-web.jpg" 
     alt="dot-art Schools Cheshire 2017 Winners" /></a>
                
  </div>
  
  <div class="span4">
		
     <a><img src="http://cheshire.schools.dot-art.com/images/dot-art-Schools-Cheshire-Primary-Winner-web.jpg" 
     alt="dot-art Schools Cheshire 2017 Winners" /></a>
                
  </div>                     
    
    
	</div>  

<!---ROW 6 -->        


<div class="row">   

<div class="span12">
		<h3>Free Event to Help Teachers Champion Creative Careers in Schools</h3>

     <a href="https://championcreativecareers.eventbrite.com" target="_blank">
                <img src="/images/dot-art-Schools-Creative-Careers-Event-Flyer.jpg"  
                alt="Champion Creative Careers Day" /></a>

     <p>.</p>
     
     <p><b>On Friday 23rd June, dot-art Schools and partners Liverpool John Moores University are holding an inspirational 
     day of advocacy to help education professionals to champion the value and impact of studying art. The event will 
     begin with a tour of the LJMU Art and Design Academy, followed by a visit to the 2017 dot-art Schools exhibition in 
     St Georges Hall, then finish by hearing from three expert speakers on the diverse and vital range of careers that are 
     opened up by a creative education</b</p>
     
     <p><b><a href="https://championcreativecareers.eventbrite.com" target="_blank">ITS FREE! More details and booking here.</a></p></b>
    
    
	</div> 


    
    
	</div>  
  
      
