<?php
   $this->headTitle('News');
   $this->headMeta()->appendName('description', 'News from participants in dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">News</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">News <span class="divider">/</span></li>
  <li class="active">News</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>

<!-- Put SPAN6 DIVs here for each news item:  -->

<div class="row">
	<div class="span6">
		<h3>dotartSchools Twitter Feed</h3>
		<a class="twitter-timeline" height="600" href="https://twitter.com/dotartschools" data-widget-id="381020540489584641">Tweets by @dotartschools</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
    
    <p>.</p>
		
    	</div>
      
    
    
      
          	<div class="span6">
		<h3>NEW - Partnership with LJMU</h3>

      <a href="https://www.ljmu.ac.uk/" target="_blank">
      <img src="/images/logos/LJMU-web.jpg" class="span6" alt="Liverpool John Moores University" /> </a>
      
      <p>.</p>
    
    <p><b>Liverpool John Moores University (LJMU) has become the official partner of dot-art Schools and aims to help us 
    inspire the region’s next generation of Turners and Emins.</b</p>
    
    <p><b>Lucy Byrne, Managing Director of dot-art commented: <i>"We are absolutely delighted to be working with LJMU to increase 
    the reach and impact of the dot-art Schools programme. This long term partnership will mean we can develop and expand 
    the scheme in the Liverpool City Region as well as allowing us to fulfil a long held ambition to extend its reach into Cheshire.
    </i></b></p>

    <p><b>Professor Nigel Weatherill, Vice Chancellor at LJMU said: <i>"Our partnership with dot-art highlights the importance 
    Liverpool John Moores University places on enabling future generations of talent to benefit from the creativity that 
    Liverpool offers.  As a modern civic university, we invest in keeping young people engaged with the arts, inspiring 
    them to consider a creative career path, and encouraging their interest in the cultural community around them."</i></b></p>
    
	</div>
	  </div>
        

<!---ROW 2 -->        
<div class="row">    

	<div class="span6">
		
	</div>
  
  	<div class="span6">
    
  </div>
      
						
		 	</div>
      
      
  <!---ROW 3 -->      
	