<?php
   $this->headTitle('Press');
   $this->headMeta()->appendName('description', 'Press releases about dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">News</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">News <span class="divider">/</span></li>
  <li class="active">Press</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>

<!-- Put SPAN6 DIVs here for each news item:  -->

<div class="row">
	<div class="span6">
	<h3>Press Releases</h3>
	<p>Click the links below to download information about the dot-art Schools programme.</p>
	<ul>
  <li><a href="http://cheshire.schools.dot-art.com/docs/dot-art-Schools-Cheshire-Winners-Press-Release.pdf" target="_blank">Press release, 9th June 2017.</a></li>
  <li><a href="http://cheshire.schools.dot-art.com/docs/dot-art-Schools-Press-Release-01-06-17.pdf" target="_blank">Press release, 1st June 2017 - Creative Careers Event.</a></li>
  <li><a href="/docs/dot-art-Schools-Press-Release-Cheshire-03-04-17.pdf" target="_blank">Press release, 3rd April 2017.</a></li>
   <li><a href="/docs/dot-art-Schools-Press-Release-09-12-16.pdf" target="_blank">Press release, 9th December 2016.</a></li>
     <li><a href="/docs/dot-art-Schools-Press-Release-07-10-16.pdf" target="_blank">Press release, 7th October 2016.</a></li>
    </ul>
	</div>
</div>

</div>
