<?php
   $this->headTitle('News');
   $this->headMeta()->appendName('description', 'News from participants in dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">News</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">News <span class="divider">/</span></li>
  <li class="active">News</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>

<!-- Put SPAN6 DIVs here for each news item:  -->

<div class="row">
	<div class="span6">
		<h3>dotartSchools Twitter Feed</h3>
		<a class="twitter-timeline" height="1000" href="https://twitter.com/dotartschools" data-widget-id="381020540489584641">Tweets by @dotartschools</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
    
    <p>.</p>
		
   
    	</div>
      
    
      	<div class="span6">
		<h3>Creative Careers Poster</h3>

      <a href="http://schools.dot-art.com/docs/dot-art-Creative-Careers-Poster.pdf" target="_blank">
      <img src="/images/dot-art-Creative-Careers-Poster-web.jpg" class="span6" alt="dot-art Schools Creative Careers Poster" /> </a>
      
    
    <p><b>dot-art Schools has commissioned graphic artist Thom Isom to produce this fantastic poster, which is FREE to download
    (click the image) and will also be posted out to secondary schools across the Liverpool City Region.</b</p>
    
    <p><b>Thom worked with groups of creative industries professionals, recent graduates, current students and the general public
    to find out what barriers exist to working towards a creative career, why and how people choose to study creative
    subjects and the huge advantages this can bring. The result is this inspirational image, highlighting the huge number of 
    jobs in the creative industries (which is the fastest growing sector in the UK) and just some of the reasons why working
    towards a creative career is such a fantastic idea!</p>

    <p>We are grateful to Arts Council England for their support of this project.</p>
    
	</div>
	      </div>
        
<!---ROW 2 -->

<div class="row"> 

<div class="span6">
		<h3>dot-art Schools Cheshire, 2017-2019</h3>

    <img src="/images/dot-art-Schools-Cheshire-2018-3.jpg" alt="dot-art Schools Cheshire" />
  <p>.</p>
 
<p><b>For three years, starting in the academic year 2016-17, we ran a second parallel dot-art Schools programme in 
Cheshire West and Chester, Cheshire East and Warrington, thanks to support from Liverpool John Moore University.
 Annual exhibitions were held in Hartford and Chester and we welcomed over 20 schools from across the region every year.</b>
</p>

 </div>
    
<div class="span6">   

<p>.</p>
<p>.</p>
   
      <img src="/images/dot-art-Schools-Cheshire-2018-2.jpg" alt="dot-art Schools Cheshire" />

<p>.</p>
      
      <p><b>From September 2019 onwards, these schools have been invited to take part in the main dot-art Schools 
      programme, as we consolidate our efforts and bring all schools into one combined annual exhibition in Liverpool.</b>
</p>

      <p><b>You can still see the amazing work of Cheshire schools from past years by visiting our
    <a href="http://schools.dot-art.com/archive/index/region/cheshire">Cheshire Archive section.</a></b</p>     
    </div>
</div>
        
        
<!---ROW 3 -->

<div class="row"> 

<div class="span6">
		<h3>2018-19 Winners Announced!</h3>

    <img src="/images/dot-art-Schools-Liverpool-Secondary-Winner-2019.jpg" alt="dot-art Schools Winner 2019" />
  <p>.</p>
 
<p><b>Earl Cabije of Cardinal Heenan Catholic High School won the Year 9 overall prize for his piece "Portrait of Earl".</b>
</p>

 </div>
    
<div class="span6">   

<p>.</p>
  <p>.</p>

     
      <img src="/images/dot-art-Schools-Liverpool-Primary-Winner-2019.jpg" class="span6" alt="dot-art Schools Winner 2019" />

<p>.</p>
      
      <p><b>Dana of Belle Vale Primary School won the Year 5 overall prize for her work "The Dark Eye".</b>
</p>

      <p><b>More details and full list of winners can be found on the 
    <a href="http://liverpool.schools.dot-art.com/exhibition/year2019">Exhibition Page.</a></b</p>     
    </div>
</div>

<!---ROW 4 -->

<div class="row"> 

<div class="span6">
		<h3>LJMU Festive Card Competition winners announced!</h3>


 
<p><b>dot-art Schools were pleased when Liverpool John Moores University asked us to launch a new competition for our 
schools to find an artwork design they could feature on their Christmas cards. With almost 200 high quality entries submitted 
the judges at LJMU had the challenging task of deciding upon a winner for both the primary and secondary age groups.</b>
</p>

<p><b>On Monday 17th Dec the dot-art Schools team attended a special LJMU festive reception which saw LJMU's Interim Vice 
Chancellor Mark Power & LJMU Honorary Fellow Jim Davies OBE congratulate Harry Chapman (year 3) & Zac Kavanagh (year 9) 
on winning the LJMU 2018 Christmas card competition. Proud parents and teachers from Gwladys St Primary & Maghull High 
also celebrated with their winning students. Each school receives an artist led workshop as a prize and the students were 
presented with an art book and framed sample of their winning Christmas card designs. Thousands of people will be able 
to enjoy the boys Christmas card designs over the festive season as LJMU send them all over the world. Well done Zac and 
Harry!</p></b>

 </div>
    
<div class="span6">   

<p>.</p>


     
      <img src="/images/LJMU-Christmas-Card.jpg" class="span6" alt="dot-art Schools LJMU Christmas Card competition winners" />

<p>.</p>
      
         
    </div>
</div>


<!---ROW 5 -->

<div class="row"> 

<div class="span6">
		<h3>2017-18 Winners Announced!</h3>

    <img src="/images/dot-art-Schools-Secondary-Overall-Winner-2018-web.jpg" alt="dot-art Schools Winner 2018" />
  <p>.</p>
 
<p><b>Jacob Crummey from St Margaret's Academy won the Year 9 award for his piece "Exploding Head 5".</b>
</p>

 </div>
    
<div class="span6">   

<p>.</p>


     
      <img src="/images/dot-art-Schools-Primary-Overall-Winner-2018-web.jpg" class="span6" alt="dot-art Schools Winner 2018" />

<p>.</p>
      
      <p><b>Harrison Fair from Eaves Primary School won the Year 6 award for his piece "The Rainforest Alive 11"</b>
</p>

      <p><b>More details and full list of winners can be found on the 
    <a href="http://liverpool.schools.dot-art.com/exhibition/year2018">Exhibition Page.</a></b</p>     
    </div>
</div>


<!---ROW 6 -->


<div class="row"> 

      	<div class="span6">
		<h3>NEW - Partnership with LJMU</h3>

      <a href="https://www.ljmu.ac.uk/" target="_blank">
      <img src="/images/logos/LJMU-web.jpg" class="span6" alt="Liverpool John Moores University" /> </a>
      
      <p>.</p>
    
    <p><b>Liverpool John Moores University (LJMU) has become the official partner of dot-art Schools and aims to help us 
    inspire the region’s next generation of Turners and Emins.</b</p>
    
    <p><b>Lucy Byrne, Managing Director of dot-art commented: <i>"We are absolutely delighted to be working with LJMU to increase 
    the reach and impact of the dot-art Schools programme. This long term partnership will mean we can develop and expand 
    the scheme in the Liverpool City Region as well as allowing us to fulfil a long held ambition to extend its reach into Cheshire.
    </i></b></p>

    <p><b>Professor Nigel Weatherill, Vice Chancellor at LJMU said: <i>"Our partnership with dot-art highlights the importance 
    Liverpool John Moores University places on enabling future generations of talent to benefit from the creativity that 
    Liverpool offers.  As a modern civic university, we invest in keeping young people engaged with the arts, inspiring 
    them to consider a creative career path, and encouraging their interest in the cultural community around them."</i></b></p>
    
	</div>
  
 <div class="span6">
		<h3>Merseyrail Exhibition</h3>

                <img src="/images/merseyrail-2018.jpg"  alt="dot-art Schools Merseyrail exhibition 2018" />

     <p>.</p>
     
     <p><b>From the 2nd August -1st September 2018 you can view a digital version of the dot-art Schools Exhibition at Lime Street
     Lower Level Station, thanks to our ongoing partnership with Merseyrail.</b</p>
    
 
    
	</div>  
  </div>
  
  <!---ROW 7 -->




<div class="row"> 

<div class="span6">
		<h3>Artsmark Partner Status</h3>

     <p>We are pleased to announce that from February 2018, dot-art Schools is an 
              <a href="http://www.artsmark.org.uk/artsmark-partnership-programme">Artsmark Partner</a>.
              Artsmark is the creative quality standard for schools and education
              settings, awarded by Arts Council England, recognising their
              commitment to high quality arts and cultural education.
              dot-art Schools is proud to be supporting schools and
              education settings on their Artsmark journey, inspiring children and
                young people to create, experience, and participate in great arts and
              culture.</p>  
              
              <p>Find out more about Artsmark at <a href="http://www.artsmark.org.uk.">artsmark.org.uk</a>
              To find out how we can support your
                Artsmark journey, contact Carolyn on 0345 0176660.
              </p>     
    </div>
    
<div class="span6">   
     
      <img src="/images/artsmark-partner-600.jpg"  alt="dot-art Schools is an Artsmark Partner" />
</div>
</div>

    <!---ROW 8 -->

<div class="row">   

<div class="span6">
		<h3>Merseyrail Exhibition</h3>

                <img src="/images/merseyrail-2017.jpg"  alt="dot-art Schools Merseyrail exhibition 2017" />

     <p>.</p>
     
     <p><b>From the 6th July - 6th August 2017 you can view a digital version of the dot-art Schools Exhibition at Lime Street
     Lower Level Station, thanks to our ongoing partnership with Merseyrail.</b</p>
    
 
    
	</div> 

<div class="span6">
		<h3>2016-17 Winners Announced!</h3>

   
               <img src="/images/dot-art-Schools-Liverpool-Winners-2017.jpg" alt="dot-art Schools Winners 2017" />
  <p>.</p>
 
<p><b>Erin Gerrard from The Sutton Academy won the Year 9 award for her piece "Intergalactic".
Grace McKeown from Knotty Ash Primary School won the Year 6 award for her piece "Lost Soul".</p>

 <p><b>More details and full list of winners can be found on the 
    <a href="http://liverpool.schools.dot-art.com/exhibition/year2017">Exhibition Page.</a></b</p>
    
    
	</div> 
  </div> 
  
  <!---ROW 9 --> 

<div class="row">   

<div class="span12">
		<h3>Free Event to Help Teachers Champion Creative Careers in Schools</h3>

     <a href="https://championcreativecareers.eventbrite.com" target="_blank">
                <img src="/images/dot-art-Schools-Creative-Careers-Event-Flyer.jpg" class="span12" 
                alt="Champion Creative Careers Day" /></a>

     <p>.</p>
     
     <p><b>On Friday 23rd June, dot-art Schools and partners Liverpool John Moores University are holding an inspirational 
     day of advocacy to help education professionals to champion the value and impact of studying art. The event will 
     begin with a tour of the LJMU Art and Design Academy, followed by a visit to the 2017 dot-art Schools exhibition in 
     St Georges Hall, then finish by hearing from three expert speakers on the diverse and vital range of careers that are 
     opened up by a creative education</b</p>
     
     <p><b><a href="https://championcreativecareers.eventbrite.com" target="_blank">ITS FREE! More details and booking here.</a></p></b>
    
    
	</div> 


    
    
	</div>  
  
 <!---ROW 10 --> 

<div class="row">   

<div class="span6">
		<h3>Morecrofts Sponsor dot-art Schools</h3>

     <a href="https://www.morecrofts.co.uk/" target="_blank">
                <img src="/images/logos/morecrofts-270.jpg" class="span6" alt="Morecrofts Solicitors Sponsors dot-art Schools" /></a>

     <p>.</p>
     
     <p><b>We are delighted to announce that Liverpool based independent solicitors Morecrofts have joined us as sponsor of the 
     dot-art Schools Liverpool programme for 2016-17.</b</p>
    
 
    
	</div> 

<div class="span6">
		<h3>Cass Art Supports Young Talent</h3>

     <a href="https://www.cassart.co.uk/" target="_blank">
                <img src="/images/logos/cass-art-270.jpg" class="span6" alt="Cass Art Sponsors dot-art Schools" /></a>

   
     <p><b>Cass Art has once again signed up to sponsor the dot-art Schools Liverpool programme for 2016-17.
     The national art materials supplier, which has a branch in Liverpool One, will be supplying prizes to both the winning
      students and schools from this years programme.</b</p>
    
    
	</div>
  	</div>    
  
<!---ROW 11 -->

<div class="row">   

<div class="span6">
		<h3>Tangle Teezer Returns as Principal Sponsor</h3>

     <img src="/images/TT-CEO.JPG" align="center" alt="Tangle Teezer Sponsors dot-art Schools" />
    
    <p><small>Tangle Teezer CEO Matt Lumb receiving his certificate of thanks for supporting dot-art Schools 2015-16.</small></p>
    
     <p><b>We are delighted to announce that internationally successful, cult hairbrush brand, Tangle Teezer, has once 
    again signed up as Principal Sponsor of the dot-art Schools programme for 2016-17.</b</p>
    
  <a href="https://www.tangleteezer.com/" target="_blank">
                <img src="/images/logos/TT-540.jpg" class="span6" alt="Tangle Teezer logo" /></a>

    
	</div> 

<div class="span6">
		<h3>2016 Winners Announced!</h3>

    <img src="/images/dot-art-Schools-secondary-winner-web.jpg" alt="dot-art Schools Winner 2016" />
    
    <p><small>Overall secondary winner Nyah Boorman of St Hildas CE High School and her work "Golden Tamarin"</small></p>
    
    <img src="/images/dot-art-Schools-primary-winner-2-web.jpg" alt="dot-art Schools Winner 2016" />
    
    <p><small>Overall primary winner Aiden Owen of St Bedes Catholic Junior School and his work "Boston Terrier"</small></p>
    
    
    <p><b>More details and full list of winners can be found on the 
    <a href="http://schools.dot-art.com/exhibition/year2016">Exhibition Page.</a></b</p>
    
	</div>  
  </div>
 
 <!---ROW 12 -->
        
<div class="row">    

<div class="span6">
<h3>2015 Winners Announced!</h3>

    <img src="/images/news/dot-art-Schools-Overall-Winner-2015-2-web" title="2015 Winners Announced"
		alt="2015 Winners Announced">
    
    <p><small>Overall winner Georgia Allen of Rainhill High and her teacher Anthony Bennett, receiving her prize from the Lord Mayor.</small></p>
    
		<img src="/images/news/dot-art-Schools-2015-winning-work-web" title="2015 Winners Announced"
		alt="2015 Winners Announced">
    
    <p><b>More details and full list of winners can be found on the 
    <a href="http://schools.dot-art.com/exhibition/year2015">Exhibition Page.</a></b</p>
    
 </div class="span6">   
    
	<div class="span6">
		
		<h3>Lime Street Exhibition</h3>
		<img src="/images/news/dot-art-Schools-Merseyrail.JPG" title="dot-art Schools at Lime Street Lower Level" 
    alt="dot-art Schools at Lime Street Lower Level"/>
    <p><small>dot-art Schools Exhibition at Lime Stret Lower Level Station</small></p>
		<p><b>Thanks to an exciting new partnership with Merseyrail, the dot-art Schools Exhibition was on public view at 
    Lime Street Lower Level for the whole of July 2015, where it was seen by almost 20000 station users. Look out for 
    more activity in conjunction with Merseyrail in 2015-16 as we continue to develop more ways of highlighting and sharing
    all the wonderful artwork submitted for the programme.</b></p>
		</p> 
	</div>
  
   <h3>Prize Giving and Exhibition 2015 on Bay TV</h3>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/hT_mcq0uIQc" frameborder="0" allowfullscreen></iframe>
       <p><small>Video courtesy of Bay TV Liverpool, Freeview Channel 8 and Virgin 159 in the Liverpool region.</small></p>
  
  
  </div>
  
  	<!---
    
    <div class="span6">
    
    <h3>Principal Sponsor 2015 Announced</h3>
		<img src="/images/news/DMR-logo-web.jpg" title="David M Robinson Principal Sponsor" alt="David M Robinson Principal Sponsor"/>
		<p><b>dot-art Schools are delighted to announce David M Robinson as their principal sponsor for the third
annual inter-school art competition. David M Robinson commented: <i>As a boy, other than playing football for the school, there was only one other
place I wanted to spend my time – in the art room... great memories of my art teacher, John Hughes. This
passion for art has followed me through life and supporting the arts in the North West has become an
integral part of our business. It is my absolute pleasure to be helping dot-art Schools inspire the imaginations
of the school children of Merseyside.</i></p>
		<p><a href="http://www.davidmrobinson.co.uk/">Find out more about David M Robinson.</b></a></p> 
	</div>
      
      
			
	--->
	
				
		 	
      
      
  <!---ROW 13 -->      
		<div class="row">
	
  <div class="span6">
		<h3>Partnership with St Georges Hall Announced</h3>
		<img src="/images/news/web-news-sgh.jpg" title="St Georges Hall and dot-art Schools" alt="St Georges Hall and dot-art Schools"/>
		<p><b>We are delighted to announce that the dot-art Schools Exhibition 2015 will take place at the iconic St Georges Hall, 
    from 5th - 20th June.</p>
		<p>Read the <a href="http://schools.dot-art.com/docs/dot-art-schools-press-release-21-11-14.pdf">
    full press release here.</b></a></p> 
	</div>
	
	<div class="span6">
		<h3>2014 Winners Announced!</h3>

		<img src="/images/news/2014-winners-web.jpg" title="2014 Winners Announced"
		alt="2014 Winners Announced">
		<p><small>Prizegiving with Lord Mayor Cllr Gary Millar</small></p>

	
    
    <p><b>More details and full list of winners can be found on the 
    <a href="http://schools.dot-art.com/exhibition/year2014">Exhibition Page.</a></b</p>
    
	</div>
	
	
	
	</div>

	
   <!---ROW 14 -->  
<div class="row">

<div class="span6">
		<h3>Overall Judge Announced: Award winning artist, Tabitha Moses.</h3>

		<img src="/images/news/tabitha-moses.jpg" title="Overall judge: Tabitha Moses"
		alt="Overall judge: Tabitha Moses">
		<p><small>Photo courtesy of McCoy Wynne</small></p>

		<p>Tabitha Moses is an artist whose practice is rooted in the meanings and 
		possibilities of materials. Fabric and stitch are central to her practice - through 
		the language of textiles Tabitha uncovers rich connections and latent emotions. 
		She is interested in the transformation of discarded or overlooked subjects and 
		matter into objects that speak with eloquence of the human experience.</p>

		<p>Tabitha was winner of the Liverpool Art Prize 2013. She is currently
		developing the theme for a solo exhibition at Walker Art Gallery later this year.</p>

		<p>Tabitha has exhibited nationally and internationally and is a visiting lecturer at 
		Manchester Metropolitan University.</p>

		<p><strong>Tabitha has selected the overall winners and runners up from both Primary
		and Secondary Schools.</strong></p>
	</div>  

	<div class="span6">
		<h3>Welcome New Sponsors: Cassell Moore</h3>

		<a href="http://schools.dot-art.com/exhibition/"><img src="/images/news/cassell-moore.jpg"
		title="dot-art Schools New Sponsors" alt="dot-art Schools New Sponsors"/></a>

		<p><b>Employment law continues to evolve at a rate of knots and at Cassell Moore we 
		recognise the challenges that this presents for our clients in balancing compliance 
		against commercial and other objectives.  We will work in partnership with you 
		providing bespoke practical advice across the full spectrum of employment law.  
		</b></p>

		<p>At Cassell Moore we recognise the challenges that constant developments in employment law present for our clients, 
		particularly in the Education Sector. Our specialist employment team will work with you to provide bespoke 
		practical advice at each stage. We advise across the full range of issues from ad hoc HR queries, internal 
		disciplinary and grievances, resolving disputes, representation at tribunal and advice on more complex 
		strategic projects such as reorganisations, redundancy, TUPE and corporate transactions.</p>

		<p><b>Contact: Liz Cotton, Partner – Head of Employment (pictured) 
		lizcotton@cassellmoore.com / www.cassellmoore.com<b></p>
	</div>
 
 
	

</div>


   <!---ROW 15 -->  
<div class="row">  

<div class="span6">
		<h3>Partnership with Walker Art Gallery Announced</h3>
		<a href="http://blog.liverpoolmuseums.org.uk/2013/11/calling-all-art-teachers/"><img src="/images/Walker-med.jpg"
		title="Walker Art Gallery and dot-art Schools" alt="Walker Art Gallery and dot-art Schools"/></a>
		<p>We are delighted to announce that the dot-art Schools Exhibition 2014 will take place at the prestigious Walker Art Gallery, from 17th May - 8th June.</p>
		<p><a href="http://blog.liverpoolmuseums.org.uk/2013/11/calling-all-art-teachers/">Read the Walker blog article here</a> and
		<a href="http://www.liverpoolmuseums.org.uk/about/mediacentre/2013/school-work-on-display-at-the-walker.aspx"> full press release here.</a></p> 
	</div> 
  
		
	<div class="span6">
		<h3>2013 Winners Announced!</h3>
		<a href="http://schools.dot-art.com/exhibition/"><img src="/images/news/winners.jpg"
		title="dot-art Schools 2013 Winners Announced" alt="dot-art Schools 2013 Winners Announced"/></a>
	</div>
	
</div>

</div>

<!--
	<div class="span6">
		<h3>Video: Beth Explains dot-art Schools</h3>
		<iframe width="550" height="396" src="http://www.baytvliverpool.com/vod/iframe/?vid=JBV527cd70c99492" frameborder="0" scrolling="no" style="overflow:hidden;"></iframe>
	</div> 
--->