<?php
   $this->headTitle('Press');
   $this->headMeta()->appendName('description', 'Press releases about dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">News</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">News <span class="divider">/</span></li>
  <li class="active">Press</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>

<!-- Put SPAN6 DIVs here for each news item:  -->

<div class="row">
	<div class="span6">
	<h3>Press Releases</h3>
	<p>Click the links below to download information about the dot-art Schools programme.</p>
	<ul>
   <li><a href="/docs/dot-art-Schools-Liverpool-Press-Release-13-11-17.pdf" target="_blank">Press release, 13th November 2017.</a></li>
   <li><a href="/docs/dot-art-Schools-Press-Release-16-06-17.pdf" target="_blank">Press release, 16th June 2017.</a></li>
  <li><a href="/docs/dot-art-Schools-Press-Release-01-06-17.pdf" target="_blank">Press release, 1st June 2017 - Creative Careers Event.</a></li>
  <li><a href="/docs/dot-art-Schools-Press-Release-Liverpool-30-03-17.pdf" target="_blank">Press release, 30th March 2017.</a></li>
      <li><a href="/docs/dot-art-Schools-Press-Release-09-12-16.pdf" target="_blank">Press release, 9th December 2016.</a></li>
     <li><a href="/docs/dot-art-Schools-Press-Release-07-10-16.pdf" target="_blank">Press release, 7th October 2016.</a></li>
    <li><a href="/docs/dot-art-Schools-Press-Release-27-05-16.pdf" target="_blank">Press release, 27th May 2016.</a></li>
 <li><a href="/docs/dot-art-Schools-Press-Release-29-03-16.pdf" target="_blank">Press release, 29th March 2016.</a></li>                                                                                                                               
   <li><a href="/docs/dot-art-Schools-Press-Release-11-01-16.pdf" target="_blank">Press release, 11th January   2016.</a></li>
  <li><a href="/docs/dot-art-Schools-Press-Release-09-10-15.pdf" target="_blank">Press release, 9th October   2015.</a></li>
    <li><a href="/docs/dot-art-schools-press-release-11-06-15.pdf" target="_blank">Press release, 11th June 2015.</a></li>
	 	  <li><a href="/docs/dot-art-schools-press-release-20-05-15.pdf" target="_blank">Press release, 20th May 2015.</a></li>
      <li><a href="/docs/dot-art-schools-press-release-02-04-15.pdf" target="_blank">Press release, 2nd April 2015.</a></li>
     <li><a href="/docs/dot-art-schools-press-release-21-11-14.pdf" target="_blank">Press release, 21st November 2014.</a></li>
	  <li><a href="/docs/dot-art-schools-press-release-14-11-14.pdf" target="_blank">Press release, 4th November 2014.</a></li>
		<li><a href="/docs/dot-art-schools-press-release-23-05-14.pdf" target="_blank">Press release, 23rd May 2014.</a></li>
		<li><a href="/docs/dot-art-schools-press-release-06-05-14.pdf" target="_blank">Press release, 6th May 2014.</a></li>
		<li><a href="/docs/dot-art-schools-press-release-10-04-14.pdf" target="_blank">Press release, 10th April 2014.</a></li>
		<li><a href="/docs/dot-art-schools-press-release-04-11-13.pdf" target="_blank">Press release, 4th November 2013.</a></li>
	</ul>
	</div>
</div>

</div>
