<?php
   $this->headTitle('Exhibition 2017');
   $this->headMeta()->appendName('description', 'Details of the annual exhibition which is the culmination of dot-art Schools, an interactive, inter school, online art competition.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Exhibition</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Exhibition <span class="divider">/</span></li>
  <li class="active">2013</li>
</ul>

<div class="row">

<div class="span12">
<h3>dot-art Schools Exhibition 2013</h3>
<p>11th-20th July, Domino Gallery, Liverpool</p>
<p>Following the results of an online public vote, this exhibition showcased the top three works from each of the schools 
who participated in the inaugural year of the programme. The winners of the 2013 dot-art Schools Competition were announced 
at a prize-giving ceremony at the Domino Gallery in Liverpool on 10th July 2013, where as well as the overall winners, 
the top three students from each of the participating schools were all presented with a certificate by the Lord Mayor, 
Councillor Gary Millar.</p> 
</div>

</div>


</div>
