<?
   $this->headTitle('News');
   $this->headMeta()->appendName('description', 'Details of the selection panel for dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Panel</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Panel</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>



<div class="row">
<div class="span4">

<h3>Sarah Pickstone</h3>

<a><img src="/images/Sarah-Pickstone.jpg" title="Sarah Pickstone, dot-art Schools Selection Panel" 
alt="Sarah Pickstone, dot-art Schools Selection Panel"/></a>

<p>Sarah Pickstone is an artist, originally from Manchester she now lives and works in London. 
Sarah''s recent work is based on writers who had a connection to Regents Park in London. 
One of these paintings called "Stevie Smith and The Willow" won the John Moores Painting 
prize 2012 and Sarah spent time in Liverpool as the painting was hanging in the Walker Art Gallery. 
In April 2014 Sarah will travel to Shanghai in China to accompany the John Moores China painting exhibition.
In May a book called Park Notes – comprising Sarah Pickstone’s paintings and writing by 
contemporary authors will be published by Daunt Books.</p>
</div>


<div class="span4">

<h3>Sandra Penketh</h3>

<a><img src="/images/Sandra-Penketh.jpg" title="Sandra Penketh, dot-art Schools Selection Panel" 
alt="Sandra Penketh, dot-art Schools Selection Panel"/></a>

<p>Sandra Penketh has responsibility for National Museum Liverpool's fine and decorative art 
collections and venue management responsibility for the Walker Art Gallery, Lady Lever Art Gallery, 
Sudley House and the Oratory. Sandra studied History of Art at the Sainsbury Centre, University 
of East Anglia and then obtained a Masters Degree in Medieval Studies from the University of Liverpool. 
In 1989 she joined the staff of National Museums Liverpool as an assistant curator at the Walker 
Art Gallery before moving on to work in the Art Galleries Education department. 
From 1998 until 2002, Sandra worked on the development of new display galleries at World Museum, 
part of the £45 million capital project Into the Future. Sandra also taught History of Art 
regularly for the University of Liverpool Centre for Continuing Education from 1991 until 2002. 
Between 2003 and 2012 she was Head of the Lady Lever Art Gallery. Sandra specialises in 
Medieval and Victorian Art and has published on Medieval Books of Hours, British nineteenth-century 
sculpture and painting, and the Fine Art collections of the Walker Art Gallery and Lady 
Lever Art Gallery. She has curated a wide range of exhibitionsÂ on Victorian art.</p>
</div>


<div class="span4">

<h3>Jenny Porter</h3>

<a><img src="/images/jenny-porter.jpg" title="Jenny Porter, dot-art Schools Selection Panel" 
alt="Jenny Porter, dot-art Schools Selection Panel"/></a>

<p>Jenny Porter is Project Manager at Metal Liverpool. Based in the historic buildings at 
Edge Hill Station, Jennyhelps to run Metal's wide variety of projects that support artists 
from different creative disciplines. Much of Metal's work involves encouraging participation 
in the arts through residencies, exhibitions, events, performances and discussions. 
Jenny has curated the annual Liverpool Art Prize exhibition for the past five years, 
working closely with a wide range of contemporary visual artists based in Merseyside 
to exhibit their work in competition for the coveted award. In 2012 she worked with 
studio groups and independent arts organisations to establish Liverpool Art Month, 
a celebration of local creativity that coincides with the Liverpool Art Prize exhibition. 
Jenny has also developed the Edge Hill Station archive, a Heritage Lottery funded project 
that brings together images, materials and a range of interviews with local people about 
the history of Edge Hill Station and the surrounding area. She is passionate about 
disseminating the fascinating story of Edge Hill and engaging diverse audiences, 
particularly people who may not see the arts as something for them. Jenny also continues 
her own practice in her spare time. An avid cinema-goer, much of her artistic practice 
uses the beauty and violence found in the poetry of films to create new images that 
explore memory, gender and nostalgia. Her work sometimes incorporates moving image, 
along with drawing, painting and collage.</p>
</div>

</div>

</div>
