<?
   $this->headTitle('News');
   $this->headMeta()->appendName('description', 'Details of the selection panel for dot-art Schools, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Panel</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Panel</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>




<div class="page-header"> 
   <h1><small>Shortlisting Panel</small></h1>
             </div> 
            

<div class="row">
<div class="span4">


<h3>Deborah Riding</h3>

<a><img src="/images/tate.jpg" title="Deborah Riding, dot-art Schools Selection Panel" 
alt="Deborah Riding, dot-art Schools Selection Panel"/></a>

<p>Deborah Riding has been working in gallery learning for 19 years. She is currently Programme Manager 
for Children and Young People at Tate Liverpool leading a team that delivers early years, family, schools 
and peer led youth programmes. She is a co-editor for the International journal of Art and Design Education 
and a trustee for Learning disability arts organisation, Venture arts. 
</div>


<div class="span4">

<h3>Sandra Penketh</h3>

<a><img src="/images/Sandra-Penketh.jpg" title="Sandra Penketh, dot-art Schools Selection Panel" 
alt="Sandra Penketh, dot-art Schools Selection Panel"/></a>

<p>Sandra Penketh has responsibility for National Museum Liverpool's fine and decorative art 
collections and venue management responsibility for the Walker Art Gallery, Lady Lever Art Gallery, 
Sudley House and the Oratory. Sandra studied History of Art at the Sainsbury Centre, University 
of East Anglia and then obtained a Masters Degree in Medieval Studies from the University of Liverpool. 
In 1989 she joined the staff of National Museums Liverpool as an assistant curator at the Walker 
Art Gallery before moving on to work in the Art Galleries Education department. 
From 1998 until 2002, Sandra worked on the development of new display galleries at World Museum, 
part of the £45 million capital project Into the Future. Sandra also taught History of Art 
regularly for the University of Liverpool Centre for Continuing Education from 1991 until 2002. 
Between 2003 and 2012 she was Head of the Lady Lever Art Gallery. Sandra specialises in 
Medieval and Victorian Art and has published on Medieval Books of Hours, British nineteenth-century 
sculpture and painting, and the Fine Art collections of the Walker Art Gallery and Lady 
Lever Art Gallery. She has curated a wide range of exhibitionsÂ on Victorian art.</p>
</div>


<div class="span4">

<h3>Jenny Porter</h3>

<a><img src="/images/jenny-porter.jpg" title="Jenny Porter, dot-art Schools Selection Panel" 
alt="Jenny Porter, dot-art Schools Selection Panel"/></a>

<p>Jenny Porter is Senior Project Manager at Metal Liverpool. She has curated the Liverpool Art Prize 
for the past five years, and is also an artist in her spare time. Working closely with Metal's artists in 
residence, and nurturing talent in the local arts scene, she is passionate about encouraging younger artists 
to develop their skills and express their ideas. For her, the dot-art schools competition is a great way to 
see what rising stars we have in our local schools.</p>
</div>

</div>

<div class="page-header"> 
   <h1><small>Overall Judge</small></h1>
             </div> 
            
<div class="row">
<div class="span4">

<h3>Susan M Coles</h3>

<a><img src="/images/susan-m-coles.jpg" title="Susan M Coles, dot-art Schools Guest Judge" 
alt="Susan M Coles, dot-art Schools Guest Judge"/></a>
  
<p>Susan was president of NSEAD 2013-14, and is secretariat to the All Party Parliamentary Group on Art, 
Craft and Design Education. She says: “I am totally absorbed in the world of art craft and design education, 
as artist, teacher, adviser, and critical friend and as part of NSEAD. Nationally (and beyond) 
I am a campaigner and advocate for the subject. I strongly believe that every child has an entitlement 
to a high quality visual art education and will do all that I can to remind people of that. 
I agreed to be a judge for this because it is a chance to showcase and to celebrate all the 
wonderful work being done in schools by teachers and young people. I can't wait to see the art work.”
</p>               
</div>
</div>


</div>
