<?php
   $this->headTitle('Artsmark');
   $this->headMeta()->appendName('description', 'dot-art Schools is an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<script type="text/javascript">twttr.conversion.trackPid('nu3ux', { tw_sale_amount: 0, tw_order_quantity: 0 });</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
</noscript>


<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">What?</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
   <li class="active">What? <span class="divider">/</span></li>
  <li class="active">Artsmark</li>
</ul>

<div class="row">
<div class="span12">
         
      
              
            <h2>Artsmark</h2>
            
            <p>dot-art Schools is proud to be an Artsmark Partner supporting schools on their Artsmark journey and responding 
            to the Cultural Education Challenge. Artsmark is awarded by the Arts Council England and has been designed by schools, 
            for schools, to align with School Improvement Plans and support core EBACC and STEM priorities, giving the curriculum 
            breadth and balance. As well as recognising schools that are making the arts come alive, the Artsmark award is a 
            practical and valuable tool for enriching a school's arts provision whatever the starting point.</p> 
            
            <p>Why not join the growing network of schools championing arts and culture today. 
            Find out more here <a href="https://www.artsmark.org.uk">artsmark.org.uk</a></p>

            <p>Artsmark supports Arts Award which recognises the creative development of individual young people. 
            Find our more here: <a href="https://www.artsaward.org.uk">artsaward.org.uk</a></p>
            
            <p>Below are ways we can support the Arts Award at each level:</p>
            
            
            
          <ul>
          <li><p><b>Arts Award Discover & Explore:</b></p>
          <p>Visit the dot-art Schools exhibitions, which happen in June each year. Check our website or email schools@dot-art.com for details.</p>
          <p>Book an artist led workshop. dot-art Schools works with a wide range of visual artists to offer your school 
          artist-led workshops, from one day to an entire project or arts week, in a variety of different techniques, media 
          and subjects. All our workshops are delivered by experienced artists with full DBS clearance and public liability 
          insurance, and can be tailored to meet your specific requirements. INSET also available. 
          See the<a href="../workshops"> Workshops page</a> for more details.</p>
          </li>
          <li><p><b>Bronze Arts Award:</b></p>
          <p>Showcase your Year 9 (also Year 5) students artwork by competing in dot-art Schools annual, online art competition 
          which culminates in a public exhibition and prize giving ceremony. Following a judges shortlist and a public vote, 
          the public exhibition showcases the winning artists work from each school who participated in the competition. 
          The overall winner of the year 9 entries receives a scholarship to dot-art, giving them a year's membership to 
          dot-art's network, allowing them to show and sell their work alongside professional artists. Other prizes include 
          exhibition tickets and art material vouchers. Open to primary, secondary and special schools in Liverpool City Region, 
          Cheshire and Warrington.</p>
          </li>
          <li><p><b>Silver Arts Award:</b></p>
           <p>Students can review the dot-art Schools annual exhibition and publish it on Arts Award Voice.</p>
          </li>
          <li><p><b>Gold Arts Award:</b></p>
           <p>Students can gain exhibition experience by volunteering for dot-art Schools annual exhibition.</p>
          </li>
          </ul>
              
         <div class="row row-entry">

            <div class="span12">
            <img src="/images/artsmark-partner.jpg" title="Artsmark Partner Logo" alt="Artsmark Partner Logo"/>
            </div>   

    
</div>
</div>
</div>

</div>


