<?php
   $this->headTitle('What?');
   $this->headMeta()->appendName('description', 'dot-art Schools is an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<script type="text/javascript">twttr.conversion.trackPid('nu3ux', { tw_sale_amount: 0, tw_order_quantity: 0 });</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
</noscript>


<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">What?</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">What?</li>
</ul>

<div class="row">
<div class="span12">

<div class="tabbable" id="stages">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-program" data-toggle="tab">
            The Programme
        </a></li>
        <li><a href="#tab-teachers" data-toggle="tab">
            Information for Teachers
        </a></li>
        <li><a href="#tab-background" data-toggle="tab">
            Background
        </a></li>
        
        <!--
        <li><a href="#tab-supporters" data-toggle="tab">
            Supporters
        </a></li>
        -->
      
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab-program">
        
           <!---
            <p><a href="/docs/dot-art-Schools-Overview-2014-15.pdf" target="_blank">Download a PDF overview of dot-art Schools</a></p>
              <p><a href="/docs/dot-art-Schools-Sign-Up-Form-2014-15.pdf" target="_blank">Download a PDF of the dot-art Schools Sign Up Form for 2014-15</a></p>
              <p><a href="/docs/dot-art-Schools-Sign-Up-Form-2014-15.doc" target="_blank">Download a Word document of the dot-art Schools Sign Up Form for 2014-15</a></p>
            -->

            
            <div class="row row-entry">

            <div class="span4">
            <img src="/images/dot-art-Schools-2015-182.jpg" title="dot-art Schools Exhibition" alt="dot-art Schools Exhibition"/>
            </div>
            
            <div class="span4">
            <img src="/images/dot-art-Schools-2015-56.jpg" title="dot-art Schools Exhibition" alt="dot-art Schools Exhibition"/>
            </div>
            
            <div class="span4">
            <img src="/images/dot-art-Schools-2015-70.jpg" title="dot-art Schools Exhibition" alt="dot-art Schools Exhibition"/>
            </div>
            </div>
            
            <h2>Sign Up</h2>
            
            <p><a href="http://cheshire.schools.dot-art.com/docs/dot-art-Schools-2017-18-Sign-Up-Form.pdf">Download the 2017-18 Entry Form.</a></p>
            
            <p><a href="http://cheshire.schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet.pdf">Download the Teachers Information Leaflet</a></p>

   
            
     <!--        
            <p>**The deadline for entering dot-art Schools 2016-17 has now passed. If you are interested in taking part next academic year, please sign up to
            our <a href="http://schools.dot-art.com/contact">SCHOOLS MAILING LIST</a>**</p>

     -->        
            
            <h2>The Programme</h2>
    
            <p>dot-art Schools Cheshire is an <strong>interactive, online, inter-school, art competition</strong>, taking part on an annual basis and
            culminating in an exhibition in a central location. Open to primary <strong>(year 5)</strong> and secondary 
            <strong>(year 9)</strong> schools in <strong>Cheshire West & Chester, Cheshire East and Warrington</strong>, 
            it is designed to nurture talent, raise ambition, and take art out of the classroom and into the
            real world. With the current threats to creative subjects on the national curriculum, dot-art Schools offers a
            way of keeping young people engaged with the arts, allows them to see a creative career path, and
            encourages them to attend exhibitions and engage with culture, outside of school.</p>
            
            </p>dot-art Schools was orginally launched in the <a href="http://liverpool.schools.dot-art.com">Liverpool City Region
            </a> in 2012, where is continues to operate on an annual
            basis. In September 2016, thanks to a new partnership with Liverpool John Moores University, a parallel second 
            programme was launched for the Cheshire region which we hope will be as successful as the first!</p>
            
            <h2>How It Works</h2>
            
            <p>During the <strong>Autumn and Spring terms</strong>, each school creates and selects <strong>25 pieces</strong> 
            of student work which
            they feel best represent the talents of their students. These art works are submitted to their dot-art Schools
            page by <strong>February Half Term</strong>, then put on display to the world via the dot-art Schools website
            (schools.dot-art.com).</p>
            
            <p>A panel of art experts will select the top 3 artworks from each school. Students from all the schools in the
            programme, as well as the general public, will then be able to <strong>vote</strong> for their favourite piece of art from the
            judge's shortlist. During the Summer term, an <strong>exhibition</strong> will be held at a <strong>gallery</strong> 
            showcasing the artwork with the most votes from each participating school. The overall winner and two runners up in both age 
            categories are chosen and announced at the prize giving ceremony.</p>

           <h2>Prizes</h2>
            
            <h3>Secondary</h3>
            
            <p><strong>Overall winner</strong></p> 
            <ul>
            <li>Scholarship to <b>dot-art</b>, giving them a year's membership
            to dot-art's network, allowing them to showcase and sell their work alongside professional artists. 
            (See: <a href="http://dot-art.co.uk/artist/">dot-art.co.uk/artist/</a>)</li>
            <li>Tickets to see the latest exhibition at <b>Tate Liverpool</b>.</li> 
            <li>A pair of tickets for The Tempest at <b>Storyhouse</b>.</li>
            <li>Art materials goody bag</li>
            </ul>
            
            <p><strong>Runners Up x 2</strong></p> 
            <ul>
            <li>Tickets to see the latest exhibtion at <b>Tate Liverpool</b></li> 
             <li>A pair of tickets for The Tempest at <b>Storyhouse</b>.</li>
             <li>Art materials goody bag</li>
            </ul>
            
            <h3>Primary</h3>
            
            <p><strong>Overall winner</strong></p> 
            <ul>
             <li>Afternoon tea for two at the <b>Townhouse Hotel</b>, Chester</li>
             <li>A pair of tickets for Swallows and Amazons at <b>Storyhouse</b>.</li> 
              <li>Art materials goody bag</li>
            </ul>
            
            <p><strong>Runners Up x 2</strong></p> 
            <ul>
            <li>A pair of tickets for Swallows and Amazons at <b>Storyhouse</b>.</li> 
              <li>Art materials goody bag</li>
            </ul>
            
            <p>All shortlisted artists (3 from each partipating school) will be awarded <strong>certificates.</strong></p>
            <p>.</p>
            
             
            <p>This annual programme will encourage healthy competition between students and schools, as well
            as driving traffic to the site and therefore increasing the audience for the students' work and
            the profile of the school. The final exhibition will provide a wonderful opportunity for
            the successful students to show their work in a public setting and a fantastic way of celebrating 
            the art work created and the school's commitment to arts education, demonstrating the quality of art produced to parents, 
            families, local authorities and the wider community. Finally the programme can help
            participating schools meet many of the KS2 and 3 <strong>National Curriculum</strong> requirements for Art and
            Design, the criteria outlined in the <strong>OFSTED</strong> evaluation framework, as well as providing a
            valuable tool for schools working towards <strong>Artsmark</strong> status.</p>
            <p>.</p>
            
            <blockquote>
                <p>Pupils benefited greatly from the feedback received when their work was shared locally or more widely...</p>
                <p>Schools should... build sustained partnerships with art galleries and creative practitioners.</p>
                <p>Pupils who met with inspectors reported consistently the motivational impact of seeing their own work displayed professionally and publicly...</p>
                <p>The public exhibition of students' work was highly effective in strengthening links between schools and the local community, including diverse community groups, different generations and those living in contrasting socio-economic circumstances.</p>
                <small>Extracts from: Ofsted Report - Making a mark: art, craft and design education, 2008/11</small>
            </blockquote>
        </div>
        
        <div class="tab-pane fade in" id="tab-teachers">
      
      

<!--        

<p>**The deadline for entering dot-art Schools 2016-17 has now passed. If you are interested in taking part next 
         academic year, please download the leaflet below for more information and sign up to
            our <a href="http://schools.dot-art.com/contact">SCHOOLS MAILING LIST</a>**</p>
            
        <p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet.pdf">Download the Teachers Information Leaflet</a></p>
            <p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Entry-Form.pdf">Download the 2015-16 Entry Form.</a></p>
    -->
            
            <h2>Information for Teachers</h2>
            
            <p><a href="http://cheshire.schools.dot-art.com/docs/dot-art-Schools-2017-18-Sign-Up-Form.pdf">Download the 2017-18 Entry Form.</a></p>
            
            <p><a href="http://cheshire.schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet.pdf">Download the Teachers Information Leaflet</a></p>

           <p>dot-art Schools was first launched in the <a href="http://liverpool.schools.dot-art.com">Liverpool City Region</a> 
           in 2012 and since then over 4000 children have taken 
           part from almost 200 schools. We have held exhibitions at the Domino Gallery, the Walker Art Gallery and St George 
           Hall and each year, three children from each participating school have been presented with a certificate by the 
           Lord Mayor of Liverpool, as well as a range of prizes awarded. In response to feedback from schools, in September 2016 we 
            changed the primary age group from Year 6 to Year 5.</p>
            
            
             <p>In September 2016, thanks to our new partnership with LJMU, dot-art Schools also launched in 
             <a href="http://cheshire.schools.dot-art.com">Cheshire.</a>
             A small group of Primary and secondary schools in Cheshire West & Chester, Cheshire East and Warrington took 
             part in the pilot year of our second region in 2016-17 and from September 2017 we will be inviting all 
             schools in the region to take part in the 2017-18 programme.</b></p>
              
      <p>We are pleased to announce that from February 2018, dot-art Schools is an 
              <a href="http://www.artsmark.org.uk/artsmark-partnership-programme">Artsmark Partner</a>.
              Artsmark is the creative quality standard for schools and education
              settings, awarded by Arts Council England, recognising their
              commitment to high quality arts and cultural education.
              dot-art Schools is proud to be supporting schools and
              education settings on their Artsmark journey, inspiring children and
                young people to create, experience, and participate in great arts and
              culture.</p>  
              
              <p>Find out more about Artsmark at <a href="http://www.artsmark.org.uk.">artsmark.org.uk</a>
              To find out how we can support your
                Artsmark journey, contact Carolyn on 0345 0176660.
              </p>  
              
                 <a href="http://www.artsmark.org.uk"><img src="/images/artsmark-partner-400.jpg" title="dot-art Schools Artsmark Partner" alt="dot-art Schools Artsmark Partner"/></a>
           

            <p>Please download the document below for more details about how the programme works and the benefits it can
            bring:</p>
            <ul>
                <li><a href="http://schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet.pdf" target="_blank">dot-art Schools Teachers Leaflet</a></li>
            </ul>
             
            <!---
            <li><a href="/docs/dot-art-Schools-KS2.pdf" target="_blank">dot-art Schools and the National Curriculum (year 6)</a></li>
                 <li><a href="/docs/dot-art-Schools-KS3.pdf" target="_blank">dot-art Schools and the National Curriculum (year 9)</a></li>
                <li><a href="/docs/dot-art-Schools-Ofsted.pdf" target="_blank">dot-art Schools and OFSTED</a></li>
                 <li><a href="/docs/dot-art-Schools-Arts-Award-Artsmark.pdf" target="_blank">dot-art Schools and Arts Award / Artsmark (overview)</a></li>
                <li><a href="/docs/dot-art-Schools-Artsmark-Detail.pdf" target="_blank">dot-art Schools and Artsmark (detail)</a></li>

                 <p>If you would like to take part, please complete and return the following Entry Form:</p>
            <ul>
                <li><a href="http://schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet.pdf" target="_blank">dot-art Schools Entry Form 2015-16</a></li>
            </ul>
           
                      -->
                      
                      
            <p><strong>Key Facts 2016-17 (pilot year):</strong></p>
            <ul>
                <li>19 schools participated.</li>
                <li>360 student art works displayed online.</li>
                <li>1500 votes cast.</li>
                <li>7000 unique visitors to the website.</li>
                 <li>19 student art works were showcased to the public at Mid Cheshire College</li>
                  <li>57 students celebrated at prize giving ceremony in the Art Gallery at Mid Cheshire College.</li>
                  <li>300 visitors to the exhibition at Mid Cheshire College</li>
                  
            </ul
           
        
      
            
             <p><strong>Feedback from schools:</strong></p>
            <ul>
                <li>“What a fantastic event and such great art work. Brilliant to be here this evening with pupils and parents, 
                looking at the work on display. Very proud teacher!”</li>
                <li>“I wanted to express my gratitude for opportunities like dot-art Schools to celebrate the 
                “small and every day wins” that usually go unnoticed at school – especially at a time where the 
                family are going through some issues.”</li>
                <li>“It has been a long time since we have had something of this calibre to promote and
                celebrate the work of our young artists”</li>
            </ul>
            
             <p><strong>Feedback from exhibition visitors:</strong></p>
            <ul>
                <li>“Carry on with all your wonderful work. dot-art is an inspirational organisation and needed now more than ever."</li>
                <li>"Just amazed at the young talent. Some of the work is so good I thought it was done by adults.”</li>
                <li>"Really high standard. I’m amazed by the Owl – beautiful"</li>
            </ul>
            
             <p><strong>Key Dates 2017-18:</strong></p>
            <ul>
              <li>September 2017 – School recruitment for 2017-18 programme begins.</li>
                <li>December 2017 – Deadline for schools to sign up.</li>
                <li>February 2018 – Deadline for schools to submit work for competition.</li>
                <li>4 - 28th April 2018 – Online voting period.</li>
                <li>7th June 2018 – Prize Giving Ceremony.</li>
                 <li>8th - 24th June 2018 – Exhibition of winning works.</li>
            </ul>
            
        </div>
        
        <div class="tab-pane fade in" id="tab-background">
            <h2>Background</h2>
            <p>The dot-art Schools programme has been developed by dot-art, a Liverpool based arts organisation which has
            been supporting artists and developing innovative and creative visual arts projects and initiatives since 2005.</p>

            <p>We are now using our skills, experience and expertise to give the young people of the region access to an
            exciting new public platform for their creative output, and a taste of the way the art world works.</p>

            <p>dot-art is made up of two arms:</p>

            <p><strong>dot-art Ltd</strong> was founded in Liverpool in 2005 and specialises in affordable, high quality, 
            locally sourced art. We work with over 100 artists to provide an unrivalled choice of original art and limited 
            edition prints for home or business, as well as offering a range of complementary services including; commissions, 
            art rental, art consultancy, exhibition planning and implementation, bespoke framing, art valuation and restoration 
            and artist sourcing. See: <a href="http://www.dot-art.com">dot-art.com</a></p>
            
            <p>All our work supports our not-for profit arm <strong>dot-art Services CIC</strong>, which exists to support 
            North-West based visual artists, both emerging and established, through a range of services and opportunities 
            designed to help them develop their careers and gain exposure and promotion for their work, as well as delivering 
            a programme of adult art classes at a range of venues across Liverpool 
            (see: <a href="http://www.dot-art.co.uk/art-classes.php">dot-art.co.uk/art-classes</a>); 
            and dot-art Schools, our innovative inter school art competition, launched in 2012. 
            See: <a href="http://services.dot-art.com">services.dot-art.com</a>.</p>
            
           <!-- <p><i>This project was initially supported using public funding by the National Lottery through Arts Council England.</i></p>
            <img src="/images/ace-med-white.jpg">
           
            
        </div>
        
          <div class="tab-pane fade in" id="tab-supporters">   
          
           <div class="page-header">
            <h1><small>Project Partner</small></h1>
            </div>
           
           <div class="row">
            
            <a href="https://www.ljmu.ac.uk/" target="_blank">
                <img src="/images/logos/LJMU-web.jpg" class="span6" alt="Liverpool John Moores University" />
            </a>
             </div>
           <!--
            
            <div class="page-header">
            <h1><small>Principal Sponsor 2015-16</small></h1>
            </div>
           
            <div class="row">
            
            <a href="https://www.tangleteezer.com/" target="_blank">
                <img src="/images/logos/TT-540.jpg" class="span6" alt="Tangle Teezer logo" />
            </a>
             </div>
             
             
             
            <div class="page-header"> 
            <h1><small>Supporters</small></h1>
             </div> 
              
             <!-- 
            <div class="row">
            
            <a href="http://liverpoolcityhalls.co.uk/st-georges-hall" target="_blank">
                <img src="/images/logos/SGH-270.jpg" class="span3" alt="St Georges Hall logo" />
            </a>
            <a href="http://www.rathbones.com/" target="_blank">
                <img src="/images/logos/rathbones-270.jpg" class="span3" alt="Rathbones logo" />
            </a>
           
           <a href="http://www.cassart.co.uk" target="_blank">
                <img src="/images/logos/cass-art-270.jpg" class="span3" alt="Cass Art logo" />
               </a>   
               
                <a href="http://www.merseyrail.org/" target="_blank">
                <img src="/images/logos/merseyrail-270.JPG" class="span3" alt="Merseyrail logo" />
            </a>
            
             </div>
                
        <div class="row">
                   <a href="http://www.bigpartnership.co.uk" target="_blank">
                <img src="/images/logos/big-270.jpg" class="span3" alt="The Big Partnership logo" />
               </a>   
                  
                  <a href="http://www.renniesartsandcrafts.co.uk/" target="_blank">
                <img src="/images/logos/Rennies-270.jpg" class="span3" alt="Rennies logo" />
               </a>  
               
                <a href="http://www.albertdock.com/" target="_blank">
                <img src="/images/logos/Albert-Dock-Logo-270.jpg" class="span3" alt="Albert Dock logo" />
               </a>  
           
                  </div>
                
                <p>.</p>  
                  
             <div class="page-header">
            <h1><small>Past Supporters</small></h1>
            </div>

            <div class="row">
            
            <a href="http://www.davidmrobinson.co.uk/" target="_blank">
                <img src="/images/logos/DMR-logo.jpg" class="span3" alt="David M Robinson logo" />
            </a>
            
            <a href="http://www.liverpoolmuseums.org.uk/walker/" target="_blank">
                <img src="/images/logos/Walker-270.jpg" class="span3" alt="Walker Art Gallery logo" />
            </a>
            
             <a href="http://www.cassellmoore.com/" target="_blank">
                <img src="/images/logos/Cassell-Moore-web.jpg" class="span3" alt="Cassell Moore logo" />
            </a>
                
                <a href="http://citycentralbid.com/" target="_blank">
                <img src="/images/logos/city-central-bid-270.jpg" class="span3" alt="City Central Bid logo" />
            </a> 
                

            
          </div>
          
           <div class="row">
        
          
          <a href="http://www.cfmerseyside.org.uk/index.php?p=145" target="_blank">
                <img src="/images/logos/L1-Foundation-270.jpg" class="span3" alt="Liverpool One Foundation logo" />
            </a>
            <a href="http://www.cfmerseyside.org.uk/" target="_blank">
                <img src="/images/logos/CFM-270.jpg" class="span3" alt="Community Foundation for Merseyside logo" />
            </a>
            <a href="http://www.artscouncil.org.uk/" target="_blank">
                <img src="/images/logos/ace-270.jpg" class="span3" alt="Arts Council England logo" />
               </a>
            
          </div>
          </div>
          
          
        
             -->   -->
            
        </div>
        
    </div>
    
</div>
</div>
</div>

</div>
