<?php
   $this->headTitle('What?');
   $this->headMeta()->appendName('description', 'dot-art Schools is an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<script type="text/javascript">twttr.conversion.trackPid('nu3ux', { tw_sale_amount: 0, tw_order_quantity: 0 });</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
</noscript>


<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">What?</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">What? <span class="divider">/</span></li>
  <li class="active">Programme</li>
</ul>

<div class="row">
<div class="span12">

        
           <!---
            <p><a href="/docs/dot-art-Schools-Overview-2014-15.pdf" target="_blank">Download a PDF overview of dot-art Schools</a></p>
              <p><a href="/docs/dot-art-Schools-Sign-Up-Form-2014-15.pdf" target="_blank">Download a PDF of the dot-art Schools Sign Up Form for 2014-15</a></p>
              <p><a href="/docs/dot-art-Schools-Sign-Up-Form-2014-15.doc" target="_blank">Download a Word document of the dot-art Schools Sign Up Form for 2014-15</a></p>
            -->

            
            <div class="row row-entry">

             <div class="span4">
            <img src="/images/dot-art-Schools-Cheshire-2018-3.jpg" title="dot-art Schools Exhibition" alt="dot-art Schools Exhibition"/>
            </div>
            
             <div class="span4">
            <img src="/images/dot-art-Schools-Cheshire-2018-1.jpg" title="dot-art Schools Exhibition" alt="dot-art Schools Exhibition"/>
            </div>
            
          
            <div class="span4">
            <img src="/images/dot-art-Schools-Cheshire-2018-2.jpg" title="dot-art Schools Exhibition" alt="dot-art Schools Exhibition"/>
            </div>
            </div>
           
            <h2>Sign Up</h2>
            
            <p><a href="http://cheshire.schools.dot-art.com/docs/NEW-dot-art-Schools-Sign-Up-Form.pdf">Download the Entry Form.</a></p>
            
            <p><a href="http://cheshire.schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet-New.pdf">Download the Teachers Information Leaflet</a></p>

   
            
     <!--        
            <p>**The deadline for entering dot-art Schools 2016-17 has now passed. If you are interested in taking part next academic year, please sign up to
            our <a href="http://schools.dot-art.com/contact">SCHOOLS MAILING LIST</a>**</p>

     -->        
            
            <h2>The Programme</h2>
    
            <p>dot-art Schools Cheshire is an <strong>interactive, online, inter-school, art competition</strong>, taking part on an annual basis and
            culminating in an exhibition in a central location. Open to primary <strong>(year 5)</strong> and secondary 
            <strong>(year 9)</strong> schools in <strong>Cheshire West & Chester, Cheshire East and Warrington</strong>, 
            it is designed to nurture talent, raise ambition, and take art out of the classroom and into the
            real world. With the current threats to creative subjects on the national curriculum, dot-art Schools offers a
            way of keeping young people engaged with the arts, allows them to see a creative career path, and
            encourages them to attend exhibitions and engage with culture, outside of school.</p>
            
            </p>dot-art Schools was orginally launched in the <a href="http://liverpool.schools.dot-art.com">Liverpool City Region
            </a> in 2012, where is continues to operate on an annual
            basis. In September 2016, thanks to a new partnership with Liverpool John Moores University, a parallel second 
            programme was launched for the Cheshire region which we hope will be as successful as the first!</p>
            
            <h2>How It Works</h2>
            
            <p>During the <strong>Autumn and Spring terms</strong>, each school creates and selects <strong>25 pieces</strong> 
            of student work which
            they feel best represent the talents of their students. These art works are submitted to their dot-art Schools
            page by <strong>February Half Term</strong>, then put on display to the world via the dot-art Schools website
            (schools.dot-art.com).</p>
            
            <p>A panel of art experts will select the top 3 artworks from each school. Students from all the schools in the
            programme, as well as the general public, will then be able to <strong>vote</strong> for their favourite piece of art from the
            judge's shortlist. During the Summer term, an <strong>exhibition</strong> will be held at a <strong>gallery</strong> 
            showcasing the artwork with the most votes from each participating school. The overall winner and two runners up in both age 
            categories are chosen and announced at the prize giving ceremony.</p>

           <h2>Prizes</h2>
            
            <h3>Secondary</h3>
            
            <p><strong>Overall winner</strong></p> 
            <ul>
            <li>Scholarship to <b>dot-art</b>, giving them a year's membership
            to dot-art's network, allowing them to showcase and sell their work alongside professional artists. 
            (See: <a href="http://dot-art.co.uk/artist/">dot-art.co.uk/artist/</a>)</li>
            <li>Tickets to see the latest exhibition at <b>Tate Liverpool</b>.</li> 
            <li>A pair of tickets for The Tempest at <b>Storyhouse</b>.</li>
            <li>Art materials goody bag</li>
            </ul>
            
            <p><strong>Runners Up x 2</strong></p> 
            <ul>
            <li>Tickets to see the latest exhibtion at <b>Tate Liverpool</b></li> 
             <li>A pair of tickets for The Tempest at <b>Storyhouse</b>.</li>
             <li>Art materials goody bag</li>
            </ul>
            
            <h3>Primary</h3>
            
            <p><strong>Overall winner</strong></p> 
            <ul>
             <li>Afternoon tea for two at the <b>Townhouse Hotel</b>, Chester</li>
             <li>A pair of tickets for Swallows and Amazons at <b>Storyhouse</b>.</li> 
              <li>Art materials goody bag</li>
            </ul>
            
            <p><strong>Runners Up x 2</strong></p> 
            <ul>
            <li>A pair of tickets for Swallows and Amazons at <b>Storyhouse</b>.</li> 
              <li>Art materials goody bag</li>
            </ul>
            
            <p>All shortlisted artists (3 from each partipating school) will be awarded <strong>certificates.</strong></p>
            <p>.</p>
            
             
            <p>This annual programme will encourage healthy competition between students and schools, as well
            as driving traffic to the site and therefore increasing the audience for the students' work and
            the profile of the school. The final exhibition will provide a wonderful opportunity for
            the successful students to show their work in a public setting and a fantastic way of celebrating 
            the art work created and the school's commitment to arts education, demonstrating the quality of art produced to parents, 
            families, local authorities and the wider community. Finally the programme can help
            participating schools meet many of the KS2 and 3 <strong>National Curriculum</strong> requirements for Art and
            Design, the criteria outlined in the <strong>OFSTED</strong> evaluation framework, as well as providing a
            valuable tool for schools working towards <strong>Artsmark</strong> status.</p>
            <p>.</p>
            
            <blockquote>
                <p>Pupils benefited greatly from the feedback received when their work was shared locally or more widely...</p>
                <p>Schools should... build sustained partnerships with art galleries and creative practitioners.</p>
                <p>Pupils who met with inspectors reported consistently the motivational impact of seeing their own work displayed professionally and publicly...</p>
                <p>The public exhibition of students' work was highly effective in strengthening links between schools and the local community, including diverse community groups, different generations and those living in contrasting socio-economic circumstances.</p>
                <small>Extracts from: Ofsted Report - Making a mark: art, craft and design education, 2008/11</small>
            </blockquote>
        </div>
        
        <div class="tab-pane fade in" id="tab-teachers">
      
      


        </div>
        
    </div>
    
</div>
</div>
</div>

</div>
