<?php
   $this->headTitle('What?');
   $this->headMeta()->appendName('description', 'dot-art Schools is an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<script type="text/javascript">twttr.conversion.trackPid('nu3ux', { tw_sale_amount: 0, tw_order_quantity: 0 });</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
</noscript>


<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">What?</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">What? <span class="divider">/</span></li>
  <li class="active">Information for Teachers</li>
</ul>

<div class="row">
<div class="span12">


            <h2>Information for Teachers</h2>
            
            <p><a href="http://cheshire.schools.dot-art.com/docs/NEW-dot-art-Schools-Sign-Up-Form.pdf">Download the Entry Form.</a></p>
            
            <p><a href="http://cheshire.schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet-New.pdf">Download the Teachers Information Leaflet</a></p>

           <p>dot-art Schools was first launched in the <a href="http://liverpool.schools.dot-art.com">Liverpool City Region</a> 
           in 2012 and since then over 5000 children have taken 
           part from almost 300 schools. We have held exhibitions at the Domino Gallery, the Walker Art Gallery, St George 
           Hall, Mid Cheshire College and Liverpool School of Art and Design and each year, three children from each 
           participating school have been presented with a certificate by the 
           Lord Mayor of Liverpool or a corresponding dignatary from Cheshire, as well as a range of prizes awarded. 
           In response to feedback from schools, in September 2016 we 
            changed the primary age group from Year 6 to Year 5.</p>
            
            
             <p>In September 2016, thanks to our new partnership with LJMU, dot-art Schools also launched in 
             <a href="http://cheshire.schools.dot-art.com">Cheshire.</a>
             A small group of Primary and secondary schools in Cheshire West & Chester, Cheshire East and Warrington took 
             part in the pilot year of our second region in 2016-17 and from September 2017 onwards we invite all 
             schools in the region to take part in the programme.</b></p>
              
      <p>We are pleased to announce that from February 2018, dot-art Schools is an 
              <a href="http://www.artsmark.org.uk/artsmark-partnership-programme">Artsmark Partner</a>.
              Artsmark is the creative quality standard for schools and education
              settings, awarded by Arts Council England, recognising their
              commitment to high quality arts and cultural education.
              dot-art Schools is proud to be supporting schools and
              education settings on their Artsmark journey, inspiring children and
                young people to create, experience, and participate in great arts and
              culture.</p>  
              
             <p>Find out more about Artsmark at <a href="http://www.artsmark.org.uk.">artsmark.org.uk</a>
               and how we can support you on our <a href="../what/artsmark">Artsmark page.</a>
              </p> 
              
              
                 <a href="http://www.artsmark.org.uk"><img src="/images/artsmark-partner-400.jpg" title="dot-art Schools Artsmark Partner" alt="dot-art Schools Artsmark Partner"/></a>
           

            <p>Please download the document below for more details about how the programme works and the benefits it can
            bring:</p>
            <ul>
                <li><a href="http://schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet-New.pdf" target="_blank">dot-art Schools Teachers Leaflet</a></li>
            </ul>
             
            <!---
            <li><a href="/docs/dot-art-Schools-KS2.pdf" target="_blank">dot-art Schools and the National Curriculum (year 6)</a></li>
                 <li><a href="/docs/dot-art-Schools-KS3.pdf" target="_blank">dot-art Schools and the National Curriculum (year 9)</a></li>
                <li><a href="/docs/dot-art-Schools-Ofsted.pdf" target="_blank">dot-art Schools and OFSTED</a></li>
                 <li><a href="/docs/dot-art-Schools-Arts-Award-Artsmark.pdf" target="_blank">dot-art Schools and Arts Award / Artsmark (overview)</a></li>
                <li><a href="/docs/dot-art-Schools-Artsmark-Detail.pdf" target="_blank">dot-art Schools and Artsmark (detail)</a></li>

                 <p>If you would like to take part, please complete and return the following Entry Form:</p>
            <ul>
                <li><a href="http://schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet.pdf" target="_blank">dot-art Schools Entry Form 2015-16</a></li>
            </ul>
           
                      -->
                      
                      
            <p><strong>Key Facts 2017-18:</strong></p>
            <ul>
                <li>19 schools participated.</li>
                <li>283 student art works displayed online.</li>
                <li>1500 votes cast.</li>
                <li>6000 unique visitors to the website.</li>
                 <li>19 student art works were showcased to the public at Storyhouse, Chester</li>
                  <li>108 guests including 42 students, their families and teachers celebrated at prize giving ceremony in the Garret Theatre at Storyhouse.</li>
                  <li>250 visitors to the exhibition at Storyhouse, Chester (including The Queen and Duchess of Sussex)!</li>
                  
            </ul
           
        
      
            
             <p><strong>Feedback from schools:</strong></p>
            <ul>
                <li>"What a fantastic event and such great art work. Brilliant to be here this evening with pupils and parents, 
                looking at the work on display. Very proud teacher!"</li>
                <li>"I wanted to express my gratitude for opportunities like dot-art Schools to celebrate the 
                "small and every day wins" that usually go unnoticed at school - especially at a time where the 
                family are going through some issues."</li>
                <li>"It has been a long time since we have had something of this calibre to promote and
                celebrate the work of our young artists"</li>
            </ul>
            
             <p><strong>Feedback from exhibition visitors:</strong></p>
            <ul>
                <li>"Carry on with all your wonderful work. dot-art is an inspirational organisation and needed now more than ever."</li>
                <li>"Just amazed at the young talent. Some of the work is so good I thought it was done by adults."</li>
                <li>"Really high standard. I'm amazed by the Owl - beautiful"</li>
            </ul>
            
             <p><strong>Key Dates 2018-19:</strong></p>
            <ul>
              <li>September 2018 - School recruitment for 2018-19 programme begins.</li>
                <li>December 2018 - Deadline for schools to sign up.</li>
                <li>February 2019 - Deadline for schools to submit work for competition.</li>
                <li>April 2019 - Online voting period.</li>
                <li>June 2019 - Prize Giving Ceremony.</li>
                 <li>June 2019 - Exhibition of winning works.</li>
            </ul>
            
        </div>
   
            
        </div>
        
    </div>
    
</div>
</div>
</div>

</div>

