INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 1, "Bank View High School", "bank-view-high", "Bank View High school is a special provision school for ASD and CLD students from Year 7 to 14. We have a large number of students with social, emotional and physical needs. The artwork I have submitted this year in our first time of dot-art Schools is a mixture of Year 9 students who have started looking at African Art, in particularly the patterns and masks of that culture. These are all A4 size and completed in Colour pencils or watercolours or a mix of both. The other entries are from students who have completed mixed media abstract compositions inspired by their research of Frank Stella and Kandinsky. ", "http://www.bankviewhighschool.com/", "bank-view-high-logo.jpg", "bank-view-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 1, "Childwall Abbey School", "childwall-abbey-school", "Childwall Abbey School is a secondary school which provides quality education for pupils who have complex learning difficulties including Autistic Spectrum Disorder. We believe that all our pupils can achieve, if they are provided with the curriculum, learning environment and support, which meets their needs. At Childwall Abbey, we develop independence and self-esteem in all our pupils through a broad and balanced curriculum to develop skills for adult life, achieve nationally accredited certification and become active contributors to the wider community.", "http://www.childwallabbeyschool.net/", "childwall-abbey-logo.jpg", "childwall-abbey-school");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 1, "Kings Leadership Academy Liverpool", "kings-leadership-liverpool", "At King’s Leadership Academy we place great emphasis on building strong character traits in all of our students. We believe that strength of character is the cornerstone of academic success. In Art, Year 9 students have been exploring the theme of identity. Here they have used a variety of media to investigate, explore and record their own personal response to this theme.", "http://www.kingsliverpool.com/", "kings-leadership-liverpool-logo.jpg", "kings-leadership-liverpool");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 1, "Knowsley Central School", "knowsley-central", "Knowsley Central School is a community that nurtures and supports each individual pupil, that values everyone’s unique worth and contribution, empowering every pupil to achieve their full potential and opens up a whole new world of opportunities. As a school we nurture and guide pupils with special educational needs to realise their full potential. With a holistic approach to our curriculum pupils are enabled to express themselves creatively across all key stages. Within Creative Arts pupils are exposed to an extensive and specialist range of materials, expertise, processes, values and culture in order to enhance their learning and progress. ", "http://knowsleycentral.co.uk/", "knowsley-central-logo.jpg", "knowsley-central-school");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "Mosspits Lane Primary School", "mosspits-lane-primary", "Mosspits Lane Primary School is based in Wavertree, Liverpool. We are passionate about our creative curriculum and the variety of ways we incorporate exciting opportunities for our children. We have established our art scheme to focus on building skills and developing techniques. Through this, we have managed to create beautiful pieces using many drawing, sculpting, painting and textile skills.  Our Year 5 children have explored African culture in depth, learning about the environment, the people, traditions, music and art. They have created observational drawings of African artefacts and used these to inspire designs for their own African masks. ", "http://www.mosspits.com", "mosspits-lane-logo.jpg", "mosspits-lane-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 1, "Ormiston Chadwick Academy", "ormiston-chadwick", "Ormiston Chadwick Academy is named after the Nobel prizewinner and physicist Sir James Chadwick. The academy is based in Widnes and is a mixed secondary school with 643 students on roll.  In 2016, outcomes were significantly above average for all groups of pupils, placing the school in the top 10% of all schools nationally for pupils’ progress. In KS4 students embark on their GCSE options, which include Graphic Communications, Fine Art or Textiles. They therefore follow a varied programme of study designed to provide every student with an opportunity to demonstrate their skills, knowledge and understanding to their full potential.", "http://www.ormistonchadwickacademy.co.uk/", "ormiston-chadwick-logo.jpg", "ormiston-chadwick");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 1, "Peterhouse School", "peterhouse-school", "Peterhouse is a non-maintained specialist school for Autism. The Arts activities are often used as a motivator, focus and vehicle for learning. This enables our students to strive for independence and successful development of life skills as well as using the Arts as a way of expressing themselves. We aim to provide multi-sensory experiences where the process is just as valuable as the end product. We have high expectations for our students and focus on what they can achieve through the creative curriculum rather than what they find difficult. The Arts also support and enable students to achieve at individual levels through personalised learning and the development of self-occupancy skills. ", "http://www.peterhouseschool.com/", "peterhouse-logo.jpg", "peterhouse-school");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "Springwell Park Primary School", "springwell-park-primary", "Springwell Park is a primary school in Bootle, Liverpool. Year 5's topic this term is Ancient Egypt. This is the childrens artwork from a homework task set for the year group.", "http://www.springwellparkprimary.co.uk/", "springwell-park-logo.jpg", "springwell-park-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "St Bertelines CE Primary School", "st-bertelines-primary", "At St Berteline’s, we very much value ‘The Arts’ and in particular the spiritual dimension they contribute to the curriculum.  Visual Art, in its many guises, is used as a vehicle for the teaching and learning of other curriculum subjects as well as being a subject worthy of study in its own right.  Our children have a good knowledge of various artists from different periods of time; they visit galleries and actively research to find out more information. Each child, from age 4, possesses their own sketch book which is very much a working document, used to experiment with media, to note and re-work ideas, to try different techniques and generally to promote an attitude of ‘Have a go! Art is never wrong’!", "http://stbertelines.org.uk/", "st-bertelines-logo.jpg", "st-bertelines-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "St Oswalds Catholic Primary School", "st-oswalds", "St Oswald’s Catholic Primary School is situated in Old Swan, Liverpool. As a school, we aim to ensure that all children grow to love their learning and live out the Gospel values in all that we think, say and do. The pupils and staff at St Oswald’s embrace art and strive to develop our creativity in all aspects of the art curriculum. We are a vibrant and inclusive school that celebrates the achievements of all its pupils.  Our Year 5 pupils have been working extremely hard this term to research the artist Michelangelo who was an Italian sculptor, painter, architect and poet of the High Renaissance.", "http://stoswaldsschool.com/", "st-oswalds-logo.jpg", "st-oswalds-catholic-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 1, "The Sutton Academy", "sutton-academy", "The Sutton Academy is a mixed 11 – 18 secondary school of over 1200 students. It is a thriving and dynamic place to learn, were together students achieve.   The art department is an exciting and vibrant part of The Sutton Academy. We encourage our students to be creative individuals and recognise that every student is different; we aim to nurture creativity and individuality.  Recently our year 9 students have been creating mixed media ‘doodle bombed’portraits inspired by the artist Hattie Stewart. Their art work combines drawing, collage and lettering to develop a range of personal outcomes.", "http://www.thesuttonacademy.org.uk", "sutton-academy-logo.jpg", "the-sutton-academy");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);
