INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Acton CE Primary Academy", "acton-ce-primary", "Acton CE Primary Academy is a small, rural school situated in Cheshire.  Creativity is a priority and central part of our ͚Real Life Curriculum͛. We believe in immersing children in as many experiences through art as possible. Our children͛s love of art was recently highlighted in our SIAMs inspection where one child explained that ͚in art we can really let our imaginations go͛.  Year 5 have been learning about traditional and abstract portraits. They have chosen to either layer self-portraits to produce abstract art in acrylics, or produce a more traditional line and water colour painting of Queen Elizabeth I.", "http://www.actonceprimary.net", "acton-ce-primary-logo.jpg", "acton-ce-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Bishops Bluecoat CoE High School", "bishops-bluecoat", "We are passionate about education and know that students, staff and parents working together create an outstanding climate for learning. There is a tangible sense of pride and positivity within our school, stemming from the belief that each student will be known, nurtured and inspired to progress academically and grow as a person.  There is very effective provision for learning and personal development; our values prepare students exceptionally well to take their place in modern Britain. Known, nurtured and inspired: the young people of Bishops' will succeed and make a positive difference to the world in which we live.", "http://www.bishopschester.co.uk", "bishops-bluecoat-logo.jpg", "bishops-bluecoat");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Bridgewater High School", "bridgewater-high", "Bridgewater is a popular and successful 11 to 19 comprehensive school, situated on two sites to the south of Warrington.  Bridgewater Art department is part of a vibrant Arts community.   Pupils in year 9 undertake two major projects and all pupils are entered into a Trinity arts exam. The work submitted this year was based on the first major project of the year, which was a Zine project. Pupils explored a theme that interests them to base their zine on and they were then asked to use an element of it to transform into a textiles piece", "http://www.bridgewaterhigh.org", "bridgewater-high-logo.jpg", "bridgewater-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Delamere CofE Primary Academy", "delamere-ce-primary", "Delamere CofE Primary Academy is an 'Outstanding School', situated near Tarporley in Cheshire. At Delamere we are proud to deliver a rich creative learning experience that enables all the children to fulfil their potential. The Academy goes 'above and beyond' with art, we believe that through the arts we enrich the lives of all children. Arts subjects stimulate creativity and imagination and enable children to communicate what they see, feel and think about the real and imaginary world in a variety of ways and through different mediums.", "http://www.delamereacademy.co.uk", "delamere-logo.jpg", "delamere-ce-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Fallibroome Academy", "fallibroome-academy", "The Fallibroome Art Department provides a sense of security and an atmosphere of respect out of which student's creativity can flourish. We encourage our students to engage with all aspects of art, craft and design and work together to develop the quality and range of courses, facilities and experiences available to our students. We recognise our responsibility for raising student awareness and understanding of the potential future opportunities available through a good education in a creative subject. We look to share our passion for the subject, subsequently engaging, enthusing and building the confidence of every student.", "http://fallibroome.academy", "fallibroome-logo.jpg", "fallibroome-academy");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Great Sankey High School", "great-sankey-high", "Great Sankey High School in Warrington is a place where every child is recognised as an individual, where their talents are nurtured, aspirations exceeded and where we collectively strive to achieve more.  Academic attainment and achievement is high – our personalised curriculum empowers all students to achieve their ambitions and fulfil their high aspirations. Oou vision in the art department at Great Sankey High School is to create an environment in which every child can feel confident and succeed. To encourage individual creativity and nurture a passion for the subject. We are very proud of the work our students create!", "http://www.greatsankey.org", "great-sankey-high-logo.jpg", "great-sankey-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Green Lane Community Special Primary School", "green-lane-special-primary", "Green Lane is a school which caters for 139 pupils, ranging from age 4 to 18. Pupils have a wide range of special needs, from moderate to severe and around half have communication difficulties, including ASD. Staff at school are extremely committed to the personal and social development of the pupils and strive to deliver a rich and balanced curriculum promoting independence, resilience and creativity.  This is no more apparent than in the teaching of art.  Every pupil is encouraged to develop their senses through their art work and express their ideas, feelings and imagination using visual media.", "http://www.greenlaneschool.co.uk", "green-lane-special-primary-logo.jpg", "green-lane-special-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Green Lane Community Special School", "green-lane-special-school", "Green Lane is a school which caters for 139 pupils, ranging from age 4 to 18. Pupils have a wide range of special needs, from moderate to severe and around half have communication difficulties, including ASD. Staff at school are extremely committed to the personal and social development of the pupils and strive to deliver a rich and balanced curriculum promoting independence, resilience and creativity.  This is no more apparent than in the teaching of art.  Every pupil is encouraged to develop their senses through their art work and express their ideas, feelings and imagination using visual media.", "http://www.greenlaneschool.co.uk", "green-lane-special-school-logo.jpg", "green-lane-special-school");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Kelsall Primary School", "kelsall-primary", "Kelsall Primary School is a rural school not far from Chester. Kelsall has a reputation for being a specialist school in Art which is promoted through a creative curriculum. Our school is fortunate to have an art studio and runs twilight courses for teachers. Most 2D and 3D art work filling our classrooms and corridors is mixed media and can be individual or group pieces, often the end result from much time experimenting and enjoying a variety of art media. We love using sketchbooks to record techniques and ideas both in art and writing, often displayed with finished work.", "http://www.kelsall.cheshire.sch.uk", "kelsall-primary-logo.jpg", "kelsall-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Kings Leadership Academy Warrington", "kings-warrington", "Over the course of six weeks, Year 9 King's students have been creating artwork based on the theme of foreshortening. Their aim has been to demonstrate their understanding of composition, perspective, contrast, tone and texture within their pieces, therefore proving their understanding of art techniques. They have all had to scale up their photograph from A4 to A3 or larger, demonstrating their drawing ability, craftsmanship and control. In many cases, students have communicated a personal message or concept within their work.", "http://www.kingswarrington.com", "kings-warrington-logo.jpg", "kings-warrington");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Mottram St Andrew Primary Academy", "mottram-st-andrew-primary", "We are a small school of 160 pupils in Cheshire. We are part of the Fallibroome Learning Community and support a creative curriculum where art is a significant part. Year 5 have produced 3-d pop art cityscapes looking at the work of Charles Fazzino. Submission 1 is a canvas produced in art club", "http://www.thelifecloud.net/schools/MottramStAndrewPrimaryAcademy", "mottram-st-andrew-logo.jpg", "mottram-st-andrew-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Newchurch Primary School", "newchurch-primary", "Newchurch Primary is a single form entry school in Culcheth, Warrington which aims to nurture the creativity of its children. The school is an Artsmark Gold Award establishment in which the visual and creative arts are upheld as highly as core subjects. The children frequently exhibit their work within school and the wider community along with staging theatrical performances in KS1, Y4 and Y6. Each year we look to offer the children access to the arts through educational visits and visiting professionals, all of which helps to develop our children's creativity.", "http://www.newchurchprimary.co.uk", "newchurch-primary-logo.jpg", "newchurch-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Oaklands School", "oaklands-school", "We cater for Complex moderate Learning difficulties. A unique and outstanding school for 11 to 17 year olds! Oaklands is a school where pupils like to attend and parents feel safe in the knowledge that their children are being well taught and nurtured. A strength of our school is that we are forward thinking and committed to the needs of all our pupils and their families. We strive to ensure that we demonstrate our care and compassion but coupled with this we have high expectations and we strive to help our pupils overcome the significant barriers to learning they face. We are equally determined that our pupils are prepared for their life after school. The art work is based on Landmarks, pupils were given the opportunity to be able to choose and work independently on their pieces. Art at Oaklands is taught throughout all key stage three, offering an ASDAN Award in Expressive Arts at the end of Year nine. Moving into Key stage four all pupils either follow a GCSE Art and Design or Entry Level Certificate. As a school we have a high 'CAN DO' attitude.", "http://www.oaklandsschool.org.uk", "oaklands-school-logo.jpg", "oaklands-school");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Sacred Heart Catholic Primary", "sacred-heart-catholic-primary", "At Sacred Heart Catholic Primary School in Warrington we aim to provide a warm, happy and stimulating environment in which children enjoy learning and we are able to appreciate its importance and relevance to their lives. We are all for the education of the 'whole child', and truly believe the development of Art skills will enable the achievement of personal fulfillment and satisfaction of the child. We feel that success increases self esteem and gives pleasure in the subject. We aim to display work when possible to celebrate pupil achievement and to enable pupil satisfaction both inside and outside of the classroom environment. We have art ambassadors who choose children to receive an award every week to celebrate achievement in a creative non academic sense.", "https://www.sacredheartcp.co.uk", "sacred-heart-logo.jpg", "sacred-heart-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Sandymoor Free School", "sandymoor-free-school", "An 11-18 school producing intelligent, employable global citizens that demonstrate social competence, a desire for learning and respect for each other and the world around us. The school will be recognised for excellence in science, technology, enterprise and sport.", "http://www.sandymoorschool.org.uk", "sandymoor-school-logo.jpg", "sandymoor-free-school");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "St Nicholas Catholic High School", "st-nicholas-catholic-high", "We are an 11-18 co-educational Catholic Comprehensive School in Hartford with Business and Enterprise College status and a second specialism as a Leading Edge school.The school has an excellent reputation and provides for its students an environment that challenges them to make the most of their God-given talents while at the same time helping them to develop as young people. 'Art is a unique way of understanding and responding to the world'. In year 9 students develop their creativity and imagination. Topics include 'Image and Text' and 'Card construction Cameras'.", "http://www.st-nicholas.cheshire.sch.uk", "st-nicholas-high-logo.jpg", "st-nicholas-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "St Winefrides Catholic Primary", "st-winefrides-catholic-primary", "Our art work is based on the Artist Piet Mondrian. We used bright colours to create different sections. Each section has a design on it that we created based on our lives, our families and our friends.", "http://www.stwinefrides.cheshire.sch.uk", "st-winefrides-logo.jpg", "st-winefrides-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "The Catholic High School Chester", "the-catholic-high", "The Catholic High School, Chester provides a broad, yet structured course within Art & Design education, combining both practical experience and an understanding of the work of others through a range of practical activities and processes. All groups are taught as mixed ability, where project starting points, allowing all students the opportunity to shine. All practical work is planned in project form by the class teacher, and aims to establish the formal elements of Art & Design. The teacher will plan for progression of key concepts and keyprocesses across the years, ensuring that logical, sequential learning is evident throughout.", "http://www.christofidelis.org.uk", "the-catholic-high-logo.jpg", "the-catholic-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Upton Priory School", "upton-priory-school", "Upton Priory is a large Primary school in Macclesfield.  Following tailored lessons in tone, animal forms and still life the children chose to create their own piece of work based on their individual interests.", "https://www.uptonpriory.cheshire.sch.uk", "upton-priory-logo.jpg", "upton-priory");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2017);
