<?php
   $this->headTitle('Information for Teachers?');
   $this->headMeta()->appendName('description', 'dot-art Schools is an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<script type="text/javascript">twttr.conversion.trackPid('nu3ux', { tw_sale_amount: 0, tw_order_quantity: 0 });</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
</noscript>


<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">What?</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">What? <span class="divider">/</span></li>
  <li class="active">Background</li>
</ul>

<div class="row">
<div class="span12">
         
           
        <div>
            <h2>Background</h2>
            <p>The dot-art Schools programme has been developed by <b>dot-art</b>, a Liverpool based arts organisation which has
            been supporting artists and developing innovative and creative visual arts projects and initiatives since 2006.</p>

            <p>In 2012 we were approached by a Liverpool school who asked if we could develop a way to showcase the art work
            of talented school children in the same way we do professional artists. Since then we have been using our skills, 
            experience and expertise to give the young people of the region access to an
            exciting new public platform for their creative output, and a taste of the way the art world works.</p>

            <blockquote><i><b>dot-art supports visual artists and champions art as an integral part of everyday life</b></i></blockquote>

            <p>We do this by selling locally sourced, affordable art, working with businesses to put art in the workplace and 
            public realm, running art classes and working with schools and community groups. All this is underpinned by our 
            unique membership scheme for artists in the North West which gives access to all the activities above and a 
            package of support and advice, creating and developing artists' careers.
            </p>
            
            <p>dot-art was founded in Liverpool in 2006 and specialises in affordable, high quality, locally sourced art. 
            We work with over 100 artists to provide an unrivaled choice of original art and limited edition prints for home 
            or business, as well as offering a range of complementary services including; commissions, art rental, art 
            consultancy, exhibition planning and implementation, bespoke framing, art valuation and restoration and artist 
            sourcing.</p>
            
            <p>All our work supports our not-for profit arm <strong>dot-art Services CIC</strong>, which exists to support 
            North-West based visual artists, both emerging and established, through a range of services and opportunities 
            designed to help them develop their careers and gain exposure and promotion for their work, as well as delivering 
            a programme of adult art classes at a range of venues across Liverpool and dot-art Schools, our innovative 
            inter school art competition, launched in 2012.</p>
            
            <p><b>For more information, see: <a href="http://www.dot-art.com">dot-art.com</a></b></p> 
            
            
          
        </div>
        
    <div class="row row-entry">

            <div class="span12">
            <img src="/images/banner-5.jpg" title="dot-art Vision Banner" alt="dot-art Vision Banner"/>
            </div>
            
            </div>     
      
</div>
</div>
</div>

</div>


