<?php
   $this->headTitle('What?');
   $this->headMeta()->appendName('description', 'dot-art Schools is an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<script type="text/javascript">twttr.conversion.trackPid('nu3ux', { tw_sale_amount: 0, tw_order_quantity: 0 });</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
</noscript>


<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">What?</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">What?</li>
</ul>

<div class="row">
<div class="span12">

<div class="tabbable" id="stages">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-program" data-toggle="tab">
            The Programme
        </a></li>
        <li><a href="#tab-teachers" data-toggle="tab">
            Information for Teachers
        </a></li>
        <li><a href="#tab-background" data-toggle="tab">
            Background
        </a></li>
        <li><a href="#tab-supporters" data-toggle="tab">
            Supporters
        </a></li>
      <!--  <li><a href="#tab-partners" data-toggle="tab">
            Partners
        </a></li> -->
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab-program">
        
           <!---
            <p><a href="/docs/dot-art-Schools-Overview-2014-15.pdf" target="_blank">Download a PDF overview of dot-art Schools</a></p>
              <p><a href="/docs/dot-art-Schools-Sign-Up-Form-2014-15.pdf" target="_blank">Download a PDF of the dot-art Schools Sign Up Form for 2014-15</a></p>
              <p><a href="/docs/dot-art-Schools-Sign-Up-Form-2014-15.doc" target="_blank">Download a Word document of the dot-art Schools Sign Up Form for 2014-15</a></p>
            -->

            
            <div class="row row-entry">

            <div class="span4">
            <img src="/images/2015-Exhibition/dot-art-Schools-2015-182.jpg" title="dot-art Schools Exhibition 2015" alt="dot-art Schools Exhibition 2015"/>
            </div>
            
            <div class="span4">
            <img src="/images/2015-Exhibition/dot-art-Schools-2015-56.jpg" title="dot-art Schools Exhibition 2015" alt="dot-art Schools Exhibition 2015"/>
            </div>
            
            <div class="span4">
            <img src="/images/2015-Exhibition/dot-art-Schools-2015-70.jpg" title="dot-art Schools Exhibition 2015" alt="dot-art Schools Exhibition 2015"/>
            </div>
            </div>
            

            <h2>Sign Up</h2>
            
            <p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Entry-Form.pdf">Download the 2016-17 Entry Form.</a></p>
            
            <p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet.pdf">Download the Teachers Information Leaflet</a></p>

   
             
            
            <p>**The deadline for entering dot-art Schools 2016-17 has now passed. If you are interested in taking part next academic year, please download the leaflet below for more information and sign up to
            our <a href="http://schools.dot-art.com/contact">SCHOOLS MAILING LIST</a>**</p>

            
            
            <h2>The Programme</h2>
    
            <p>dot-art Schools is an <strong>interactive, online, inter-school, art competition</strong>, taking part on an annual basis and
            culminating in an exhibition. Open to primary <strong>(year 5, NEW FOR THIS YEAR!)</strong> and secondary 
            <strong>(year 9)</strong> schools in the <strong>Liverpool
            City Region, and NEW for 2016-17, in Cheshire West & Chester, Cheshire East and Warrington.</strong>. 
            It is designed to nurture talent, raise ambition, and take art out of the classroom and into the
            real world. With the current threats to creative subjects on the national curriculum, dot-art Schools offers a
            way of keeping young people engaged with the arts, allows them to see a creative career path, and
            encourages them to attend exhibitions and engage with culture, outside of school.</p>
            
            <h2>How It Works</h2>
            
            <p>During the <strong>Autumn and Spring terms</strong>, each school creates and selects <strong>25 pieces</strong> 
            of student work which
            they feel best represent the talents of their students. These art works are submitted to their dot-art Schools
            page by <strong>February Half Term</strong>, then put on display to the world via the dot-art Schools website
            (schools.dot-art.com).</p>
            
            <p>A panel of art experts will select the top 3 artworks from each school. Students from all the schools in the
            programme, as well as the general public, will then be able to <strong>vote</strong> for their favourite piece of art from the
            judge's shortlist. During the Summer term, an <strong>exhibition</strong> will be held at a <strong>city centre art gallery</strong> 
            showcasing the artwork with the most votes from each participating school.</p>

            <h2>Prizes</h2>
            
            <h3>Secondary</h3>
            
            <p><strong>Overall winner</strong></p> 
            <ul>
            <li>Scholarship to <b>dot-art</b>, giving them a year's membership
            to dot-art's network, allowing them to showcase and sell their work alongside professional artists. 
            (See: <a href="http://dot-art.co.uk/artist/">dot-art.co.uk/artist/</a>)</li>
            <li>Tickets to see the latest exhibition at <b>Tate Liverpool</b>.</li> 
            <li>£50 worth of vouchers to spend at <b>Rennies</b> Art Supplies.</li>
           <li>PLUS NEW for 2016 <strong>*** FOR THE WINNING SCHOOL *** </strong>- £250 worth of vouchers to spend at <b>Cass Art</b>.</li>
            </ul>
            
            <p><strong>Runners Up x 2</strong></p> 
            <ul>
            <li>Tickets to see the latest exhibtion at <b>Tate Liverpool</b></li> 
            <li>£25 worth of vouchers to spend at <b>Rennies</b> Art Supplies.</li>
            </ul>
            
            <h3>Primary</h3>
            
            <p><strong>Overall winner</strong></p> 
            <ul>
            <li>Family day out for 4 at the <b>Albert Dock</b>, including lunch, tickets to the Beatles Story,
            rides on the Wheel of Liverpool and more!</li>
            <li>Tickets to see the latest exhibition at <b>Tate Liverpool</b></li> 
            <li>£50 worth of vouchers to spend at <b>Rennies</b> Art Supplies.</li>
           <li>PLUS NEW for 2016 <strong>*** FOR THE WINNING SCHOOL *** </strong>- £250 worth of vouchers to spend at <b>Cass Art</b>.</li>
            </ul>
            
            <p><strong>Runners Up x 2</strong></p> 
            <ul>
            <li>Tickets to see the latest exhibtion at <b>Tate Liverpool</b></li> 
            <li>£25 worth of vouchers to spend at <b>Rennies</b> Art Supplies.</li>
            </ul>
            
            <p>All winning artists (1 from each partipating school) will also receive a <b>Tangle Teezer</b> hairbrush.</p>
            <p>All shortlisted artists (3 from each partipating school) will be awarded <strong>certificates.</strong></p>
            <p>.</p>
            
            <p>This annual programme will encourage healthy competition between students and schools, as well
            as driving traffic to the site and therefore increasing the audience for the students' work and
            the profile of the school. The final exhibition will provide a wonderful opportunity for
            the successful students to show their work in a public setting and a fantastic way of celebrating 
            the art work created and the school's commitment to arts education, demonstrating the quality of art produced to parents, 
            families, local authorities and the wider community. Finally the programme can help
            participating schools meet many of the KS2 and 3 <strong>National Curriculum</strong> requirements for Art and
            Design, the criteria outlined in the <strong>OFSTED</strong> evaluation framework, as well as providing a
            valuable tool for schools working towards <strong>Artsmark</strong> status.</p>
            <p>.</p>
            
            <blockquote>
                <p>Pupils benefited greatly from the feedback received when their work was shared locally or more widely...</p>
                <p>Schools should... build sustained partnerships with art galleries and creative practitioners.</p>
                <p>Pupils who met with inspectors reported consistently the motivational impact of seeing their own work displayed professionally and publicly...</p>
                <p>The public exhibition of students' work was highly effective in strengthening links between schools and the local community, including diverse community groups, different generations and those living in contrasting socio-economic circumstances.</p>
                <small>Extracts from: Ofsted Report - Making a mark: art, craft and design education, 2008/11</small>
            </blockquote>
        </div>
        
        <div class="tab-pane fade in" id="tab-teachers">
        
         <p>**The deadline for entering dot-art Schools 2016-17 has now passed. If you are interested in taking part next academic year, please download the leaflet below for more information and sign up to
            our <a href="http://schools.dot-art.com/contact">SCHOOLS MAILING LIST</a>**</p>

          <!--
        <p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet.pdf">Download the Teachers Information Leaflet</a></p>
            <p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Entry-Form.pdf">Download the 2016-17 Entry Form.</a></p>
              -->
              
            <h2>Information for Teachers</h2>
            
            <p>dot-art Schools was launched in 2012 and since then over 3000 children have taken part from almost 170 schools.
            We have held exhibitions at the Domino Gallery, the Walker Art Gallery and St George Hall and each year,
            three children from each participating school have been presented with a certificate by the Lord Mayor of Liverpool.
            This wonderful prize giving ceremony, attended by families and staff, which for the Liverpool programme now 
            takes place in the stunning Concert Room at St Georges Hall (Cheshire location TBC), is where the overall 
            winners and runner up are also announced.</p>
            
            
             
             
             <div class="well well-lg"> 
             <p><b>NEW! In September 2016, thanks to our new partnership with LJMU, dot-art Schools is coming to Cheshire!<br>
             Primary and secondary schools in Cheshire West & Chester, Cheshire East and Warrington are invited to
             take part in our pilot year.</b></p>
              </div>
                
            <p><b>From September 2016 we are accepting new primary and secondary schools onto the fifth year of the programme 
              from across Liverpool and Cheshire.<br>
              PLEASE NOTE - In response to feedback from schools we have changed the primary age group from Year 6
               to Year 5.</b></p>

            <p>Please download the document below for more details about how the programme works and the benefits it can
            bring:</p>
            <ul>
                <li><a href="http://schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet.pdf" target="_blank">dot-art Schools Teachers Leaflet</a></li>
            </ul>
            
            <!---
            <li><a href="/docs/dot-art-Schools-KS2.pdf" target="_blank">dot-art Schools and the National Curriculum (year 6)</a></li>
                 <li><a href="/docs/dot-art-Schools-KS3.pdf" target="_blank">dot-art Schools and the National Curriculum (year 9)</a></li>
                <li><a href="/docs/dot-art-Schools-Ofsted.pdf" target="_blank">dot-art Schools and OFSTED</a></li>
                 <li><a href="/docs/dot-art-Schools-Arts-Award-Artsmark.pdf" target="_blank">dot-art Schools and Arts Award / Artsmark (overview)</a></li>
                <li><a href="/docs/dot-art-Schools-Artsmark-Detail.pdf" target="_blank">dot-art Schools and Artsmark (detail)</a></li>

            -->

            <p>If you would like to take part, please complete and return the following Entry Form:</p>
            <ul>
                 <li><a href="http://schools.dot-art.com/docs/dot-art-Schools-Entry-Form.pdf">dot-art Schools 2016-17 Entry Form.</a></li>
            </ul>
            
            <p><strong>Key Facts 2015-16:</strong></p>
            <ul>
                <li>54 schools participated.</li>
                <li>1000 student art works displayed online.</li>
                <li>3600 votes cast.</li>
                <li>12000 unique visitors to the website.</li>
                 <li>54 student art works were showcased to the public in St George's Hall.</li>
                  <li>162 students celebrated at prize giving ceremony in the Concert Room at St George’s Hall</li>
                  <li>1100 visitors to the exhibition at St George's Hall.</li>
                  <li>20000 people viewed the exhibition at Lime Street Lower Level Station.</li>
            </ul
            
           
          
            
             <p><strong>Feedback from schools:</strong></p>
            <ul>
                <li>“We have just looked at the art work on the website, the work looks amazing. We are so happy with
                the quality of all of the schools submissions. You have done a great job!”</li>
                <li>“I have just looked at our page and I am very impressed with the whole project”</li>
                <li>“What a fantastic event!”</li>
                <li>“It has been a long time since we have had something of this calibre in the city to promote and
                celebrate the work of our young artists”</li>
            </ul>
            
             <p><strong>Feedback from exhibition visitors:</strong></p>
            <ul>
                <li>“What a fantastic level of skill from such talented young people"</li>
                <li>"What talented youth we have in Liverpool, so impressed with all the artwork presented"</li>
                <li>"A lovely exhibition with some excellent work on display, hope it encourages many of the exhibitors
                to become artists of the future"</li>
                <li>"I didn't realise the work was all by people under 15! Rather inspiring"</li>
            </ul>
            
             <p><strong>Key Dates 2016-17:</strong></p>
            <ul>
                <li>September 2016 – School recruitment for 2016-17 programme begins.</li>
                <li>December 2016 – Deadline for schools to sign up.</li>
                <li>February 2017 – Deadline for schools to submit work for competition.</li>
                <li>April 2017 – Online voting period.</li>
                <li>May 2017 – Prize Giving Ceremony.</li>
                 <li>June 2017 – Exhibition of winning works.</li>
            </ul>
            
        </div>
        
        <div class="tab-pane fade in" id="tab-background">
            <h2>Background</h2>
            <p>The dot-art Schools programme has been developed by dot-art, a Liverpool based arts organisation which has
            been supporting artists and developing innovative and creative visual arts projects and initiatives since 2005.</p>

            <p>We are now using our skills, experience and expertise to give the young people of the region access to an
            exciting new public platform for their creative output, and a taste of the way the art world works.</p>

            <p>dot-art is made up of two arms:</p>

            <p><strong>dot-art Ltd</strong> was founded in Liverpool in 2005 and specialises in affordable, high quality, 
            locally sourced art. We work with over 100 artists to provide an unrivalled choice of original art and limited 
            edition prints for home or business, as well as offering a range of complementary services including; commissions, 
            art rental, art consultancy, exhibition planning and implementation, bespoke framing, art valuation and restoration 
            and artist sourcing. See: <a href="http://www.dot-art.com">dot-art.com</a></p>
            
            <p>All our work supports our not-for profit arm <strong>dot-art Services CIC</strong>, which exists to support 
            North-West based visual artists, both emerging and established, through a range of services and opportunities 
            designed to help them develop their careers and gain exposure and promotion for their work, as well as delivering 
            a programme of adult art classes at a range of venues across Liverpool 
            (see: <a href="http://www.dot-art.co.uk/art-classes.php">dot-art.co.uk/art-classes</a>); 
            and dot-art Schools, our innovative inter school art competition, launched in 2012. 
            See: <a href="http://services.dot-art.com">services.dot-art.com</a>.</p>
            
           <!-- <p><i>This project was initially supported using public funding by the National Lottery through Arts Council England.</i></p>
            <img src="/images/ace-med-white.jpg">
            -->
            
        </div>
        
          <div class="tab-pane fade in" id="tab-supporters">   
            
            <div class="page-header">
            <h1><small>Project Partner</small></h1>
            </div>
           
            <div class="row">
            
            <a href="https://www.ljmu.ac.uk/" target="_blank">
                <img src="/images/logos/LJMU-web.jpg" class="span6" alt="Liverpool John Moores University" />
            </a>
             </div>
            
            <div class="page-header">
            <h1><small>Principal Sponsor 2016-17</small></h1>
            </div>
           
            <div class="row">
            
            <a href="https://www.tangleteezer.com/" target="_blank">
                <img src="/images/logos/TT-540.jpg" class="span6" alt="Tangle Teezer logo" />
            </a>
             </div>
             
            <div class="page-header"> 
            <h1><small>Supporters 2016-17</small></h1>
             </div> 
              
            <div class="row">
            
            <a href="http://liverpoolcityhalls.co.uk/st-georges-hall" target="_blank">
                <img src="/images/logos/SGH-270.jpg" class="span3" alt="St Georges Hall logo" />
            </a>
            <a href="http://www.morecrofts.co.uk/" target="_blank">
                <img src="/images/logos/morecrofts.jpg" class="span3" alt="Morecrofts logo" />
            </a>
           
         
               
                <a href="http://www.merseyrail.org/" target="_blank">
                <img src="/images/logos/merseyrail-270.JPG" class="span3" alt="Merseyrail logo" />
            </a>
            
              <a href="http://www.cassart.co.uk" target="_blank">
                <img src="/images/logos/cass-art-270.jpg" class="span3" alt="Cass Art logo" />
               </a> 
            
             </div>
                
        
                
                <p>.</p>  
                  
             <div class="page-header">
            <h1><small>Past Supporters</small></h1>
            </div>
            
            <div class="row">
                   <a href="http://www.bigpartnership.co.uk" target="_blank">
                <img src="/images/logos/big-270.jpg" class="span3" alt="The Big Partnership logo" />
               </a>   
                  
                  <a href="http://www.renniesartsandcrafts.co.uk/" target="_blank">
                <img src="/images/logos/Rennies-270.jpg" class="span3" alt="Rennies logo" />
               </a>  
               
                <a href="http://www.albertdock.com/" target="_blank">
                <img src="/images/logos/Albert-Dock-Logo-270.jpg" class="span3" alt="Albert Dock logo" />
               </a>  
               
                
            <a href="http://www.artscouncil.org.uk/" target="_blank">
                <img src="/images/logos/ace-270.jpg" class="span3" alt="Arts Council England logo" />
               </a>
                  
           
                  </div>

            <div class="row">
            
            <a href="http://www.davidmrobinson.co.uk/" target="_blank">
                <img src="/images/logos/DMR-logo.jpg" class="span3" alt="David M Robinson logo" />
            </a>
            
            <a href="http://www.liverpoolmuseums.org.uk/walker/" target="_blank">
                <img src="/images/logos/Walker-270.jpg" class="span3" alt="Walker Art Gallery logo" />
            </a>
            
             <a href="http://www.cassellmoore.com/" target="_blank">
                <img src="/images/logos/Cassell-Moore-web.jpg" class="span3" alt="Cassell Moore logo" />
            </a>
                
                <a href="http://citycentralbid.com/" target="_blank">
                <img src="/images/logos/city-central-bid-270.jpg" class="span3" alt="City Central Bid logo" />
            </a> 
                

            
          </div>
          
           <div class="row">
        
                
            
          <a href="http://www.cfmerseyside.org.uk/index.php?p=145" target="_blank">
                <img src="/images/logos/L1-Foundation-270.jpg" class="span3" alt="Liverpool One Foundation logo" />
            </a>
            
                 <a href="http://www.cfmerseyside.org.uk/" target="_blank">
                <img src="/images/logos/CFM-270.jpg" class="span3" alt="Community Foundation for Merseyside logo" />
            </a>
                 <a href="http://www.rathbones.co.uk/" target="_blank">
                <img src="/images/logos/rathbones-270.jpg" class="span3" alt="Rathbones logo" />
            </a>
            
          </div>
          </div>
          
          
   <!--     
        <div class="tab-pane fade in" id="tab-partners">
            <h2>Partners</h2>   

           <div class="row">
            <a href="http://liverpool.gov.uk/">
                <img src="/images/logos/lcc-270.jpg" class="span3" alt="Liverpool City Council logo" />
            </a>
               <a href="http://www.liverpoolchamber.org.uk/">
                <img src="/images/logos/chamber-270.jpg" class="span3" alt="Liverpool and Sefton Chamber of Commerce logo" />
            </a>
              <a href="http://www.curiousminds.org.uk/">
                <img src="/images/logos/curious-minds-270.jpg" class="span3" alt="Curious Minds logo" />
            </a>  
            <a href="http://www.as-creatives.com/">
                <img src="/images/logos/as-creatives-270.jpg" class="span3" alt="As Creatives logo" />
            </a>
              </div>
                 <div class="row">
             <a href="http://www.ifb2014.com/">
                <img src="/images/logos/ifb-270.jpg" class="span3" alt="International Festival for Business logo" />
            </a> 
              <a href="http://www.ljmu.ac.uk/" >
                <img src="/images/logos/ljmu-270.jpg" class="span3" alt="Liverpool John Moores University logo" />
            </a>

              <a href="http://www.artsaward.org.uk/site/?id=1763/">
                <img src="/images/logos/arts-award-270.jpg" class="span3" alt="Arts Award Supporter logo" />
            </a>
              <a href="http://www.sthelens.gov.uk/">
                <img src="/images/logos/st-helens-council-270.jpg" class="span3" alt="St Helens Council logo" />
            </a>
            </div>
            
            -->
            
        </div>
        
    </div>
    
</div>
</div>
</div>

</div>
