<?php
   $this->headTitle('What?');
   $this->headMeta()->appendName('description', 'dot-art Schools is an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<script type="text/javascript">twttr.conversion.trackPid('nu3ux', { tw_sale_amount: 0, tw_order_quantity: 0 });</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
</noscript>


<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">What?</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">What? <span class="divider">/</span></li>
  <li class="active">Programme</li>
</ul>

<div class="row">
<div class="span12">
         
            <div class="row row-entry">

            <div class="span4">
            <img src="/images/2019-Exhibition/2.jpg" title="dot-art Schools Exhibition 2019" alt="dot-art Schools Exhibition 2019"/>
            </div>
            
            <div class="span4">
            <img src="/images/2019-Exhibition/6.jpg" title="dot-art Schools Exhibition 2019" alt="dot-art Schools Exhibition 2019"/>
            </div>
            
            <div class="span4">
            <img src="/images/2019-Exhibition/4.jpg" title="dot-art Schools Exhibition 2019" alt="dot-art Schools Exhibition 2019"/>
            </div>
            </div>
            

            <h2>Sign Up</h2>
            
            <p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Sign-Up-Form 2019-20.pdf">Download the Sign Up Form as PDF.</a></p>
            <p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Sign-Up-Form 2019-20.docx">Download the Sign Up Form as Word Doc.</a></p>
            
            <p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet-web.pdf">Download the Teachers Information Leaflet</a></p>

   
            
     <!--        
            <p>**The deadline for entering dot-art Schools 2016-17 has now passed. If you are interested in taking part next academic year, please sign up to
            our <a href="http://schools.dot-art.com/contact">SCHOOLS MAILING LIST</a>**</p>

     -->        
            
            <h2>The Programme</h2>
    
            <p>dot-art Schools is an <strong>interactive, online, inter-school, art competition</strong>, taking part on an annual basis and
            culminating in an exhibition. Open to primary <strong>(year 5)</strong> and secondary 
            <strong>(year 9)</strong> schools in the <strong>Liverpool
            City Region.</strong>
            It is designed to nurture talent, raise ambition, and take art out of the classroom and into the
            real world. With the current threats to creative subjects on the national curriculum, dot-art Schools offers a
            way of keeping young people engaged with the arts, allows them to see a creative career path, and
            encourages them to attend exhibitions and engage with culture, outside of school.</p>
            
            <h2>How It Works</h2>
            
            <p><ul>
            <li><b>September to December</b> - Schools sign up to participate in dot-art Schools.</li>
              <li><b>February</b> - Schools submit photographs of students’ artworks by half term. 
              Competition entries are added to the school’s portfolio page on the dot-art Schools website. </li>
               <li><b>March</b> - Judging panel of respected arts professionals shortlist the top 3 entries from each school</li>
                <li><b>April</b> – The public vote online for their favourite shortlisted entry. 
                The entry with most votes from each school wins a place in the exhibition.</li>
                 <li><b>May / June</b> - Schools frame and deliver their winning entry ready for exhibition. Guest judge selects overall winners and runners up at the exhibition and announces them at the prize giving ceremony. 
                 Students, families and teachers celebrate at exhibition preview. dot-art Schools Exhibition opens to the public.</li>
            </ul></p>
            
  

            
            
           
<!---            
            <h3>Secondary</h3>
            
            <p><strong>Overall winner</strong></p> 
            <ul>
            <li>A scholarship to <b>Liverpool John Moores University</b>, giving the student £1000 per year for 3 years towards course fees
            should they choose to study at the Arts Faculty. 
            (See: <a href="https://www.ljmu.ac.uk/about-us/faculties/faculty-of-arts-professional-and-social-studies">ljmu.ac.uk/faculty-of-arts</a>)</li>
            <li>Membership to <b>dot-art</b>, giving them a year's membership
            to dot-art's network, allowing them to showcase and sell their work alongside professional artists. 
            (See: <a href="http://dot-art.co.uk/artist/">dot-art.co.uk/artist/</a>)</li>
            <li>Tickets to see the latest exhibition at <b>Tate Liverpool</b>.</li> 
            <li><b>Cass Art</b> special goody bag of art materials.</li>
            <li>£50 worth of vouchers to spend at <b>Rennies</b> Art Supplies.</li>
           
           <li><strong>FOR THE WINNING SCHOOL</strong> - &pound250 worth of vouchers to spend at <b>Cass Art</b>.</li>
            <li><strong>FOR THE WINNING SCHOOL</strong> - <b>Creative Careers talk</b> from Professor Caroline Wilkinson
            Director of the School of Art & Design at LJMU.</li>
            <li><strong>FOR THE WINNING SCHOOL</strong> - Schools will be invited for free hands-on Today at Apple sessions at Apple Liverpool. 
            During the sessions, participants will learn how to create digital artworks.</b>.</li>
            </ul>
            
            <p><strong>Runners Up x 2</strong></p> 
            <ul>
            <li><b>Cass Art</b> special goody bag of art materials.</li>
            <li>Tickets to see the latest exhibtion at <b>Tate Liverpool</b></li> 
            
           
            </ul>
            
            <h3>Primary</h3>
            
            <p><strong>Overall winner</strong></p> 
            <ul>
            <li><b>Cass Art</b> special goody bag of art materials.</li>
            <li>Four tickets for Meredith Wilson’s Miracle on 34th Street at the <b>Liverpool Playhouse Theatre</b></li>
            <li>Family meal for 4 at YeeRah restaurant, <b>Liverpool One</b></li> 
            <li>Mug featuring your art work from <b>Cauliflower</b></li>
            <li>£50 worth of vouchers to spend at <b>Rennies</b> Art Supplies.</li>
            
           <li><strong>FOR THE WINNING SCHOOL</strong>- &pound250 worth of vouchers to spend at <b>Cass Art</b>.</li>
            <li><strong>FOR THE WINNING SCHOOL</strong> - &pound250 voucher for playground equipment from <b>Playdale Playgrounds</b>.</li>
              <li><strong>FOR THE WINNING SCHOOL</strong> - Schools will be invited for free hands-on Today at Apple sessions at Apple Liverpool. 
            During the sessions, participants will learn how to create digital artworks.</b></li>
            </ul>
            
            <p><strong>Runners Up x 2</strong></p> 
            <ul>
            <li><b>Cass Art</b> special goody bag of art materials.</li>
           <li>Mug featuring your art work from <b>Cauliflower</b></li> 
           
            
            </ul>
            
-->
             <h2>Prizes</h2>
             
            <p>Prizes include membership to dot-art (for the overall secondary winner) plus vouchers for art materials
            and exhibition entry for both age groups. Further details to be announced.</p>            
            
            <p>All winning artists (1 from each partipating school) will also receive a <strong>Cass Art</strong> goody bag.</p>
            <p>All shortlisted artists (3 from each partipating school) will be awarded <strong>certificates.</strong></p>
            <p>.</p>
            
     
     <div class="span12">
                
     <p align="center"> <iframe width="100%" height="100%" src="https://www.youtube.com/embed/sg-IpeGO1jg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>
           
      </div>  
      
      <p>.</p>
            
      
      <h2>10 Reasons to Take Part</h2>  
      
      <blockquote>   
       <ol>
       <li>Contributes to a <b>broad and balanced curriculum</b></li>
       <li>Helps build pupils’ <b>cultural capital</b> (included in the new Education Inspection Framework)</li>
       <li>Raises the school’s <b>profile</b> and shows the school’s commitment to creative education</li>
       <li>Fantastic opportunity to <b>showcase</b> your students artwork outside school</li>
       <li><b>Compare standards</b> of artwork with other schools across the region, online and in a gallery setting.</li>
       <li>Improve students’ <b>confidence</b> in their own ability and give a real sense of pride</li>
       <li>Great way to engage student’s <b>families</b> through the public vote, exhibition and prize giving ceremony.</li>
       <li>Demonstrate the <b>quality of artwork</b> produced to students’ families and the wider community</li>
       <li>Support your <b>Artsmark</b> journey and help meet <b>OFSTED</b> and National Curriculum attainment targets</li>
       <li>Increase pupil’s self-esteem, particularly important with the growing <b>mental health crisis</b> facing young people</li>
       </ol>
       </blockquote>
     
         
         
           <h2>Liverpool LCEP</h2>  
        
        <p>dot-art Schools is part of the <b>Liverpool Cultural Education Partnership (LCEP)</b>. This was set up to increase opportunities 
        for children and young people across our region to take part in quality art and cultural experiences. The LCEP has developed 
        <a href="https://www.culturepool.org/">Culturepool.org</a> where you can search for cultural education resources, activities and 
        experiences for children and young people and find out more about the work of the LCEP.</p>
        
        <p>.</p>  
<!---       
        
            <p>This annual programme will encourage healthy competition between students and schools, as well
            as driving traffic to the site and therefore increasing the audience for the students' work and
            the profile of the school. The final exhibition will provide a wonderful opportunity for
            the successful students to show their work in a public setting and a fantastic way of celebrating 
            the art work created and the school's commitment to arts education, demonstrating the quality of art produced to parents, 
            families, local authorities and the wider community. Finally the programme can help
            participating schools meet many of the KS2 and 3 <strong>National Curriculum</strong> requirements for Art and
            Design, the criteria outlined in the <strong>OFSTED</strong> evaluation framework, as well as providing a
            valuable tool for schools working towards <strong>Artsmark</strong> status.</p>
            <p>.</p>
            
            <blockquote>
                <p>Pupils benefited greatly from the feedback received when their work was shared locally or more widely...</p>
                <p>Schools should... build sustained partnerships with art galleries and creative practitioners.</p>
                <p>Pupils who met with inspectors reported consistently the motivational impact of seeing their own work displayed professionally and publicly...</p>
                <p>The public exhibition of students' work was highly effective in strengthening links between schools and the local community, including diverse community groups, different generations and those living in contrasting socio-economic circumstances.</p>
                <small>Extracts from: Ofsted Report - Making a mark: art, craft and design education, 2008/11</small>
            </blockquote>
            
-->
        
  <div class="row row-entry">

            <div class="span4">
            <img src="/images/2019-Exhibition/9.jpg" title="dot-art Schools Exhibition 2019" alt="dot-art Schools Exhibition 2019"/>
            </div>
            
            <div class="span4">
            <img src="/images/2019-Exhibition/1.jpg" title="dot-art Schools Exhibition 2019" alt="dot-art Schools Exhibition 2019"/>
            </div>
            
            <div class="span4">
            <img src="/images/2019-Exhibition/7.jpg" title="dot-art Schools Exhibition 2019" alt="dot-art Schools Exhibition 2019"/>
            </div>
            </div>       
       
       
     
  </div>
              
        
    </div>
    
</div>
</div>
</div>

</div>
