<?php
   $this->headTitle('Information for Teachers?');
   $this->headMeta()->appendName('description', 'dot-art Schools is an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
   $this->headScript()->appendFile('/scripts/bootstrap-transition.js', 'text/javascript');
   $this->headScript()->appendFile('/scripts/bootstrap-tab.js', 'text/javascript');
      
?>

<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<script type="text/javascript">twttr.conversion.trackPid('nu3ux', { tw_sale_amount: 0, tw_order_quantity: 0 });</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu3ux&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
</noscript>


<div class="container lowered">

<div class="jumbotron what">
<h1 class="what">What?</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">What? <span class="divider">/</span></li>
  <li class="active">Information for Teachers</li>
</ul>

<div class="row">
<div class="span12">
         
        
            
          <p><a href="https://eu.jotform.com/dotart/sign-up-2020-21">COMPLETE THE SIGN UP FORM HERE</a></p>
            
            <p><a href="http://schools.dot-art.com/docs/dot-art-Schools-Leaflet-2020-21.pdf">Download the Teachers Information Leaflet</a></p>

              
            <h2>Information for Teachers</h2>
            
            <p><b>What will I have to do?<a href="http://schools.dot-art.com/docs/dot-art-Schools-Teachers-Info.pdf"> Download full details</a></b></p>
            
            <p>dot-art Schools was launched in 2012 and since then over 8000 children have taken part from almost 500 schools. 
            We have held exhibitions at the Domino Gallery, the Walker Art Gallery, St George Hall and the Liverpool School 
            of Art and Design and each year, three children from each participating school have been presented with a 
            certificate by the Lord Mayor of Liverpool. This wonderful prize giving ceremony, attended by families and staff, 
            which for the Liverpool programme now takes place in the LJMU Art School, is where the overall winners and 
            runner up are also announced. In response to feedback from schools, in September 2016 we changed the primary 
            age group from Year 6 to Year 5.</p>
            
            
             <p>In September 2016, thanks to our new partnership with LJMU, dot-art Schools also launched in 
             <a href="http://cheshire.schools.dot-art.com">Cheshire.</a>
             Over 20 primary and secondary schools in Cheshire West & Chester, Cheshire East and Warrington 
             took part in the competition each year from 2017 to 2019.</b></p>
              
              <p>In February 2018, dot-art Schools became an  
              <a href="http://www.artsmark.org.uk/artsmark-partnership-programme">Artsmark Partner,</a>.
             Artsmark is the creative quality standard for schools and education settings, awarded by Arts Council England, 
             recognising their commitment to high quality arts and cultural education. dot-art Schools is proud to be 
             supporting schools and education settings on their Artsmark journey, inspiring children and young people to 
             create, experience, and participate in great arts and culture.</p>  
              
              <p>Find out more about Artsmark at <a href="http://www.artsmark.org.uk.">artsmark.org.uk</a>
               and how we can support you on our <a href="../what/artsmark">Artsmark page</a>
               or call Carolyn on 0345 0176660.
              </p>  
              
                 <a href="http://www.artsmark.org.uk"><img src="/images/artsmark-partner-400.jpg" title="dot-art Schools Artsmark Partner" alt="dot-art Schools Artsmark Partner"/></a>

           <p>.</p>
           
            <p>Please download the document below for more details about how the programme works and the benefits it can
            bring:</p>
            <ul>
                <li><a href="http://schools.dot-art.com/docs/dot-art-Schools-Leaflet-2020-21.pdf" target="_blank">dot-art Schools Teachers Leaflet</a></li>
            </ul>
            
            <!---
            <li><a href="/docs/dot-art-Schools-KS2.pdf" target="_blank">dot-art Schools and the National Curriculum (year 6)</a></li>
                 <li><a href="/docs/dot-art-Schools-KS3.pdf" target="_blank">dot-art Schools and the National Curriculum (year 9)</a></li>
                <li><a href="/docs/dot-art-Schools-Ofsted.pdf" target="_blank">dot-art Schools and OFSTED</a></li>
                 <li><a href="/docs/dot-art-Schools-Arts-Award-Artsmark.pdf" target="_blank">dot-art Schools and Arts Award / Artsmark (overview)</a></li>
                <li><a href="/docs/dot-art-Schools-Artsmark-Detail.pdf" target="_blank">dot-art Schools and Artsmark (detail)</a></li>

                 <p>If you would like to take part, please complete and return the following Entry Form:</p>
            <ul>
                 <li><a href="http://schools.dot-art.com/docs/dot-art-Schools-Entry-Form.pdf">dot-art Schools 2016-17 Entry Form.</a></li>
            </ul>
           
            -->

            
            <p><strong>Key Facts 2018-19:</strong></p>
            <ul>
                <li>63 schools participated.</li>
                <li>1065 student art works displayed online.</li>
                <li>5270 votes cast.</li>
                <li>23000 unique visitors to the website.</li>
                 <li>63 student art works were showcased to the public in Liverpool School of Art and Design.</li>
                  <li>400 students, their families and teachers celebrated at prize giving ceremonies held in the Johnson Foundation auditorium at Liverpool School of Art & Design</li>
                  <li>480 visitors to the exhibition at Liverpool School of Art & Design</li>
                  <li>100000+ people viewed the exhibition hoarding on Castle Street, Liverpool city centre.</li>
            </ul
            
           
          
            
             <p><strong>Feedback from schools:</strong></p>
            <ul>
                <li>"We have just looked at the art work on the website, the work looks amazing. We are so happy with
                the quality of all of the schools submissions. You have done a great job!"</li>
                <li>"I have just looked at our page and I am very impressed with the whole project"</li>
                <li>"What a fantastic event!"</li>
                <li>"It has been a long time since we have had something of this calibre in the city to promote and
                celebrate the work of our young artists"</li>
            </ul>
            
             <p><strong>Feedback from exhibition visitors:</strong></p>
            <ul>
                <li>"What a fantastic level of skill from such talented young people"</li>
                <li>"What talented youth we have in Liverpool, so impressed with all the artwork presented"</li>
                <li>"A lovely exhibition with some excellent work on display, hope it encourages many of the exhibitors
                to become artists of the future"</li>
                <li>"I didn't realise the work was all by people under 15! Rather inspiring"</li>
            </ul>
   
   <!--         
             <p><strong>Key Dates 2017-18:</strong></p>
            <ul>
                <li>September 2018 - School recruitment for 2018-19 programme begins.</li>
                <li>December 2018 - Deadline for schools to sign up.</li>
                <li>February 2019 - Deadline for schools to submit work for competition.</li>
                <li>April 2019 - Online voting period.</li>
                <li>June 2019 - Prize Giving Ceremony.</li>
                 <li>June 2019 - Exhibition of winning works.</li>
            </ul>
            
-->            
            
        </div>
        
     
    </div>
    
</div>
</div>
</div>

</div>

