<?
   $this->headTitle('Exhibition');
   $this->headMeta()->appendName('description', 'Details of the annual exhibition which is the culmination of dot-art Schools, an interactive, inter school, online art competition.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Exhibition</h1>
</div>

<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Exhibition <span class="divider">/</span></li>
  <li class="active">2015</li>
</ul>

<div class="row">

<div class="span12">
<h3>dot-art Schools Exhibition 2015</h3>
<p>The dot-art Schools Exhibition 2015 will take place at St George's Hall from the 5th to the 20th of June, and will showcase
the winnning entries from each of our participating schools.</p>

</div>

</div>

</div>
