<?
   $this->headTitle('Exhibition');
   $this->headMeta()->appendName('description', 'Details of the annual exhibition which is the culmination of dot-art Schools, an interactive, inter school, online art competition.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Exhibition</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Exhibition <span class="divider">/</span></li>
  <li class="active">2014</li>
</ul>

<div class="row">

<div class="span12">
<h3>dot-art Schools Exhibition 2014</h3>
<p>17th May - 8th June, Walker Art Gallery, Liverpool</p>

<p>Following a judges' shortlist and an online public vote, the 2014 exhibition showcased the winning work from each participating school. 
The overall winners of the 2014 dot-art Schools Competition were announced at a prize-giving ceremony on 16th May, 
where the top three students from each of the participating schools were 
presented with a certificate by the Lord Mayor, Councillor Gary Millar and the seven overall winners and runners up received prizes.</p>

<p><b>Lottie Hulse</b> from <b>St.Hildas CE High School</b> won the Year 9 award for her pen and ink drawing "Heat".<br></p>

<p><b>Daniel Canning</b> from <b>Christian Fellowship Middle School</b> won the Year 6 award for his colourful self-portrait.<br></p>

<p>A Highly Commended Award was given to <b>Kristy Vidamour</b> of <b>Range High School</b> for her piece "The Last of the Tribal Men".<br></p>

<p>Runners Up Awards in the secondary category were presented to <b>Leigha Slevin</b> from <b>St Augustine of Cantebury High School</b> 
and <b>Erin Ball</b> of <b>Holly Lodge Girls School</b>.</p>

<p>In the primary category Runners Up Awards were presented to <b>Holly A</b> of <b>St Michael and All Angels Primary School</b> and 
<b>Tilly Rogan</b> of <b>Arnot St Mary''s Primary School</b>.</p>

<p>All the prize winners were awarded vouchers to spend at Rennies Arts and Crafts, tickets to the Tate's Mondrian show and 
a selection of art books from the Walker Art Gallery. In addition, as overall winner, Lottie received a scholarship to 
dot-art, giving her a year's membership to 
<a href="http://services.dot-art.com/"target="_blank">dot-art's network,</a> allowing her to showcase and sell her work alongside 
professional artists.</p>

<p>See the <a href="http://www.liverpoolmuseums.org.uk/walker/events/displayevent.aspx?EventID=16763"
	target="_blank">Walker website</a> for more details.</p>   
</div>

</div>



<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-01.jpg" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-02.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-03.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-04.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-05.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-06.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-07.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-08.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-09.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-10.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-11.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-12.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>



<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-13.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-14.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-15.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>




<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-16.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-17.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-18.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>


<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-19.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-20.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-21.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>



<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-22.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>


<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-23.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-24.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>


<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-25.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-26.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-27.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>



<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-28.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-29.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-30.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>


<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-31.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-32.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>


<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-33.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>



<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-34.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-35.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>


<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-36.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>



<div class="row row-entry">


<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-37.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-38.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-39.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>


<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-40.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-41.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-42.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>


<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-43.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-44.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-45.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-46.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-47.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-48.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-49.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-50.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-51.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-52.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-53.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-54.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-55.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-56.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-57.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-58.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-59.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-60.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-61.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-62.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-63.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-64.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-65.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-66.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-67.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-68.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-69.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-70.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-71.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-72.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-73.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-74.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-75.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-76.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-77.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-78.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-79.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-80.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-81.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-82.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-83.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-84.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-85.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-86.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-87.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-88.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-89.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-90.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-91.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-92.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-93.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2014-Exhibition/dot-art-Schools-14-94.jpg" title="dot-art Schools Exhibition 2014" alt="dot-art Schools Exhibition 2014"/>
</div>

</div>




<div class="row">

<div class="span6">
<img src="/images/dot-art-poster-web.jpg" title="dot-art Schools exhibition flyer, front" alt="dot-art Schools exhibition flyer, front"/>
</div>

<div class="span6">
<img src="/images/dot-art-leaflet-web.jpg" title="dot-art Schools exhibition flyer, back" alt="dot-art Schools exhibition flyer, back"/>
</div>

</div>

</div>
