<?
   $this->headTitle('Exhibition');
   $this->headMeta()->appendName('description', 'Details of the annual exhibition which is the culmination of dot-art Schools, an interactive, inter school, online art competition.');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Exhibition</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Exhibition <span class="divider">/</span></li>
  <li class="active">2013</li>
</ul>

<div class="row">

<div class="span12">
<h3>dot-art Schools Exhibition 2013</h3>
<p>11th-20th July, Domino Gallery, Liverpool</p>
<p>Following the results of an online public vote, this exhibition showcased the top three works from each of the schools 
who participated in the inaugural year of the programme. The winners of the 2013 dot-art Schools Competition were announced 
at a prize-giving ceremony at the Domino Gallery in Liverpool on 10th July 2013, where as well as the overall winners, 
the top three students from each of the participating schools were all presented with a certificate by the Lord Mayor, 
Councillor Gary Millar.</p> 

<p>The two <b>runners-up</b> were <b>Isobel Shore</b> (picture 2) from <b>Gateacre School</b> and <b>Jessie Lau</b> (picture 3) 
from <b>The Blue Coat School</b>, 
who both won exclusive ticket's to see Tate Liverpool's Chagall Exhibition when the gallery is closed to the public.</p>

<p>The <b>overall first prize</b> was awarded to <b>James Murphy</b> (picture 1), a year 9 pupil from <b>St Margaret’s Church of England Academy</b>. 
As well as tickets to the Chagall show, he also received a scholarship to dot-art, giving him a year's membership 
to dot-art's network, allowing him to showcase and sell his work alongside professional artists.</p>

<p>Browse the 2013 winners in our <a href="http://schools.dot-art.com/archive/entries/year/2013">Archive.</a></p>
</div>

</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-Winner.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-44.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-43.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-48.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-47.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-46.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-45.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-50.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-49.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>

<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-41.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-34.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-26.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>



<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-39.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-38.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-37.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>




<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-33.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-32.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-31.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>


<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-30.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-29.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-27.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>



<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-28.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>


<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-25.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-22.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>


<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-21.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-20.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-19.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>



<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-18.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-17.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-16.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>


<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-15.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-06.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>


<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-13.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>



<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-12.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-07.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>


<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-10.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>



<div class="row row-entry">


<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-02.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-01.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-04.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>


<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-36.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-35.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-23.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>


<div class="row row-entry">

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-09.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-05.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>

<div class="span4">
<img src="/images/2013-Exhibition/dot-art-Schools-13-11.JPG" title="dot-art Schools Exhibition 2013" alt="dot-art Schools Exhibition 2013"/>
</div>
</div>


 
<div class="row row-entry">

<div class="span6">
<img src="/images/dot-art-Schools-Exhibition-Flyer-Front.jpg" title="dot-art Schools Exhibition Flyer" alt="dot-art Schools Exhibition Flyer"/>
</div>

<div class="span6">
<img src="/images/dot-art-Schools-Exhibition-Flyer-back.jpg" title="dot-art Schools Exhibition Flyer" alt="dot-art Schools Exhibition Flyer"/>
</div>
</div>

</div>
