DELETE FROM judging;

INSERT INTO judging (school, title, artist) VALUES ('Acton Academy', 'Tahlia''s great wave', 'Tahlia Buckley');
INSERT INTO judging (school, title, artist) VALUES ('Acton Academy', 'Lily-Mai''s great wave', 'Lily-Mai Welch');
INSERT INTO judging (school, title, artist) VALUES ('Acton Academy', 'Lola''s Great Wave', 'Lola Hilton');
INSERT INTO judging (school, title, artist) VALUES ('Archers Brook SEN School', 'Running away', 'Cody Broster-Johnston');
INSERT INTO judging (school, title, artist) VALUES ('Archers Brook SEN School', 'The Dark stormy night', 'Kaden Wright');
INSERT INTO judging (school, title, artist) VALUES ('Archers Brook SEN School', 'The wolf', 'Freddie Morris');
INSERT INTO judging (school, title, artist) VALUES ('Barnton Primary School', 'Collage 10', 'Nathan Buzzard');
INSERT INTO judging (school, title, artist) VALUES ('Barnton Primary School', 'Collage 4', 'Keegan Hill');
INSERT INTO judging (school, title, artist) VALUES ('Barnton Primary School', 'Collage 1', 'Tayo Bilton');
INSERT INTO judging (school, title, artist) VALUES ('Bridgewater High School', 'Feminism', 'Lucy Rothwell');
INSERT INTO judging (school, title, artist) VALUES ('Bridgewater High School', 'Music 3', 'Nancy Bligh');
INSERT INTO judging (school, title, artist) VALUES ('Bridgewater High School', 'Martin Luther King', 'Ewan Schooler');
INSERT INTO judging (school, title, artist) VALUES ('Culcheth High School', 'Mexican day of the dead 1', 'Lauren Chappel');
INSERT INTO judging (school, title, artist) VALUES ('Culcheth High School', 'Mexican day of the dead 3', 'Tegan Fadil');
INSERT INTO judging (school, title, artist) VALUES ('Culcheth High School', 'Mexican day of the dead 21', 'Isabelle Whitford');
INSERT INTO judging (school, title, artist) VALUES ('Fallibroome Academy', 'Sunset in the Peak District', 'Georgia Mayer Holt');
INSERT INTO judging (school, title, artist) VALUES ('Fallibroome Academy', 'London sky', 'Caera Hannah');
INSERT INTO judging (school, title, artist) VALUES ('Fallibroome Academy', 'Lost paradise', 'Madison Bownass');
INSERT INTO judging (school, title, artist) VALUES ('Grange Community Primary', 'Tree Top', 'Kai Daniells');
INSERT INTO judging (school, title, artist) VALUES ('Grange Community Primary', 'Rainbow Winsford Flashes', 'Sian Buckley');
INSERT INTO judging (school, title, artist) VALUES ('Grange Community Primary', 'The Rainbowed Birds', 'Dilara Ozkara');
INSERT INTO judging (school, title, artist) VALUES ('Green Lane Special Primary School', 'Untitled 9', 'Joshua P');
INSERT INTO judging (school, title, artist) VALUES ('Green Lane Special Primary School', 'Untitled 7', 'Ethan H');
INSERT INTO judging (school, title, artist) VALUES ('Green Lane Special Primary School', 'Untitled 6', 'Ethan G');
INSERT INTO judging (school, title, artist) VALUES ('Green Lane Special School', 'Untitled 5', 'Connor P');
INSERT INTO judging (school, title, artist) VALUES ('Green Lane Special School', 'Untitled 10', 'Kaeden B');
INSERT INTO judging (school, title, artist) VALUES ('Green Lane Special School', 'Untitled 2', 'Ben M');
INSERT INTO judging (school, title, artist) VALUES ('Kelsall Primary School', 'Distant Hills 3', 'Mia Horne');
INSERT INTO judging (school, title, artist) VALUES ('Kelsall Primary School', 'Landscape 1', 'Penelope Harrison');
INSERT INTO judging (school, title, artist) VALUES ('Kelsall Primary School', 'Landscape 3', 'Samuel Johnson');
INSERT INTO judging (school, title, artist) VALUES ('Neston High School', 'Wendy Peekaboo', 'Lean Eugenio');
INSERT INTO judging (school, title, artist) VALUES ('Neston High School', 'Fish Close-Up 3', 'Jess Kelly');
INSERT INTO judging (school, title, artist) VALUES ('Neston High School', 'Fish Close-Up 5', 'Aaran Edwards');
INSERT INTO judging (school, title, artist) VALUES ('Oaklands School SEN', 'Sunset 11', 'Josh F');
INSERT INTO judging (school, title, artist) VALUES ('Oaklands School SEN', 'Waves 2', 'Sam B');
INSERT INTO judging (school, title, artist) VALUES ('Oaklands School SEN', 'Sunset 6', 'Zoey A');
INSERT INTO judging (school, title, artist) VALUES ('Sir William Stanier School', '2', 'Paige Hunt');
INSERT INTO judging (school, title, artist) VALUES ('Sir William Stanier School', '4', 'Cody McEvoy');
INSERT INTO judging (school, title, artist) VALUES ('Sir William Stanier School', '5', 'Sophie Dickinson');
INSERT INTO judging (school, title, artist) VALUES ('The Catholic High School', 'Susan Davis Painting 1', 'Pranathi Tulasi');
INSERT INTO judging (school, title, artist) VALUES ('The Catholic High School', 'Bug Prints Drawings 1', 'Tina Perruzza');
INSERT INTO judging (school, title, artist) VALUES ('The Catholic High School', 'Clay Heads 3', 'Mathew McFadyen');
INSERT INTO judging (school, title, artist) VALUES ('The Firs School', 'Just Shoot', 'Freddie Lawson');
INSERT INTO judging (school, title, artist) VALUES ('The Firs School', 'Seaweed 2', 'Adam Railton');
INSERT INTO judging (school, title, artist) VALUES ('The Firs School', 'Waterlilies', 'Eve O''Keefe');
INSERT INTO judging (school, title, artist) VALUES ('The Queen''s Lower School', 'Blast Off 8', 'Lucy Mackay');
INSERT INTO judging (school, title, artist) VALUES ('The Queen''s Lower School', 'Blast Off 7', 'Gowrie Shetty');
INSERT INTO judging (school, title, artist) VALUES ('The Queen''s Lower School', 'Blast Off 16', 'Jenny Lobato- Jones');
INSERT INTO judging (school, title, artist) VALUES ('Upton by Chester High School', 'Skull', 'Faisal Aljemaiah');
INSERT INTO judging (school, title, artist) VALUES ('Upton by Chester High School', 'Architecture Layers', 'Vivien Szilagyi');
INSERT INTO judging (school, title, artist) VALUES ('Upton by Chester High School', 'Cherries', 'Nisa Hoque');
INSERT INTO judging (school, title, artist) VALUES ('Whitby High School', 'Quality Street 2', 'Megan Roscoe');
INSERT INTO judging (school, title, artist) VALUES ('Whitby High School', 'Renaissance 1', 'Ella Appleby');
INSERT INTO judging (school, title, artist) VALUES ('Whitby High School', 'Pineapple', 'Sophie Roberts');
INSERT INTO judging (school, title, artist) VALUES ('Woodlands Primary', 'Peacock Feathers 10', 'Lucy A');
INSERT INTO judging (school, title, artist) VALUES ('Woodlands Primary', 'Peacock Feathers 8', 'Anya A');
INSERT INTO judging (school, title, artist) VALUES ('Woodlands Primary', 'Peacock Feathers 9', 'Imogen C');


INSERT INTO judging (school, title, artist) VALUES ('Alsop High School', 'Goodbye Blue Sky', 'Kierra O''Connell');
INSERT INTO judging (school, title, artist) VALUES ('Alsop High School', 'Brighton Rock', 'Freddie Blackburn');
INSERT INTO judging (school, title, artist) VALUES ('Alsop High School', 'One of these days', 'Benjamin Thomas');
INSERT INTO judging (school, title, artist) VALUES ('Archbishop Beck', 'View thru a window 4', 'Dylan Donoghue');
INSERT INTO judging (school, title, artist) VALUES ('Archbishop Beck', 'View thru a window 12', 'Daniel Gillon');
INSERT INTO judging (school, title, artist) VALUES ('Archbishop Beck', 'View thru a window 13', 'Emily Plews');
INSERT INTO judging (school, title, artist) VALUES ('Bank View High School (SEN)', 'Portrait with watercolour', 'Anthony Owen');
INSERT INTO judging (school, title, artist) VALUES ('Bank View High School (SEN)', 'Blood sweat and tears', 'Bobby Baker');
INSERT INTO judging (school, title, artist) VALUES ('Bank View High School (SEN)', 'Read it and weep', 'Leighton Cooper');
INSERT INTO judging (school, title, artist) VALUES ('Barlows Primary', 'Untitled -7', 'Daisy Carter');
INSERT INTO judging (school, title, artist) VALUES ('Barlows Primary', 'Untitled -12', 'Louie Gillon');
INSERT INTO judging (school, title, artist) VALUES ('Barlows Primary', 'Untitled -3', 'Alfie Moyes');
INSERT INTO judging (school, title, artist) VALUES ('Bellerive FCJ Catholic College', 'Kids United', 'Paula Malinowska');
INSERT INTO judging (school, title, artist) VALUES ('Bellerive FCJ Catholic College', 'Butternut', 'Emily Morris');
INSERT INTO judging (school, title, artist) VALUES ('Bellerive FCJ Catholic College', 'B.I.G', 'Imara Rogers');
INSERT INTO judging (school, title, artist) VALUES ('Blackmoor Park Junior School', 'Mystery River', 'Heidi Cooke');
INSERT INTO judging (school, title, artist) VALUES ('Blackmoor Park Junior School', 'Untitled 2', 'Lucas McIntyre');
INSERT INTO judging (school, title, artist) VALUES ('Blackmoor Park Junior School', 'Night-swirl', 'Miles Barton');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen International School', 'Red line', 'Abbie Fitzpatrick');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen International School', 'Snowy Road', 'Daniel Rose');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen International School', 'City blend', 'Finnley Wade');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen Primary', 'The wonderful plantpot', 'Luke Hall');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen Primary', 'Monet''s garden', 'Elliot Miller');
INSERT INTO judging (school, title, artist) VALUES ('Broadgreen Primary', 'sunset', 'Oliver Gregson');
INSERT INTO judging (school, title, artist) VALUES ('Broughton Hall Catholic High', 'dog', 'Olivia Williams');
INSERT INTO judging (school, title, artist) VALUES ('Broughton Hall Catholic High', 'Collagraph Landscape 5', 'Macy Mitchell');
INSERT INTO judging (school, title, artist) VALUES ('Broughton Hall Catholic High', 'Untitled 1', 'Samantha Thomas');
INSERT INTO judging (school, title, artist) VALUES ('Childwall Abbey School (SEN)', 'House', 'Mercy Abiodun');
INSERT INTO judging (school, title, artist) VALUES ('Childwall Abbey School (SEN)', 'My Crazy Milkshake', 'Josie');
INSERT INTO judging (school, title, artist) VALUES ('Childwall Abbey School (SEN)', 'Grin', 'James Stoba');
INSERT INTO judging (school, title, artist) VALUES ('Eaves Primary School', 'The Rainforest Alive 15', 'Luke Hawksworth');
INSERT INTO judging (school, title, artist) VALUES ('Eaves Primary School', 'The Rainforest Alive 9', 'Rhys Davies');
INSERT INTO judging (school, title, artist) VALUES ('Eaves Primary School', 'The Rainforest Alive 11', 'Harrison Fair');
INSERT INTO judging (school, title, artist) VALUES ('Florence Melly Primary', 'The Football Field', 'Daniel Blackwel');
INSERT INTO judging (school, title, artist) VALUES ('Florence Melly Primary', 'Bluey', 'Joel Collett');
INSERT INTO judging (school, title, artist) VALUES ('Florence Melly Primary', 'The Evening Run', 'Isaac Baines');
INSERT INTO judging (school, title, artist) VALUES ('Gateacre School', 'Love', 'Emily Vandelt');
INSERT INTO judging (school, title, artist) VALUES ('Gateacre School', 'Read my lips', 'Jack Davison');
INSERT INTO judging (school, title, artist) VALUES ('Gateacre School', 'My favourite things', 'Caoimhe Quinn');
INSERT INTO judging (school, title, artist) VALUES ('Greenbank High School', 'Blue Dahlia', 'Amelia Harvey');
INSERT INTO judging (school, title, artist) VALUES ('Greenbank High School', 'Waves', 'Hope McCaffrey');
INSERT INTO judging (school, title, artist) VALUES ('Greenbank High School', 'London', 'Carmen Leach');
INSERT INTO judging (school, title, artist) VALUES ('Gwladys Street Primary', 'Space Odyssey 2', 'Sarah Goodwin');
INSERT INTO judging (school, title, artist) VALUES ('Gwladys Street Primary', 'Space Odyssey 18', 'Riley Navarro');
INSERT INTO judging (school, title, artist) VALUES ('Gwladys Street Primary', 'Space Odyssey 23', 'Sonny Murphy');
INSERT INTO judging (school, title, artist) VALUES ('Harmonize Academy', 'Reflections of a City', 'Tyreese McBingham');
INSERT INTO judging (school, title, artist) VALUES ('Harmonize Academy', 'The King of Dreams', 'Anthony Lawler');
INSERT INTO judging (school, title, artist) VALUES ('Harmonize Academy', 'The Cure', 'Lee Weston');
INSERT INTO judging (school, title, artist) VALUES ('Hilbre High School', 'Inverse Parrot', 'Joseph Salkeld');
INSERT INTO judging (school, title, artist) VALUES ('Hilbre High School', 'Paper Toucan', 'Monty Loughrey');
INSERT INTO judging (school, title, artist) VALUES ('Hilbre High School', 'Swans', 'Linxi Jian');
INSERT INTO judging (school, title, artist) VALUES ('Holy Family Catholic Primary School Cronton', 'Flora 2', 'Olivia Crowley');
INSERT INTO judging (school, title, artist) VALUES ('Holy Family Catholic Primary School Cronton', 'Flora 30', 'Jake Spencer');
INSERT INTO judging (school, title, artist) VALUES ('Holy Family Catholic Primary School Cronton', 'Flora 29', 'Francesca Firth');
INSERT INTO judging (school, title, artist) VALUES ('Holy Family High School', 'Maddi', 'Madison Clarke');
INSERT INTO judging (school, title, artist) VALUES ('Holy Family High School', 'Two Face', 'Tilly Withell');
INSERT INTO judging (school, title, artist) VALUES ('Holy Family High School', 'Reflection', 'Alex Tutty');
INSERT INTO judging (school, title, artist) VALUES ('Hope School', 'Callum', 'Callum Walls');
INSERT INTO judging (school, title, artist) VALUES ('Hope School', 'Tigee', 'Jack Robinson');

INSERT INTO judging (school, title, artist) VALUES ('Kings Leadership Academy Liverpool', 'Behind the Camera', 'Dalea Al Motlak');
INSERT INTO judging (school, title, artist) VALUES ('Kings Leadership Academy Liverpool', 'Salvador Brother', 'Raul Paun');
INSERT INTO judging (school, title, artist) VALUES ('Kings Leadership Academy Liverpool', 'Audrey rainbow thoughts', 'Angelica Kandiah');
INSERT INTO judging (school, title, artist) VALUES ('Knotty Ash Primary', 'Under Art', 'Connie Maddison');
INSERT INTO judging (school, title, artist) VALUES ('Knotty Ash Primary', 'the-dark-mysterious', 'Maisy Lafferty');
INSERT INTO judging (school, title, artist) VALUES ('Knotty Ash Primary', 'The other side', 'Ethan Robertson');
INSERT INTO judging (school, title, artist) VALUES ('Leamington Community Primary', 'Rainbow Beauty', 'Lexie Sweeney');
INSERT INTO judging (school, title, artist) VALUES ('Leamington Community Primary', 'Self Portrait', 'Gerard Clarke');
INSERT INTO judging (school, title, artist) VALUES ('Leamington Community Primary', 'White House', 'Eddie Asuquo');
INSERT INTO judging (school, title, artist) VALUES ('Liverpool College', 'John Lennon 3', 'Jasmine Kalirai');
INSERT INTO judging (school, title, artist) VALUES ('Liverpool College', 'Memories', 'Jay Mabrouk');
INSERT INTO judging (school, title, artist) VALUES ('Liverpool College', 'Paul O''Grady', 'Nicolaas Salmon');
INSERT INTO judging (school, title, artist) VALUES ('Maghull High School', 'Cells 3', 'Riley Maloney');
INSERT INTO judging (school, title, artist) VALUES ('Maghull High School', 'Cells 12', 'Emma Clayton');
INSERT INTO judging (school, title, artist) VALUES ('Maghull High School', 'Tower 5', 'Lois Fisher');
INSERT INTO judging (school, title, artist) VALUES ('Maricourt Catholic High School', 'Mononoke (Pretty Flower)', 'Millie Power');
INSERT INTO judging (school, title, artist) VALUES ('Maricourt Catholic High School', 'Acrylic Dreams', 'Luke Hallman');
INSERT INTO judging (school, title, artist) VALUES ('Maricourt Catholic High School', 'Serenity', 'Hannah Mulligan');
INSERT INTO judging (school, title, artist) VALUES ('Moorfield Primary', 'Portrait of Sophie 7', 'Thomas Snape');
INSERT INTO judging (school, title, artist) VALUES ('Moorfield Primary', 'Cello 2', 'Aaron Fitzpatrick');
INSERT INTO judging (school, title, artist) VALUES ('Moorfield Primary', 'Portrait of Sophie 2', 'William Slinn');
INSERT INTO judging (school, title, artist) VALUES ('Ormiston Bolingbroke Academy', 'Notre Dame', 'Molly McMaster');
INSERT INTO judging (school, title, artist) VALUES ('Ormiston Bolingbroke Academy', 'Florence Duomo', 'Gabrielle Sartorius');
INSERT INTO judging (school, title, artist) VALUES ('Ormiston Bolingbroke Academy', 'Norton Water Tower', 'Beth Burns');
INSERT INTO judging (school, title, artist) VALUES ('Peterhouse School', 'Ink & Water', 'Jordan Stafford ');
INSERT INTO judging (school, title, artist) VALUES ('Peterhouse School', 'Still Life Cat & Mouse', 'Sam McCarney');
INSERT INTO judging (school, title, artist) VALUES ('Peterhouse School', 'Aboriginal Fish', 'Jack Hall');
INSERT INTO judging (school, title, artist) VALUES ('Phoenix Primary School', 'Liverpool Skyline', 'Harry Wynne');
INSERT INTO judging (school, title, artist) VALUES ('Phoenix Primary School', 'A Rainforest', 'Demi-Leigh Bratby');
INSERT INTO judging (school, title, artist) VALUES ('Phoenix Primary School', 'Banyan Tree 3', 'Isabella Nkrumah Nuakoh');
INSERT INTO judging (school, title, artist) VALUES ('Prescot Primary', 'Space 9', 'Eva Ablewhite');
INSERT INTO judging (school, title, artist) VALUES ('Prescot Primary', 'Space 7', 'Harriet Kilshaw');
INSERT INTO judging (school, title, artist) VALUES ('Prescot Primary', 'Space 2', 'Ryan Macklin');
INSERT INTO judging (school, title, artist) VALUES ('Rainhill High School', 'Stormzy', 'Mohammed Omar');
INSERT INTO judging (school, title, artist) VALUES ('Rainhill High School', 'Altered Cityscapes', 'Liam Mcdonald');
INSERT INTO judging (school, title, artist) VALUES ('Rainhill High School', 'Paper Sculpture 3 (abstract light and dark)', 'Maisie Roberts');
INSERT INTO judging (school, title, artist) VALUES ('Range High School', 'Mount Bear', 'Alix Smith');
INSERT INTO judging (school, title, artist) VALUES ('Range High School', 'Lioness', 'Heather Mc Namara');
INSERT INTO judging (school, title, artist) VALUES ('Range High School', 'The woman', 'Harvind Sangha');
INSERT INTO judging (school, title, artist) VALUES ('Springwood Heath Primary School', 'Mayan Doily', 'Maisy Gray');
INSERT INTO judging (school, title, artist) VALUES ('Springwood Heath Primary School', 'Ancient plate', 'Joel Graham ');
INSERT INTO judging (school, title, artist) VALUES ('Springwood Heath Primary School', 'Polka Plate', 'Luca Banaru');
INSERT INTO judging (school, title, artist) VALUES ('St Anne''s Catholic Primary', 'My Liverpool 1', 'Tyra Fareweather');
INSERT INTO judging (school, title, artist) VALUES ('St Anne''s Catholic Primary', 'My Liverpool 3', 'Rozelin Karakas');
INSERT INTO judging (school, title, artist) VALUES ('St Anne''s Catholic Primary', 'The Reading Tree', 'Adam Sidimoussa');
INSERT INTO judging (school, title, artist) VALUES ('St Anne''s Stanley CoE Primary', 'The Beach', 'Annelyse Dunn');
INSERT INTO judging (school, title, artist) VALUES ('St Anne''s Stanley CoE Primary', 'Liverpool Bright Lights', 'Maysa Alasaly');
INSERT INTO judging (school, title, artist) VALUES ('St Anne''s Stanley CoE Primary', 'A City Awakens', 'Elizabeth Kenny');
INSERT INTO judging (school, title, artist) VALUES ('St Augustine of Canterbury Catholic High', 'Below The Void Poster', 'Conor Travis');
INSERT INTO judging (school, title, artist) VALUES ('St Augustine of Canterbury Catholic High', 'Polygonal Fericit', 'Gena Pantelimon');
INSERT INTO judging (school, title, artist) VALUES ('St Augustine of Canterbury Catholic High', 'Shells', 'Emily Martland');
INSERT INTO judging (school, title, artist) VALUES ('St Bedes Catholic Junior', 'Photo Day', 'Alex O''Connor');
INSERT INTO judging (school, title, artist) VALUES ('St Bedes Catholic Junior', 'Still Life ', 'Summer Draycott');
INSERT INTO judging (school, title, artist) VALUES ('St Bedes Catholic Junior', 'Oriental Garden', 'Rosie Ellis');
INSERT INTO judging (school, title, artist) VALUES ('St Chads Catholic & CofE High School', 'Jungle Foliage 14', 'Xavier Nelson');
INSERT INTO judging (school, title, artist) VALUES ('St Chads Catholic & CofE High School', 'Jungle Foliage 8', 'Hannah Hart-Coppin');
INSERT INTO judging (school, title, artist) VALUES ('St Chads Catholic & CofE High School', 'Jungle Foliage 3', 'Ashlei Costain');
INSERT INTO judging (school, title, artist) VALUES ('St Cuthberts Catholic Primary', 'Alex''s Liverpool Landmarks', 'Alexsander Cicslinski');
INSERT INTO judging (school, title, artist) VALUES ('St Cuthberts Catholic Primary', 'Halema''s Liverpool Landmarks', 'Halema Muthana');
INSERT INTO judging (school, title, artist) VALUES ('St Cuthberts Catholic Primary', 'Ben''s Liverpool Landmarks', 'Ben Newton');
INSERT INTO judging (school, title, artist) VALUES ('St Francis de Sales Catholic Junior School', 'Amphora Pot 2', 'Eva Lavelle');
INSERT INTO judging (school, title, artist) VALUES ('St Francis de Sales Catholic Junior School', 'Amphora Pot 3', 'Michael Phillips');
INSERT INTO judging (school, title, artist) VALUES ('St Francis de Sales Catholic Junior School', 'Oenochoe jug 2', 'Rachel Yalcin ');
INSERT INTO judging (school, title, artist) VALUES ('St Hildas CE High School', 'Little Sister', 'Sophie Little-Byrne');
INSERT INTO judging (school, title, artist) VALUES ('St Hildas CE High School', 'Portrait 3', 'Italia Kelly');
INSERT INTO judging (school, title, artist) VALUES ('St Hildas CE High School', 'Zentangle Eye 7', 'Leona Nnachi');
INSERT INTO judging (school, title, artist) VALUES ('St Julie''s Catholic High School', 'Bug 1', 'Libby Pendleton');
INSERT INTO judging (school, title, artist) VALUES ('St Julie''s Catholic High School', 'Bug 3', 'Alex Lowe');
INSERT INTO judging (school, title, artist) VALUES ('St Julie''s Catholic High School', 'Fruit tone', 'Chloe Spyrou');
INSERT INTO judging (school, title, artist) VALUES ('St Margarets Academy', 'Exploding head 5', 'Jacob Crummey');
INSERT INTO judging (school, title, artist) VALUES ('St Margarets Academy', 'My dog''s nose', 'Reece Valentine');
INSERT INTO judging (school, title, artist) VALUES ('St Margarets Academy', 'Lego figure 18', 'Harry Mayers');
INSERT INTO judging (school, title, artist) VALUES ('St Michael and All Angels Primary', 'Votes 4 Women', 'Ruby Kelly');
INSERT INTO judging (school, title, artist) VALUES ('St Michael and All Angels Primary', 'We can do it together!', 'Mia Banawich');
INSERT INTO judging (school, title, artist) VALUES ('St Michael and All Angels Primary', 'Girl Power!', 'Lola Edwards');
INSERT INTO judging (school, title, artist) VALUES ('St Michaels Catholic Primary', 'A face 6', 'Emily Gilmore');
INSERT INTO judging (school, title, artist) VALUES ('St Michaels Catholic Primary', 'A face 2', 'Aimee Burns');
INSERT INTO judging (school, title, artist) VALUES ('St Michaels Catholic Primary', 'A face 3', 'CHARLIE Beesley ');
INSERT INTO judging (school, title, artist) VALUES ('St Peter and St Pauls RC Aided Primary', 'Dome of home 1', 'Keira Blundell');
INSERT INTO judging (school, title, artist) VALUES ('St Peter and St Pauls RC Aided Primary', 'Dome of home 4', 'Daisy Backinsell');
INSERT INTO judging (school, title, artist) VALUES ('St Peter and St Pauls RC Aided Primary', 'Dome of home 13', 'Liam Kane');
INSERT INTO judging (school, title, artist) VALUES ('St Sebastians Catholic Primary', 'Dylann''s Liverpool skyline', 'Dylann Hughes');
INSERT INTO judging (school, title, artist) VALUES ('St Sebastians Catholic Primary', 'Luca''s Liverpool skyline ', 'Luca Dorkel');
INSERT INTO judging (school, title, artist) VALUES ('St Sebastians Catholic Primary', 'Nathan''s Liverpool skyline ', 'Nathan Lee');
INSERT INTO judging (school, title, artist) VALUES ('The Academy of Saint Nicholas', 'Architecture', 'Kiah Abbot');
INSERT INTO judging (school, title, artist) VALUES ('The Academy of Saint Nicholas', 'Door knocker 2', 'Chloe Lennox');
INSERT INTO judging (school, title, artist) VALUES ('The Academy of Saint Nicholas', 'Buildings', 'karolina Jurand');
INSERT INTO judging (school, title, artist) VALUES ('The Academy of St Francis of Assisi', 'Sunset', 'Melanie Valvuccio');
INSERT INTO judging (school, title, artist) VALUES ('The Academy of St Francis of Assisi', 'Decay', 'Tala Jebreen');
INSERT INTO judging (school, title, artist) VALUES ('The Academy of St Francis of Assisi', 'Rust ', 'Melissa Silva');
INSERT INTO judging (school, title, artist) VALUES ('The Heath School', 'Ice cream melt', 'Kyle Larvin');
INSERT INTO judging (school, title, artist) VALUES ('The Heath School', 'Apple core?', 'CHARLIE Steinmann');
INSERT INTO judging (school, title, artist) VALUES ('The Heath School', 'Kitchen sink cake', 'Estelle Smith');
INSERT INTO judging (school, title, artist) VALUES ('West Derby High School', 'Liverpool illustration 2', 'Thomas Ellis');
INSERT INTO judging (school, title, artist) VALUES ('West Derby High School', 'Art goes pop 4', 'Cameron Mercer');
INSERT INTO judging (school, title, artist) VALUES ('West Derby High School', 'Turn and face the changes 2', 'Niall Cullen');
INSERT INTO judging (school, title, artist) VALUES ('West Kirby School & College', 'City', 'Leon Butcher');
INSERT INTO judging (school, title, artist) VALUES ('West Kirby School & College', 'Church', 'Levi Williams');
INSERT INTO judging (school, title, artist) VALUES ('West Kirby School & College', 'Pigs', 'Freja Dickinson ');
INSERT INTO judging (school, title, artist) VALUES ('Windsor Primary School', 'Georges Seurat style landmark 2', 'Alicja Dolosz');
INSERT INTO judging (school, title, artist) VALUES ('Windsor Primary School', 'Liverpool cathedral ', 'Hanan Al-Qashtari');
INSERT INTO judging (school, title, artist) VALUES ('Windsor Primary School', 'Eiffel Tower', 'Ahmed Medni');
INSERT INTO judging (school, title, artist) VALUES ('Woodchurch High School', 'Little drop', 'Charlotte Kane');
INSERT INTO judging (school, title, artist) VALUES ('Woodchurch High School', 'Coachella', 'Lewis Fryer');
INSERT INTO judging (school, title, artist) VALUES ('Woodchurch High School', 'Psychedelic', 'Amy Wayne');

UPDATE judging j
  JOIN entry e ON j.`artist` = e.`artist` AND j.`title` = e.`title`
   SET j.`entry_id` = e.`entry_id`;

UPDATE entry e
  JOIN judging j ON j.entry_id = e.entry_id
   SET e.`rank` = 1;

