INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "Blackmoor Park Junior School", "blackmoor-park-junior", "Blackmoor Park Junior School encourages a lifelong enjoyment of learning which leads to personal growth and fulfilment. Our Mission Statement, 'By Living Together, Learning Together and Playing Together We Will All Achieve' reflects this and forms the basis of all our work in the school. Our Year 5 children were encouraged to produce artwork which explored their individually chosen themes, compositions and techniques. They employed a range of different materials including pastel, paint, collage and mixed-media.", "http://www.blackmoorpark.com", "blackmoor-park-junior-logo.jpg", "blackmoor-park-junior");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "Eaves Primary School", "eaves-primary", "At Eaves, we highly value the teaching of Art and Design. As a school, we are currently working towards gaining Artsmark status and our pupils have thoroughly enjoyed exploring a range of new skills and techniques. Year 5 have been learning all about Rainforests and have loved the process of creating their own mixed media artwork. From creating interesting paper to use as collage for their animal skins to learning how to use technical drawing and use of colour though the animals eyes and features, Year 5 have worked hard to really produce some beautiful pieces. They have also explored ways in which to use paint to add details for their chosen animal.", "http://www.eaves.st-helens.sch.uk/", "eaves-primary-logo.jpg", "eaves-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 1, "Hilbre High School", "hilbre-high", "Hilbre High School is a mixed ability school in West Kirby. The Art department believe in students expressing themselves individually through a range of media and techniques-with an emphasis on drawing and colour. In the past, we ran Fine Art and Graphic Design courses so have a very illustrative house style that also accommodates anything from digital responses to animation to traditional painting. In our first year running a 3 years GCSE, students have sampled all the titles within the current Art, Craft & Design GCSE. The work represented is a response to their 'pre course-work' studies on the themes of 'Flight' and 'Natural Form'", "http://www.hilbre.wirral.sch.uk/", "hilbre-high-logo.jpg", "hilbre-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "Holy Family Catholic Primary School", "holy-family-cronton-primary", "Holy Family is a small primary school located in Knowsley. Here at Holy Family we strive to ensure that children experience an immersive curriculum with focus days to support children to develop and understand key skills within the Arts. Our Year 5 students have been exploring themes of flora as part of their studies and have used techniques of press-print, painting and collage to create layers and textures within their work.", "http://www.holyfamilycronton.co.uk", "holy-family-primary-logo.jpg", "holy-family-cronton-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "Moorfield Primary", "moorfield-primary", "Moorfield is a busy, exciting primary school in Widnes. We are all passionate about growing children's confidence, building on their strengths, and supporting them in becoming extraordinary people. We want all children to enjoy their learning experience whilst recognising the importance of working hard. Children are given stimulating learning opportunities that utilise their reading, writing and maths skills in a cross-curricular way that develops their wider work place skills. Arts, humanities, science and sports are all highly valued as we promote a love and a joy of learning.", "https://www.moorfieldprimary.co.uk/", "moorfield-primary-logo.jpg", "moorfield-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "Peterhouse School", "peterhouse-school", "As a specialist school for pupils with Autism we use The Arts as a motivator to enable our pupils to increase their confidence and strive for independence as well as being a tool to aid in the development of communication and self-expression. We have high expectations and focus on a “can do” approach which highlights what pupils can do rather than what they find difficult. Not only do we celebrate the finished product but more importantly the process and learning which has been involved to reach the end result and hopefully develop self-occupancy skills and interests for adult life.", "http://www.peterhouseschool.com", "peterhouse-logo.jpg", "peterhouse-school");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "Prescot Primary School", "prescot-primary", "We value creativity and curiosity from Nursery to Year 6. Our art work links closely with our topics. Children at Prescot Primary are encouraged to believe that anything is possible. Our art entries are inspired by the work of Peter Thorpe, the children spent time looking at his creations and developed their own rockets, planets and skyscapes. This enabled them to create their final pieces using textured paint, paper collage and acrylic paints. The children then assembled their work independently.", "http://www.prescotprimary.org.uk", "prescot-primary-logo.jpg", "prescot-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "Phoenix Primary School", "phoenix-primary", "Phoenix Primary is an inclusive Community School, with resource provision for children with needs in all areas. We celebrate outstanding practice and embrace creativity. Our day to day practice reflects our ethos of 'Where we Rise to the Challenge'. We have children from countries across the world and value differences. Phoenix reflects and celebrates all cultures and focus is placed on art through refugee Week, Global Awareness and World Wise Week. We actively encourage families to participate in creative activities and understand the importance of providing all children with a wide a range of experiences as possible.", "http://www.phoenixprimaryliverpool.co.uk/", "phoenix-primary-logo.jpg", "phoenix-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "St Anne's Catholic Primary School", "st-annes-catholic-primary", "At St Anne's this year we will be taking part in Liverpool's Eighteen for 18 celebrations by having 18 days dedicated to the Arts. Some of the artwork submitted marks the start of these celebrations. They will be used as a stimulus for the rest of the school to take part in a 'My Liverpool' art project. It worked out very nicely working with Year 5 children as some of them were born in 2008! The other pieces of work submitted were part of our Spanish week celebrations in which the children studied the work of Spanish artist Joan Miro.", "http://www.stannescatholicprimary.com/", "st-annes-catholic-primary-logo.jpg", "st-annes-catholic-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "St Anne's Stanley CoE Primary School", "st-annes-stanley-ce-primary", "At St. Anne's, our approach to art is to encourage children to see the world around them in diverse ways and to experiment with making marks, use of colour, and using a range of materials. In this project called Fauvism in Liverpool, children were asked to use chalk to make a skyline of warm tones. A photograph of a Liverpool landmark was then added and using oil pastels, the children then added a layer of solid colours. Finally, a 3rd layer of acetate overlay was placed on top and details of the scene accentuated and outlined with marker pen.", "http://st-anne-stanley-school.co.uk/", "st-anne-stanley-logo.jpg", "st-annes-stanley-ce-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 1, "St Francis de Sales Catholic Junior School", "st-francis-de-sales-catholic-junior", "Art and design has a significant and valuable role to play in the overall ethos of our school. We aim to provide an art curriculum that will enable all children to reach their full potential through equipping them with the knowledge and skills to experiement, invent and create their own works.Incorporating art into the wider curriculum is intrinsic to teaching at our school. In doing so, lessons are more creative and dynamic whilst enabling us to extend and enrich children's learning. In Year 5, the creating of the Greek designs (amphora & oenochoe) is part of our Ancient Greece topic in which children have also written a Greek myth, studied the Trojan War and examined Greek democracy.", "http://www.st-francis-de-sales.co.uk/", "st-francis-de-sales-logo.jpg", "st-francis-de-sales-catholic-junior");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 1, "The Academy of Saint Nicholas", "the-academy-of-saint-nicholas", "Together we Aspire, Believe and Achieve guided by Christian Values of respect, ambition, resilience and compassion. The Art department is an area of excellence and has a strong team spirit.  The aim of the department is to develop the confidence of students and allow them to explore different issues in a creative and imaginative way.  We believe that Art and Design is a unique subject combining visual, emotional, expressive, conceptual and tactile experiences.", "http://www.theacademyofstnicholas.org.uk/", "academy-of-st-nicholas-logo.jpg", "the-academy-of-saint-nicholas");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);
