INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Archers Brook SEMH Residential School", "archers-brook", "This school community offers quality support for children and young people with a range of complex social, emotional and behavioural difficulties often linked with medical conditions such as ADHD or communication needs associated with ASD. We encourage pupils to work creatively in all aspects of the school curriculum.", "http://www.archersbrook.cheshire.sch.uk/", "archers-brook-logo.jpg", "archers-brook");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Barnton Primary School", "barnton-primary", "At Barnton Community Nursery and Primary School we believe in giving children the opportunity to have access to inspiring learning experiences that enable them to appreciate and value art and its influence on culture and society. Children are encouraged to develop a love of art and its richness, and skills and techniques are developed through direct and cross curricular class teaching and through the support of visiting artists.", "http://www.barnton.cheshire.sch.uk", "barnton-primary-logo.jpg", "barnton-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Culcheth High School", "culcheth-high", "Culcheth High School is a highly successful and over-subscribed community school in the heart of semi-rural Warrington. In The Art department @ Culcheth we have a high achieving, nurtured and purposeful working environment. We encourage creativity and expression establishing a fundamental grounding in the key skills of Art & Design. Together the students and staff work with enthusiasm and energy to develop inspirational work and share artistic awareness both in school and the wider community. Students in year 9 have followed a journey of discovery to research and develop a personal response to the theme Mexican Day of The Dead.", "http://culchethhigh.org.uk/", "Culcheth-high-logo.jpg", "culcheth-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Grange Community Primary School", "grange-primary", "Grange Community Primary is a small school at the heart of our community in Winsford. We believe every child has huge potential and it is our responsibility to unlock this, by supporting children and their families to have the highest aspirations and to achieve their very best. At Grange we provide our children with a rich and varied curriculum, making links across all disciplines to gain greater understanding. Year 5 undertook this art project after studying the history and geography of our local area. They refined their techniques in watercolours whilst learning about the physical geography and how it developed.", "https://grange-pri.cheshire.sch.uk/cheshire/primary/grange-pri", "grange-primary-logo.jpg", "grange-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Neston High School", "neston-high", "Neston High School is an 11-18 rural comprehensive school of over 1700 students. The Art and Applied Design Department is one of the largest in the country. Subject specialists deliver a broad Art and Design curriculum including; Fine Art, Textiles, Graphics, Photography and Product Design. ", "www.nestonhigh.cheshire.sch.uk", "neston-logo.jpg", "neston-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Sir William Stanier School", "sir-william-stanier", "We believe our students have the potential to achieve anything they aim for in life. We provide a great start to their future through high quality teaching, a rich and vibrant curriculum experience and a culture of aspiration and ambition. Sir William Stanier School stands for success and progress. We are proud of who we are. The Art and Design department is enthusiastic, innovative and highly creative. We enjoy displaying and celebrating the pupil's artwork throughout the school building. We strive to support pupils to be independent and explore a wide range of materials and techniques.", "http://www.thelifecloud.net/schools/SirWilliamStanierAcademy", "sir-william-stanier-logo.jpg", "sir-william-stanier");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "The Firs School", "the-firs-school", "The Firs School has a proud tradition of taking part at a high level within the creative arts. Art and DT have their own designated spaces in a fully equipped classroom with high level work spaces. The school also has its own ceramics room with kiln and class sets of Chromebooks to encourage digital artistic design. The Firs School enters local and national exhibitions and competitions and this year had particular success with its first place in computer animation in the ISA's National Competition which involved over 400 schools. Pupils use sketchbooks and are encouraged to take inspiration from the areas directly around them, using our beautiful grounds for stimulus as well as school visits to regional landmarks and galleries. Each year we create a whole school exhibition which we proudly display at the Racecourse before putting up in school. The Firs school is an inspirational primary school delivering exceptional learning and the creative arts are very much part of its success.", "http://www.firsschool.net/", "the-firs-school-logo.jpg", "the-firs-school"); 
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "The Queen's Lower School", "the-queens-lower-school", "The Queen's Lower School is an independent girls' school situated in Chester. We believe in education in its broadest sense and our pupils experience art appreciation and teaching throughout our infant and junior classes. Girls enjoy experimenting with a broad range of art techniques, both in our well-equipped art room and outside in the natural environment; progression in art skills, including 3D modelling, textiles, printing and painting, as well as design using technology is interwoven into our creative, enquiry based curriculum. Our art clubs and theme weeks are always very popular!", "http://www.thequeensschool.co.uk", "the-queens-lower-school-logo.jpg", "the-queens-lower-school");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Upton by Chester High School", "upton-by-chester-high", "Upton-by-Chester High is a highly successful, 11-18 High School.  Our mission statement is 'Learning to Shape the Future'. We strive to ensure our students achieve not just academic excellence, but also leave our school ready to take their place in the world of the future. In the Art department our aim is to develop independent and creative thinkers. We believe that art education has a vital role in the development of all pupils and we encourage problem solving, the ability to work and think independently; providing opportunities to apply their ideas and thoughts creatively.", "http://www.uptonhigh.co.uk", "upton-by-chester-high-logo.jpg", "upton-by-chester-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Whitby High School", "whitby-high", "We strive to ensure all students achieve their potential and develop their passion for Art through the provision of a stimulating environment and a structured curriculum in which each student can excel. We ensure all students are provided with a range of skills to use as a means of expressing and communicating their ideas, giving form to their experiences. We encourage in all our students an independence of thought with a critical and aesthetic awareness. We provide our students with an appreciation and understanding of a wide variety of genres and styles from other times, places and peoples.", "http://www.whitbyhigh.org", "whitby-high-logo.jpg", "whitby-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Woodlands Primary", "woodlands-primary", "Woodlands Primary School is a three-form entry school and is one of the largest schools in Cheshire. We have a creative and innovative approach to the curriculum.  ", "http://www.woodlands.cheshire.sch.uk/", "woodlands-primary-logo", "woodlands-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2018);
