<?php
   $this->headTitle('Thank You');
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">Thank You For Voting</h1>
</div>

<p>Thank you for taking the time to vote in the dot-art Schools competition.</p>
<p>We have sent you an email with a link that you <strong>must</strong> click in order to confirm
your vote. Check your Inbox now... (Try your Junk Mail folder if you can&#39;t find it!)</p>

<p><span class="label label-info">Important</span> Please note that if you haven't received your
email within the hour, please let us know by emailing
<a href="mailto:schools@dot-art.com">schools@dot-art.com</a> with details.</p>

<a href="/school/index/name/<?= $this->returnSchoolUrl; ?>" class="btn">Go back to school page</a>

</div>
