<?
   $this->headTitle('Archive');
   $this->headMeta()->appendName('description', 'Archive of schools who took part in past dot-art Schools programmes; an interactive, 
   inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">Schools</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Archive</li>
</ul>

<p>Browse through entries from competitions in previous years by clicking a year below:</p>
<ul>
    <li><a href="/archive/entries/year/2015">2015</a></li>
    <li><a href="/archive/entries/year/2014">2014</a></li>
    <li><a href="/archive/entries/year/2013">2013</a></li>
</ul>

</div>
