USE `dotart`;

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Abbey Gate College", "abbey-gate-college", "Abbey Gate College is the longest running co-educational independent school in Chester providing continuous education for boys and girls from ages 4 - 18 years. Set in idyllic rural surroundings on the outskirts of the city, our Infant and Junior School is based in the village of Aldford, with our Senior School a short distance away in Saighton. At Abbey Gate College our pupils are at the heart of everything we do. We promote a love of learning, academic ambition and excellence within a welcoming, safe and caring community. Pupils are instilled with a 'can do' attitude giving them the confidence to make a difference and 'Be Someone'.", "http://www.abbeygatecollege.co.uk", "abbey-gate-college-logo.jpg", "abbey-gate-college");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2019);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Barrow CE Primary School", "barrow-ce-primary", "Our small, village school is situated in Barrow in rural Cheshire, five miles from the city of Chester. Founded in Victorian times in 1865, the school is awash with character and is a place where forward and progressive thinking meets with traditional values. Barrow School is a focal point of the village and our vibrant community. We are especially proud of our strong Christian ethos and family atmosphere that permeates throughout the school. The work submitted is part of our project on Ancient Greece. The drawings are designs for a life size model of a Greek soldier.", "http://barrowcofeschool.com/", "barrow-ce-logo.jpg", "barrow-ce-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2019);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Beamont Collegiate Academy", "beamont-collegiate-academy", "Beamont Collegiate Academy is a caring and achieving school in which young people thrive and flourish. We provide a stimulating learning experience which challenges and excites students both academically and beyond the classroom. As an art department we work with students to achieve their full potential, encouraging experimentation and guiding practice to achieve excellence. The work submitted is a mixture of Art and Textiles created using a range of mediums based on the project Architecture and looking at the artwork of Ian Murphy for inspiration.", "http://bca.warrington.ac.uk/", "beamont-college-logo.jpg", "beamont-collegiate-academy");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2019);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Frodsham Manor House Primary School", "frodsham-manor-house-primary", "Frodsham Manor House Primary School is an attractive Primary School in Frodsham, Cheshire. Our school vision is 'Hand in hand, we imagine, we believe and we achieve' and we do this by offering an exciting, thematic and rich curriculum in conjunction with a happy caring environment where all children can enjoy the learning process in an atmosphere of excitement, enthusiasm and support. For this art competition, Year 5 children have thought about the emotions inside them as part of our focus on feelings and caring for ourselves and how they can portray them using oil pastels on paper.", "http://www.manorhouse.cheshire.sch.uk/", "frodsham-manor-house-logo.jpg", "frodsham-manor-house-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2019);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "Hartford CoE High School", "hartford-ce-high-school", "Hartford C of E High School is a popular and oversubscribed comprehensive school with demanding expectations and high standards. The Art department at Hartford aims to provide a purposeful and stimulating working environment. Pupils are provided with the necessary skills to allow them to participate in a wide range of creative experiences developed to encourage their understanding and knowledge of a variety of genres and styles. Year 9 were given the task of taking the idea of an ordinary spray can and developing it into a character of their choice. Ideas have been generated through independent research and personal interest.", "https://www.hartfordhigh.org.uk/", "hartford-ce-high-logo.jpg", "hartford-ce-high");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2019);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Hawarden Village Church School", "hawarden-village-church-school", "Hawarden Village Church School is a Happy, Valuing, Caring School in North Wales for pupils aged 3 - 11.   We are passionate about delivering a rich, varied and balanced curriculum, allowing pupils to learn creatively in a way that nurtures and celebrates their individual talents.  We recognise the vital role that art plays in allowing pupils to explore their thoughts or feelings and connect and communicate with others.  We gave our pupils complete freedom when creating their pieces for this competition, allowing them to develop their own ideas and style - we hope this is reflected in the variety of our entries.", "http://www.hawardenvillage.wales", "hawarden-village-church-logo.jpg", "hawarden-village-church-school");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2019);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "The Kings School Macclesfield", "the-kings-school-macclesfield", "The King's School is proud of its history and ambitious for its future. Learning and personal development are at the heart of our community. We seek to equip young people with the character and skills necessary to meet the challenges of an ever changing world. We believe that education is about what happens in the classroom and more. We seek to produce courageous and responsible citizens who contribute to society through leadership and service. The values of love, compassion and respect underpin all our activities. In art we have achieved considerable distinction, exhibiting work at prestigious regional and national venues.", "http://www.kingsmac.co.uk/", "kings-logo.jpg", "the-kings-junior");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2019);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (2, 2, "The Oaks Academy", "the-oaks-academy", "The Oaks Academy is a mixed 11-16 High School accommodating pupils from the local area of Crewe. Pupils currently have 1 art lesson a week at KS3 and are encouraged to explore a range of Fine Art approaches. Year 9 pupils are currently studying the theme of Africa. Having created handmade sketchbooks, they have been exploring a range of mixed media approaches to creating art linked to this theme. The work submitted has been created in lessons or in a Gifted and Talented Art club.", "http://www.theoaksacademy.co.uk", "oaks-academy-logo.jpg", "the-oaks-academy");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2019);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Westminster Community Primary School", "westminster-community-primary", "Westminster Community Primary School is located in Ellesmere Port and is over 100 years old. We are dedicated to providing the best for the children we work with and we enjoy working hard within our 'inclusive and harmonious' school. Our children enjoy a wide range of artistic experiences throughout their school career and thoroughly enjoy exploring all types of art and crafts. Examples of their work ca be seen in and around Ellesmere Port, including at the railway station waiting room and in local shop windows.", "https://www.westminsterprimary.cheshire.sch.uk/", "westminster-primary-logo.jpg", "westminster-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2019);

INSERT INTO school (type, region, name, url_path, statement, website, image, image_folder) VALUES (1, 2, "Willaston CE Primary School", "willaston-ce-primary", "At Willaston CE Primary School we are passionate about providing a creative environment for our children. We aim for children's learning to be exciting and imaginative, providing opportunities for first hand experiences, practical work, investigation and play. The arts play a central role in the delivery of our curriculum. Our commitment is evident in our children's involvement in the Art Awards Explore and Discover, our achievement of the Artsmark Gold Award and in the rich learning environment that we provide for our children.", "http://www.willastonceprimaryschool.co.uk/", "willaston-ce-primary-logo.jpg", "willaston-ce-primary");
INSERT INTO school_year (school, year)
 VALUES(LAST_INSERT_ID(), 2019);

