-- USE `dotart`;

INSERT INTO entry (school_year, artist, title, properties, image) VALUES (398, "Daniel Pittard Wheeler", "Mixed media vessel 1", "9 x 9 cm, Ceramic and wire", "mixed-media-vessel-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (398, "Amelia Gelder", "Mixed media vessel 2", "9 x 12 cm, Ceramic and wire", "mixed-media-vessel-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (398, "Lauren Hopkins", "Mixed media vessel 3", "6 x 18 cm, Ceramic and wire", "mixed-media-vessel-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (398, "Harry Green", "Mixed media vessel 4", "8.5 x 16 cm, Ceramic and wire", "mixed-media-vessel-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (398, "Ella Stockton", "Tudor House 1", "2.5 x 3 x 7cm, Ceramic", "tudor-house-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (398, "Misty Mansfield", "Tudor House 2", "3 x 3 x 8cm, Ceramic", "tudor-house-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (398, "Luke Lardner-Mackin", "Tudor House 3", "3.5 x 3 x 7cm, Ceramic", "tudor-house-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (398, "Lucy Shutler", "Tudor House 4", "3 x 4 x 6.5cm, Ceramic", "tudor-house-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Summar Linsey-Shihadah", "Woodland patterns", "30 x 27cm, Mixed media ", "woodland-patterns.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Ruby Leather", "Woodland walks ", "28 x 36cm, Oil Pastels", "woodland-walks.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Rose Lawson", "Wild flower meadows ", "18 x 26cm, Oil Pastels", "wild-flower-meadows.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Emilia Newport", "Poppy Field", "23 x 34cm, Oil Pastels", "poppy-field.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Matilda Williams", "Hayfield ", "25 x 37cm, Oil Pastels", "hayfield.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Ed Kinsey", "Wildflower Landscape ", "36 x 22cm, Oil Pastels", "wildflower-landscape.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Harry Clough", "Dripping Eye", "36 x 30 cm, Pen and inks", "dripping-eye.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Lydia Street", "Crying eye", "30 x 42 cm, Pen and inks", "crying-eye.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Daniel Leather", "Blue Eye ", "42 x 30 cm, Pen and inks", "blue-eye.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Madison Latham", "Colourful Eye ", "42 x 30 cm, Pen and inks", "colourful-eye.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Jason Cooper", "Night time ", "27 x 20 cm, Pen and inks", "night-time.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Megan Brown", "Night life", "24 x 37 cm, Pen and inks", "night-life.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Toba Jellicoe", "Meadow of Flowers ", "35 x 25 cm, Oil pastels", "meadow-of-flowers.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Evie Mackintosh", "Summer Flowers", "23 x 34 cm, Oil pastels", "summer-flowers.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Alexi Harper", "Sunset Landscape ", "25 x 28 cm, Oil pastels", "sunset-landscape.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Ava Chapman", "Lupins", "25 x 29 cm, Oil pastels", "lupins.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Holly Hale", "Country landscape", "17 x 25 cm, Oil pastels", "country-landscape.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Pixie Barlow", "Bright Eye ", "30 x 41 cm, Pen and inks", "bright-eye.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "George Evans", "Beautiful Birds", "30 x 39 cm, Watercolours", "beautiful-birds.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Finn Gilding", "Colourful Birds", "30 x 37 cm, Watercolours", "colourful-birds.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Eddie Ambrus", "Woodland leaves", "51 x 27cm, Mixed media", "woodland-leaves.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (386, "Jake Tudor", "Nature Colours", "25 x 17 cm, Oil pastels", "nature-colours.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Isabelle Lynch", "Untitled 1", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Kiera Paterson", "Untitled 2", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Nathan Karpinski", "Untitled 3", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Hannah Dougan", "Untitled 4", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Francesca Hyndman", "Untitled 5", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Kayte-Mae Hobbs", "Untitled 6", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-6.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Lexie Skelton", "Untitled 7", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-7.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Lily Roberts", "Untitled 8", "28 x 28cm, Mixed media, paint and oil pastel", "untitled-8.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Freya Roebuck", "Untitled 9", "30 x 29cm, Mixed media, paint and oil pastel", "untitled-9.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Lauren Greasley", "Untitled 10", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-10.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Missy Sant", "Untitled 11", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-11.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Freya Loverseed", "Untitled 12", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-12.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Olivia Frazer", "Untitled 13", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-13.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Freya Voce", "Untitled 14", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-14.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Henryk Wieckowski", "Untitled 15", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-15.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Olivia Deakin", "Untitled 16", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-16.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Ryan Adlington", "Untitled 17", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-17.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Finlay Fisher", "Untitled 18", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-18.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Molly Moran", "Untitled 19", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-19.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Tristan Meesala", "Untitled 20", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-20.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Lyra Reilly", "Untitled 21", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-21.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Izabelle Kidd", "Untitled 22", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-22.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Maddison Eaves", "Untitled 23", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-23.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Lydia Ollier", "Untitled 24", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-24.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (387, "Maisie Almond", "Untitled 25", "30 x 28cm, Mixed media, paint and oil pastel", "untitled-25.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (399, "Oliver Brown", "Greek Art 1", "60 x 90cm, Oil pastel and black marker pen", "greek-art-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (399, "Charlie Coulter Farrall", "Greek Art 2", "60 x 90cm, Oil pastel and black marker pen", "greek-art-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (399, "Lucy Green - Garton", "Greek Art 3", "60 x 90cm, Oil pastel and black marker pen", "greek-art-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (399, "Clara Hassells", "Greek Art 4", "60 x 90cm, Oil pastel and black marker pen", "greek-art-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (399, "Zach Thompson", "Greek Art 5", "60 x 90cm, Oil pastel and black marker pen", "greek-art-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Megan Thomason", "Alleyway", "44 x 43cm, Acrylic paint", "alleyway.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Elise Burgess", "Close up 1", "33 x 28cm, Ink", "close-up-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Michaela Heath", "Liverpool", "46 x 49cm, Prints", "liverpool.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Jake Cooke", "Up close", "61 x 52cm, Acrylic paint", "up-close.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Dylan Stewart", "The town clock", "41 x 30cm, Acrylic paint", "town-clock.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Ellie-Louise Blackburn", "Italy 1", "29 x 42cm, Mixed media", "italy-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Holly Higham", "Italy 2", "30 x 42cm, Mixed media", "italy-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Madison Davies-Kokat", "Close up 2", "30 x 42cm, Mixed media", "close-up-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Klaudia Majka", "Close up 3", "30 x 42cm, Mixed media", "close-up-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Nicola Mondry", "Fading into the past", "33 x 34cm, Mixed media", "fading-into-the-past.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Nicholas Miko", "Building adornments", "55 x 40cm, Acrylic paint", "building-adornments.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Dylan Braddish", "Aspects of buildings ", "41 x 30cm, Acrylic paint", "aspects-of-buildings.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Jess Dean", "Architectural beauty", "43 x 66cm, Ink", "architectural-beauty.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Simon Elias", "Abstract building", "60 x 41cm, Acrylic paint", "abstract-building.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Scott Riley", "Extreme close up", "39 x 43cm, Acrylic paint", "extreme-close-up.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Chazelle Osman", "Building layers", "48 x 43cm, Mixed media textiles", "building-layers.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Katie Moore", "Fragments 1", "51 x 23cm, Mixed media textiles", "fragments-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Libby Clarke", "Outline ", "33 x 24cm, Mixed media ", "outline.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Ben Murphy", "Fragments 2", "43 x 26cm, Mixed media", "fragments-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (400, "Thomas Roberts", "Elements", "36 x 23cm, Mixed media", "elements.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Li Zhi Potts", "Flower Power", "41 x 15cm, Mixed media", "flower-power.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Evan Hickman", "LV", "41 x 15cm, Mixed media", "lv.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Leah Collins", "Dog 'n' Bone", "41 x 15cm, Mixed media", "dog-n-bone.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Hannah Kolita-Blood", "1960's Fashion", "41 x 15cm, Mixed media", "1960s-fashion.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Emily Ward", "Animal Zine", "41 x 15cm, Mixed media", "animal-zine.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Annie Baker", "London", "18 x 21cm, Mixed media textile", "london.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Caitlin Trainer", "Doggy Doodle", "20 x 15cm, Mixed media textile", "doggy-doodle.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Abbie Whitcher", "Snap!", "18 x 24cm, Mixed media textile", "snap.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Erin Flanagan", "Little Mix", "15 x 21cm, Mixed media textile", "little-mix.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Chloe Paget", "Shark Life", "14 x 21cm, Mixed media textile", "shark-life.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Oliver Sutcliffe", "Red Shoes", "15 x 21cm, Mixed media textile", "red-shoes.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Grace Williams", "Emotions", "14 x 21cm, Mixed media textile", "emotions.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Thomas Kemp", "Eye See Everything", "15 x 21cm, Mixed media textile", "eye-see-everything.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Lucy McNeill", "I love make up", "41 x 15cm, Mixed media ", "love-make-up.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Meadow Whitehead", "Make up Brands", "41 x 15cm, Mixed media ", "make-up-brands.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Will Gidea", "Tyler Who Dat Boy?", "20 x 15cm, Mixed media", "who-dat-boy.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Louise Mann", "Cities Concrete Jungle", "41 x 15cm, Mixed media ", "cities-concrete-jungle.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Will Towers", "Basketball Zine", "41 x 15cm, Mixed media", "basketball-zine.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Imogen Leah", "Fashion", "41 x 15cm, Mixed media", "friends.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Lauren Norman", "Dance Zine", "41 x 15cm, Mixed media", "dance-zine.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Abby Gillingham", "Full House", "41 x 15cm, Mixed media", "full-house.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Megan Hawkins", "Friends", "41 x 15cm, Mixed media", "friends.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Pippa Bailey", "13 Reasons Why", "41 x 15cm, Mixed media", "13-reasons-why.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Millie-Kit Lawton", "Positivity", "41 x 15cm, Mixed media", "positivity.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (388, "Mia Scattergood", "Space", "41 x 15cm, Mixed media", "space.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Abi Hazelhurst", "Penguins 1", "24 x 25cm, Watercolours", "penguins-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Amelia Wood", "Lion", "33 x 21cm, Watercolours", "lion.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Arran Robbins", "Tiger 1", "31 x 28cm, Oil Pastels", "tiger-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Bella Wood", "Tiger 2", "41 x 29cm, Watercolours", "tiger-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Charlie Barratt", "Jaguar", "30 x 41cm, Charcoal", "jaguar.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Charlie Wall", "Tiger 3", "30 x 26cm, Oil Pastels", "tiger-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Chloe Kaziu", "Penguins 2", "30 x 42cm, Oil Pastel, Watercolours", "penguins-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Ella Ogden", "Monkey 1", "42 x 30cm, Watercolours", "monkey-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Gabriel Green", "Tiger 4", "38 x 30cm, Oil Pastels", "tiger-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Isla Bushell", "Tiger 5", "29 x 25cm, Pencil", "tiger-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Isla Entwistle", "Koala Bear", "35 x 42cm, Oil Pastel, Watercolour", "koala-bear.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Isla Houston", "Cheetah 1", "30 x 28cm, Charcoal", "cheetah-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "James McCallum", "Red Panda 1", "41 x 29cm, Watercolours", "red-panda-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Jose LeBreton", "Red Panda 2", "45 x 33cm, Watercolours", "red-panda-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Maisey Heath", "Monkey 2", "41 x 24cm, Watercolours", "monkey-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Max Dedicoat", "Leopard", "32 x 38cm, Oil Pastel, Colour pencil", "leopard.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Mollie Carroll", "Cheetah 2", "32 x 35cm, Watercolours", "cheetah-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Neve Beswick", "Monkey 3", "38 x 26cm, Watercolours", "monkey-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Rebekah Pye", "Monkey 4", "42 x 33cm, Oil Pastel, Watercolour", "monkey-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Rowan Cartwright", "American Eagle", "41 x 29cm, Charcoal", "american-eagle.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Sophia Emmett", "Penguins 3", "41 x 32cm, Oil Pastel, Watercolour", "penguins-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Tallulah Bloyce", "Chameleon", "41 x 26cm, Watercolours", "chameleon.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Teddy Rothwell", "Butterfly", "41 x 28cm, Oil Pastel", "butterfly.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (389, "Thomas Hill", "Rhino", "31 x 28cm, Oil Pastel", "rhino.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Alysha Ashcroft", "Feelings inside me 1", "21 x 30cm, Oil Pastel", "feelings-inside-me-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Isabel Atkin", "Feelings inside me 2", "21 x 30cm, Oil Pastel", "feelings-inside-me-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Edith Banks ", "Feelings inside me 3", "21 x 30cm, Oil Pastel", "feelings-inside-me-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Rhys Baynham-Hughes", "Feelings inside me 4", "21 x 30cm, Oil Pastel", "feelings-inside-me-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Olivia Brown ", "Feelings inside me 5", "21 x 30cm, Oil Pastel", "feelings-inside-me-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Alice Buckley ", "Feelings inside me 6", "21 x 30cm, Oil Pastel", "feelings-inside-me-6.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Phoebe Burton ", "Feelings inside me 7", "21 x 30cm, Oil Pastel", "feelings-inside-me-7.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Ella Carter", "Feelings inside me 8", "21 x 30cm, Oil Pastel", "feelings-inside-me-8.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Ella Cleave", "Feelings inside me 9", "21 x 30cm, Oil Pastel", "feelings-inside-me-9.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Harrison ", "Feelings inside me 10", "21 x 30cm, Oil Pastel", "feelings-inside-me-10.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Robyn Dawson ", "Feelings inside me 11", "21 x 30cm, Oil Pastel", "feelings-inside-me-11.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Kimberly Erasmus ", "Feelings inside me 12", "21 x 30cm, Oil Pastel", "feelings-inside-me-12.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Phoebe Fraser ", "Feelings inside me 13", "21 x 30cm, Oil Pastel", "feelings-inside-me-13.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Isabelle Gormally ", "Feelings inside me 14", "21 x 30cm, Oil Pastel", "feelings-inside-me-14.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Abigail Gorry", "Feelings inside me 15", "21 x 30cm, Oil Pastel", "feelings-inside-me-15.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Ella Griffiths", "Feelings inside me 16", "21 x 30cm, Oil Pastel", "feelings-inside-me-16.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Bethany Hardy", "Feelings inside me 17", "21 x 30cm, Oil Pastel", "feelings-inside-me-17.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Amelia-Faith Pearson", "Feelings inside me 18", "21 x 30cm, Oil Pastel", "feelings-inside-me-18.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Luke Houlbrook ", "Feelings inside me 19", "21 x 30cm, Oil Pastel", "feelings-inside-me-19.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Lois Lee", "Feelings inside me 20", "21 x 30cm, Oil Pastel", "feelings-inside-me-20.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Oisín Moloney-Pugh", "Feelings inside me 21", "21 x 30cm, Oil Pastel", "feelings-inside-me-21.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Ashton Moston ", "Feelings inside me 22", "21 x 30cm, Oil Pastel", "feelings-inside-me-22.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Ruby Paul ", "Feelings inside me 23", "21 x 30cm, Oil Pastel", "feelings-inside-me-23.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Ethan Seymour", "Feelings inside me 24", "21 x 30cm, Oil Pastel", "feelings-inside-me-24.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Elizabeth Smith ", "Feelings inside me 25", "21 x 30cm, Oil Pastel", "feelings-inside-me-25.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Daisy Tandy", "Feelings inside me 26", "21 x 30cm, Oil Pastel", "feelings-inside-me-26.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Eva Taylor-Williams ", "Feelings inside me 27", "21 x 30cm, Oil Pastel", "feelings-inside-me-27.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Finn Williamson", "Feelings inside me 28", "21 x 30cm, Oil Pastel", "feelings-inside-me-28.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (401, "Lucie Crozier ", "Feelings inside me 29", "21 x 30cm, Oil Pastel", "feelings-inside-me-29.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Maddie Haddock", "Ru Paul", "39 x 30cm, Acrylic paint on card  ", "ru-paul.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Alisha Seddon", "Marilyn", "41 x 30cm, Acrylic paint on card", "marilyn.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Charlie Morris ", "Dictator", "54 x 39cm, Acrylic paint on card", "dictator.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Isobel Sanders", "The Colonel", "40 x 30cm, Acrylic paint on card", "the-colonel.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Alfie Naylor ", "MJ", "36 x 36cm, Acrylic paint on card", "mj.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Ellie Johnson", "Sasha Fierce", "39 x 32cm, Acrylic paint on card", "sasha-fierce.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Jennifer Riley ", "Explorer", "48 x 46cm, Acrylic paint on card", "explorer.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Ruby Clark", "Kim Kardashian ", "42 x 38cm, Acrylic paint on card", "kim-kardashian.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Katy Ball", "Dali", "56 x 33cm, Acrylic paint on card", "dali.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Sam Brady", "Fake News", "40 x 24cm, Acrylic paint on card", "fake-news.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Paris Basset", "Widow Maker", "44 x 38cm, Acrylic paint on card", "widow-maker.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Thomas Greaves", "The Joker", "37 x 35cm, Acrylic paint on card", "the-joker.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Erin Cloherty", "Einstein", "44 x 38cm, Acrylic paint on card", "einstein.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Eleanor Bradbury ", "Pennywise", "36 x 39cm, Acrylic paint on card", "pennywise.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Katie Turner", "Brendon Urie", "41 x 40cm, Acrylic paint on card", "brendon-urie.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Grace Roberts", "Under the Sea", "38 x 30cm, Acrylic paint on card", "under-the-sea.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Nina Martin", "Sing out", "44 x 24cm, Acrylic paint on card", "sing-out.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Isabelle Buck", "Ariana", "38 x 30cm, Acrylic paint on card", "ariana.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Grace Sperring Toy", "Festival", "40 x 26cm, Acrylic paint on card", "festival.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Isabelle Barnett", "The Snitch", "21 x 56cm, Acrylic paint on card", "the-snitch.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Hermione Mason", "Banksy", "27 x 36cm, Acrylic paint on card", "banksy.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Anna Yevseyev", "Dumbo", "43 x 60cm, Acrylic paint on card", "dumbo.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Isabelle Fleming", "Hermione", "49 x 30cm, Acrylic paint on card", "hermione.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Mary Smith", "Matilda", "50 x 25cm, Acrylic paint on card", "matilda.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (402, "Emmy Abbott", "Circus", "36 x 40cm, Acrylic paint on card", "circus.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "James Oakley", "Colourful Hands ", "30 x 42cm, Paint and felt tip pens", "colourful-hands.jpg ");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Luke Williams", "100% Effort", "30 x 42cm, Paint, chalk, collage", "one-hundred-percent-effort.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Sarah McKee and Eleanor Grugel", "Wild Horses", "39 x 49cm, Chalk, pastel, paint ", "wild-horses.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Ella Morrison", "Freedom With Flight", "40 x 60cm, Paint ", "freedom-with-flight.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Owen Ellis ", "Waterfall Under The Rainbow", "30 x 42cm, Pen, Pencil Crayon ", "waterfall-under-the-rainbow.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Leon Humphreys and George Allen", "The Mountain Milky Way", "31 x 42cm, Pencil Crayon, Felt tip pens", "the-mountain-milky-way.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Emilia Richardson", "Blossom World", "30 x 42cm, Chalk, Paint, Pencil Crayon ", "blossom-world.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Danielle Price", "The Day and Night Tree", "39 x 30cm, Paint", "the-day-and-night-tree.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Tia Tuft", "Sun and Moon", "42 x 30cm, Paint", "sun-and-moon.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Amie Bartley", "Sea of Blue", "23 x 30cm, Paint, Pencil Crayon ", "sea-of-blue.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Evie Jones", "Our Space", "23 x 30cm, Paint, Pencil Crayon", "our-space.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Daisy Clarke", "The Sunset Mountains", "23 x 30cm, Chalk, Paint, Collage ", "the-sunset-mountains.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Grace Parry", "Be Creative", "30 x 42cm, Pastel, Paints and Felt Tip pens", "be-creative.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Sophie Lynn", "Unicorn", "23 x 30cm, Pen, Chalk ", "unicorn.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Leon Humphreys", "Lamborghini of Dreams ", "23 x 30cm, Pencil Crayon", "lamborghini-of-dreams.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Dylan Astbury", "The Sunset", "30 x 19cm, Pastel, black paper", "the-sunset.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Luke Tyndall and Sam Williams", "The Space Explosion", "23 x 31cm, Paint, Chalk ", "the-space-explosion.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Poppy Littleton, Sophie Littleton and Hoi Yee Lam", "Milky Way", "60 x 102cm, Paint , Chalk , Pastel, Collage", "milky-way.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Ava Waterfall", "Where the Wildlife Begins", "60 x 102cm, Paint", "where-wildlife-begins.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Morgan Thelwell", "Skylight Mountains", "14 x 18cm, Felt tip pens", "skylight-mountains.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Poppy Williams", "Over The Cities", "23 x 31cm, Paint, Black paper ", "over-the-cities.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Seren Woods", "Dream Wolf", "27 x 23cm, Watercolours", "dream-wolf.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Georgia Williams", "Tree Scene", "18 x 29cm, Paint", "tree-scene.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Daisy Lindop and Nieve McCulloch", "Day vs Night", "29 x 40cm, Paint", "day-vs-night.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (403, "Chloe Birch", "Rainbow", "30 x 40cm, Paint, felt tip pens", "rainbow.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Pablo Stanley-Latorre", "Mackerel 1", "30 x 40cm, Mixed media", "mackerel-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "William Albiston- Bennett", "Mackerel 2", "30 x 40cm, Mixed media", "mackerel-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Max Harbridge", "Mackerel 3", "30 x 40cm, Mixed media", "mackerel-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Neve Horne", "Mackerel 4", "30 x 40cm, Mixed media", "mackerel-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Sophie McIntyre", "Shoal 1", "30 x 40cm, Mixed media", "shoal-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Ellie - Nichole Forster", "Fishes 1", "30 x 40cm, Mixed media", "fishes-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Nia Edwards", "Mackerel 5", "30 x 40cm, Mixed media", "mackerel-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Ruby Barton", "Shoal 2", "30 x 40cm, Mixed media", "shoal-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Isla Alberda", "Fishes 2", "30 x 40cm, Mixed media", "fishes-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Rachel Thompson", "Fishes 3", "30 x 40cm, Mixed media", "fishes-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Sam Heverin", "Fishes 4", "30 x 40cm, Mixed media", "fishes-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Ieuan Morris", "Fishes 5", "30 x 40cm, Mixed media", "fishes-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Noah Simpson", "Mixed media fish 1", "30 x 40cm, Mixed media", "mixed-media-fish-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Riley Walker", "Mixed media fish 2", "30 x 40cm, Mixed media", "mixed-media-fish-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Archie McConville", "Mixed media fish 3", "30 x 40cm, Mixed media", "mixed-media-fish-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Phoebe Grindrod", "Mackerel shoal 1", "30 x 40cm, Mixed media", "mackerel-shoal-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Chloe Pawley", "Mackerel shoal 2", "30 x 40cm, Mixed media", "mackerel-shoal-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Louisa Plumbley", "Mackerel shoal 3", "30 x 40cm, Mixed media", "mackerel-shoal-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Roshan Narsai-Latham", "Mackerel shoal 4", "30 x 40cm, Mixed media", "mackerel-shoal-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Jack Elson", "Swim 1", "30 x 40cm, Mixed media", "swim-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Sophia Windhaber", "Swim 2", "30 x 40cm, Mixed media", "swim-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Tom Farrington", "Swim 3", "30 x 40cm, Mixed media", "swim-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Charlie Rogers", "Swim 4", "30 x 40cm, Mixed media", "swim-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Summer Davenport", "Swim 5", "30 x 40cm, Mixed media", "swim-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (390, "Alice Brookfield", "Mixed media fish 4", "30 x 40cm, Mixed media", "mixed-media-fish-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Isaac White ", "Rex-ray response 1", "15 x 41cm, Collage ", "rex-ray-response-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Tyra Kiama ", "Rex-ray response 2", "15 x 41cm, Collage ", "rex-ray-response-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Emily Taylor", "Rex-ray response 3", "15 x 41cm, Collage ", "rex-ray-response-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Matthew Peters", "Rex-ray response 4", "15 x 41cm, Collage ", "rex-ray-response-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Kirsty Johnson ", "Rex-ray response 5", "15 x 41cm, Collage ", "rex-ray-response-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Mia Wood ", "Rex-ray response 6", "15 x 41cm, Collage ", "rex-ray-response-6.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "George Roe", "Clare Youngs Response 1", "24 x 26cm, Calico, fabric dye, embroidery thread ", "clare-youngs-response-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Tamsin Jones", "Clare Youngs Response 2", "24 x 26cm, Calico, fabric dye, embroidery thread ", "clare-youngs-response-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Freya Dodd ", "Clare Youngs Response 3", "24 x 26cm, Calico, fabric dye, embroidery thread ", "clare-youngs-response-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Thomas Phillipart", "Into the woods 1 ", "35 x 60cm, Acrylic paint", "into-the-woods-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Ami Pepper ", "Into the woods 2", "38 x 60cm, Acrylic paint", "into-the-woods-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Emily Beddoes", "Into the woods 3", "43 x 60cm, Acrylic paint", "into-the-woods-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Lily Jones ", "Into the woods 4", "38 x 60cm, Acrylic paint", "into-the-woods-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Phoebe Jones ", "Into the woods 5", "44 x 60cm, Acrylic paint", "into-the-woods-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Nyssa Walton", "Into the woods 6", "34 x 60cm, Acrylic paint", "into-the-woods-6.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Grace Scott ", "Into the woods 7", "40 x 60cm, Acrylic paint", "into-the-woods-7.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Olivia Holroyd ", "Into the woods 8", "34 x 60cm, Acrylic paint", "into-the-woods-8.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Louis Miller Musset ", "Anatomy 1", "30 x 41 cm, Ink, fineliner and colour pencil ", "anatomy-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Imogen Fenney ", "Anatomy 2", "30 x 41 cm, Ink, fineliner and colour pencil ", "anatomy-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Ella Hennell-Nealey ", "Anatomy 3", "30 x 41 cm, Ink, fineliner and colour pencil ", "anatomy-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Jake Barnard ", "Portrait 1 ", "26 x 26 cm, Oil pastel, felt pen ", "portrait-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Eleanor Jackson", "Portrait 2", "26 x 26 cm, Oil pastel, felt pen ", "portrait-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Molly Kent", "Portrait 3", "26 x 26 cm, Oil pastel, felt pen ", "portrait-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (391, "Lily Owen", "Portrait 4", "26 x 26 cm, Oil pastel, felt pen ", "portrait-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "LW", "Patterns 1", "30 x 42cm, Pencil crayon", "patterns-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "GH", "Heartbeat", "30 x 42cm, Watercolours/pens", "heartbeat.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "CB", "Flower", "30 x 42cm, Pencil crayon", "flower.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "AP", "Patterns 2", "30 x 42cm, Pencil crayon", "patterns-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "LR", "Patterns 3", "30 x 42cm, Pencil crayon", "patterns-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "JB", "Geometric", "30 x 42cm, Pencil crayon", "geometric.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "TB", "Flowers 2 ", "30 x 42cm, Pencil crayon", "flowers-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "ED", "Mechanisms ", "30 x 42cm, Pencils, watercolours, black pen, metallics ", "mechanisms.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "MM", "Patterns 4", "30 x 42cm, Pencil crayon", "patterns-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "GT", "Galaxy mirror", "30 x 42cm, Watercolour pencils, acrylic paint, pencil ", "galaxy-mirror.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "PW", "Under the sea", "30 x42cm, Cardboard, paper, hamma beads, lego, tin foil, paint, felt tip pens ", "under-the-sea.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "HG", "Reflection", "30 x 42cm, Watercolour pencils", "reflection.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "OP", "Patterns 6", "30 x 42cm, Pencil crayon", "patterns-6.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "JD", "Patterns 5", "30 x 42cm, Felt tip pens", "patterns-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "EF", "Patterns 7 ", "30 x 42cm, Felt tip pen, pencil crayon", "patterns-7.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "AW", "Patterns 8", "30 x 42cm, Pencil crayon", "patterns-8.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "FW", "Patterns 9", "30 x 42cm, Felt tip pen, pencil", "patterns-9.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "MT", "Patterns 10", "30 x 42cm, Felt tip pen", "patterns-10.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (393, "TT", "Patterns 11", "30 x 42cm, Watercolours, Sharpie ", "patterns-11.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (394, "Bibi Charlesworth", "Vogue", "48 x 68cm, Mixed media", "vogue.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (394, "Millie Edwards", "Remembrance ", "48 x 68cm, Mixed media", "remembrance.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (394, "Krystal Gibbins", "Ballerina", "48 x 68cm, Mixed media", "ballerina.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (394, "Destinee Parsonage", "Untitled 1", "21 x 30cm, Watercolour, acrylic and fine liner", "untitled-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (394, "Zara Hassall", "Untitled 2", "21 x 30cm, Pencil crayon", "untitled-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (394, "Terri Hough", "Untitled 3", "43 x 43cm, Oil pastel", "untitled-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (394, "Dakota Jones", "Care and be aware", "42 x 60cm, Acrylic, watercolour, fine liner, pencil crayon", "care-and-be-aware.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (394, "Jodie Peake", "Roman", "80 x 50cm, Card,masking tape and acrylic paint", "roman.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Paulina Szewczyk", "Fox in the snow ", "21 x 30cm, Coloured pencil ", "fox-in-the-snow.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Eimear Comboy", "Under the sea", "30 x 42cm, Watercolour and chalk ", "under-the-sea.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Owi Ball", "The X-men", "30 x 42cm, Fine-liner, biro and ink", "the-x-men.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Milly Allen", "Fox reflection ", "21 x 30cm, Coloured pencil ", "fox-reflection.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Sam Giavedoni", "A knight and the dragon ", "30 x 42cm, Colour pencil", "knight-and-the-dragon.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Anabelle Gallagher", "Palm Sunset  ", "21 x 30cm, Coloured pencil, watercolour and acrylic paint", "palm-sunset.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Amy Sheen ", "Orangutan ", "21 x 30cm, Coloured pencil", "orangutan.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Eva Grice", "Teal bubble", "30 x 42cm, Pencil and chalk", "teal-bubble.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Hannah Rich", "Floral Arrangements", "21 x 30cm, Biro and watercolour ", "floral-arrangement.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Olivia Andrzejewska", "Noir", "15 x 21cm, Prisma pencils, copics markers ", "noir.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Matilda Delf", "Eyes more than vision", "15 x 21cm, Coloured pencil ", "eyes-more-than-vision.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Annabelle Kelly", "Cheshire Polo Club ", "21 x 30cm, Collage and acrylic", "cheshire-polo-club.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Poppy Knight", "Colour vision", "21 x 30cm, Acrylic, fine liner", "colour-vision.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Aislinn Clark ", "Lion", "21 x 30cm, Watercolour", "lion.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (395, "Catherine Lever", "Natural", "15 x 21cm, Pencil ", "natural.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (396, "Sawa Maiuri", "Butterfly book 1", "40 x 18cm, Drawing, print and watercolour", "butterfly-book-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (396, "Hana Rosqueta", "Butterfly book 2", "40 x 18cm, Drawing, print and watercolour", "butterfly-book-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (396, "Shakti Ramesh", "Butterfly book 3", "40 x 18cm, Drawing, print and watercolour", "butterfly-book-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (396, "Hannah Edwards", "Laura Bell painting 1", "66 x 43cm, Acrylic paint, ink, card", "laura-bell-painting-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (396, "Katie Stanworth", "Laura Bell painting 2", "66 x 43cm, Acrylic paint, ink, card", "laura-bell-painting-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (396, "Jadah Sidwell", "Laura Bell painting 3", "66 x 43cm, Acrylic paint, ink, card", "laura-bell-painting-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (396, "Bridie O' Reilly", "Circus 1", "30 x 21cm, Wire, paper, print, collage", "circus-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (396, "Isabelle Price", "Circus 2", "30 x 20cm, Wire, paper, print, collage", "circus-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (396, "Grace Hawkin", "Circus 3", "27 x 21cm, Wire, paper, print, collage", "circus-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Tom Calderwood", "Galaxy", "21 x 30cm, Silk paint on silk", "galaxy.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Olivia Bray", "Galaxy 1", "21 x 30cm, Silk paint on silk", "galaxy-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Sophie Chong", "Galaxy 2", "21 x 30cm, Silk paint on silk", "galaxy-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Emily Matthews", "Galaxy 3", "21 x 30cm, Silk paint on silk", "galaxy-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Zach al Ausi", "Galaxy 4", "21 x 30cm, Silk paint on silk", "galaxy-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Archie Hood", "Galaxy 5", "21 x 30cm, Silk paint on silk", "galaxy-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Lauren Whaley", "Galaxy 6", "21 x 30cm, Silk paint on silk", "galaxy-6.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Adithya Nair", "Henry VIII a", "21 x 30cm, Pencil on paper", "henry-viii-a.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Rosie Bowen", "Henry VIII b", "21 x 30cm, Pencil on paper", "henry-viii-b.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Alex Cooper", "Henry VIII c", "21 x 30cm, Pencil on paper", "henry-viii-c.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Poppy Moore", "Henry VIII d", "21 x 30cm, Pencil on paper", "henry-viii-d.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Tamara Syrett", "Henry VIII e", "21 x 30cm, Pencil on paper", "henry-viii-e.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Purdey Lowe", "Henry VIII f", "21 x 30cm, Pencil on paper", "henry-viii-f.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Charlie Maunders", "Henry VIII g", "21 x 30cm, Pencil on paper", "henry-viii-g.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Abigail Poulton", "Art in Maths 1", "21 x 30cm, Pencil on paper", "art-in-maths-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Emily Carter", "Art in Maths 2", "21 x 30cm, Pencil on paper", "art-in-maths-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Alice Vital", "Art in Maths 3", "21 x 30cm, Pencil on paper", "art-in-maths-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Jasmine Oakes", "Poppy Sketch 1", "21 x 30cm, Pencil on paper", "poppy-sketch-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Reuben Blackhurst", "Poppy Sketch 2", "21 x 30cm, Pencil on paper", "poppy-sketch-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Rory Horne", "Remembrance Day 1", "21 x 30cm, Watercolour silhouette collage ", "remembrance-day-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Louisa Bailey ", "Remembrance Day 2", "21 x 30cm, Watercolour silhouette collage ", "remembrance-day-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Harley Coulson", "Remembrance Day 3", "21 x 30cm, Watercolour silhouette collage ", "remembrance-day-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Ollie Walsh", "Saturn 1", "21 x 30cm, Chalk on black paper", "saturn-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Emily Carter", "Saturn 2", "21 x 30cm, Chalk on black paper", "saturn-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Jack Ledger", "Saturn 3", "21 x 30cm, Chalk on black paper", "saturn-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (404, "Kaan Kynagoli", "Saturn 4", "21 x 30cm, Chalk on black paper", "saturn-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (405, "Milly Kolbuck", "Please help me", "51cm x 34cm, Mixed media", "please-help-me.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (405, "Kelly Wu", "The Elegant Elephant", "59cm x 42cm, Mixed media", "elegant-elephant.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (405, "Francesca Beard", "African Mask", "33cm x 51cm, Mixed media", "african-mask.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (405, "Kennan Rutter", "Rhino", "47cm x 51cm, Graphite and White Paint", "rhino.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (405, "Jagoda Jakubiak", "Giraffe", "31cm x 31cm, Graphite and White Paint", "giraffe.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (405, "Amy Chen", "African Giraffe", "41cm x 59cm, Mixed media", "african-giraffe .jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (405, "Gabriella Beeney", "Roar", "41cm x 59cm, Mixed media", "roar.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (405, "Halina Sidzinska", "The Right Stripe", "41cm x 59cm, Mixed media", "the-right-stripe.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (405, "Ellie Garrett", "The Elephant", "51cm x 35cm, Graphite and White Paint", "the-elephant.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (405, "Bethany Wallace", "The White Rhinoceros", "42cm x 59cm, Mixed media", "the-white-rhinoceros.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (406, "Katelyn-Eve Barker-Fenton", "Eye Believe", "45 x 33cm, Black art pen, collage", "eye-believe.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (406, "Scarlett Dean", "Tentacles", "45 x 33cm, Black art pen, collage", "tentacles.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (406, "Annabel Turley", "Eye Lashes", "45 x 33cm, Black art pen, collage", "eye-lashes.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (406, "Sean Owens", "Eye  Music", "45 x 33cm, Black art pen, collage", "eye-music.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (406, "Abby Foort", "Cry Me a River", "45 x 33cm, Black art pen, collage", "cry-me-a-river.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (406, "Riley Hubbert", "Capital Eye", "45 x 33cm, Black art pen, collage", "capital-eye.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (406, "Archie Woodward", "Eye Saw", "45 x 33cm, Black art pen, collage", "eye-saw.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (397, "Amelie Plage", "The Golden Queen", "28 x 42cm, Oil pastels", "the-golden-queen.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (397, "Harriett Doherty ", "Princess in a tower ", "28 x 42cm, Oil pastels", "princess-in-a-tower.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (397, "Bethany Nixon", "A crown of emeralds", "31 x 42cm, Oil pastels", "crown-of-emeralds.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (397, "Kaitlyn Hanson", "Crown princess", "28 x 42cm, Oil pastels", "crown-princess.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (397, "Finley Lancaster", "The green eyed king", "28 x 42cm, Oil pastels", "green-eyed-king.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (397, "Ashleigh Evans", "Crown of gold", "28 x 35cm, Gold and silver pens", "crown-of-gold.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (397, "Alfie Jones", "King beard", "29 x 42cm, Oil pastels", "king-beard.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (397, "Joseph Storey", "Magic magi", "28 x 42cm, Oil pastels", "magic-magi.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (397, "Alex Whatling", "The orange king", "29 x 42cm, Pen", "orange-king.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Olivia Buckley", "Steampunk Lizard 1", "42 x 31cm, Mixed media", "steampunk-lizard-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Harry Chevannes", "Steampunk Lizard 2", "32 x 31cm, Mixed media", "steampunk-lizard-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Iwan Davies", "Steampunk Lizard 3", "42 x 31cm, Mixed media", "steampunk-lizard-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Ethan Hughes", "Steampunk Lizard 4", "32 x 31cm, Mixed media", "steampunk-lizard-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Thomas Leach", "Steampunk Lizard 5", "32 x 31cm, Mixed media", "steampunk-lizard-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Isla Reeve", "Steampunk Lizard 6", "42 x 31cm, Mixed media", "steampunk-lizard-6.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Jackson Silk-Smith", "Steampunk Lizard 7", "32 x 31cm, Mixed media", "steampunk-lizard-7.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Euan Weatherhead", "Steampunk Lizard 8", "42 x 31cm, Mixed media", "steampunk-lizard-8.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Alexander Wilkie", "Steampunk Lizard 9", "42 x 31cm, Mixed media", "steampunk-lizard-9.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Sophie Clafton", "Steampunk Mouse 1", "42 x 31cm, Mixed media", "steampunk-mouse-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Lola-May Evans", "Steampunk Mouse 2", "42 x 31cm, Mixed media", "steampunk-mouse-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Edward Groves", "Steampunk Mouse 3", "42 x 31cm, Mixed media", "steampunk-mouse-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Alexandra Howitt", "Steampunk Mouse 4", "32 x 31cm, Mixed media", "steampunk-mouse-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Oliver Moran", "Steampunk Mouse 5", "32 x 31cm, Mixed media", "steampunk-mouse-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Riaz Penisini", "Steampunk Mouse 6", "42 x 31cm, Mixed media", "steampunk-mouse-6.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Edi Raven", "Steampunk Mouse 7", "42 x 31cm, Mixed media", "steampunk-mouse-7.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Holly Spambo", "Steampunk Mouse 8", "32 x 31cm, Mixed media", "steampunk-mouse-8.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Euan Watson", "Steampunk Mouse 9", "42 x 31cm, Mixed media", "steampunk-mouse-9.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Bradley Cliff", "Steampunk Owl 1", "32 x 31cm, Mixed media", "steampunk-owl-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Abigail Dobson", "Steampunk Owl 2", "32 x 31cm, Mixed media", "steampunk-owl-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Benjamin Howes", "Steampunk Owl 3", "32 x 31cm, Mixed media", "steampunk-owl-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Ellena Reddy", "Steampunk Owl 4", "42 x 31cm, Mixed media", "steampunk-owl-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Will Taylor", "Steampunk Owl 5", "32 x 31cm, Mixed media", "steampunk-owl-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Jasmine Thompson-Davies", "Steampunk Owl 6", "32 x 31cm, Mixed media", "steampunk-owl-6.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Maisie Darlington Bullock", "Steampunk Butterfly 1", "32 x 31cm, Mixed media", "steampunk-butterfly-1.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Thomas Kealey", "Steampunk Butterfly 2", "32 x 31cm, Mixed media", "steampunk-butterfly-2.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Lucas McGauley", "Steampunk Butterfly 3", "32 x 31cm, Mixed media", "steampunk-butterfly-3.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Isabelle Pickering", "Steampunk Butterfly 4", "42 x 31cm, Mixed media", "steampunk-butterfly-4.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Alexia Sturzy", "Steampunk Butterfly 5", "32 x 31cm, Mixed media", "steampunk-butterfly-5.jpg");
INSERT INTO entry (school_year, artist, title, properties, image) VALUES (407, "Daisy Wright", "Steampunk Butterfly 6", "32 x 31cm, Mixed media", "steampunk-butterfly-6.jpg");