<?
   $this->headTitle('Contact');
   $this->headMeta()->appendName('description', 'Contact the dot-art Schools program, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">Contact</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Contact</li>
</ul>

<div class="row">

<div class="span12">

<p>If you are interested in getting involved in dot-art Schools, please see the <a href="/what">What?</a> page for further
details.</p>

<p>Alternatively, please contact us via email or phone:</p>

<table class="table table-condensed">
    <tr>
        <td>Email:</td>
        <td><a href="mailto:schools@dot-art.com">schools@dot-art.com</a></td>
    </tr>
    <tr>
        <td>Telephone:</td>
        <td>0845 017 6660</td>
    </tr>
    <tr>
        <td>Social Media:</td>
        <td><a href="https://twitter.com/dotartschools" target="_blank">
                <img src="/images/icons/twitter.png" title="Follow dot-art Schools on Twitter" alt="Twitter logo" />
            </a>
            <a href="https://www.facebook.com/dotartSchools" target="_blank">
                <img src="/images/icons/facebook.png" title="Like dot-art Schools on Facebook" alt="Facebook logo" />
            </a>
        </td>
    </tr>
</table>

</div>

</div>

</div>
