<?
   $this->headTitle('Contact');
   $this->headMeta()->appendName('description', 'Contact the dot-art Schools program, an interactive, inter school, online art competition, culminating in an exhibition of the winning students works.');
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">Contact</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Contact</li>
</ul>

<div class="row">

<div class="span12">

 <div class="row row-entry">

            <div class="span4">
            <img src="/images/2015-Exhibition/dot-art-Schools-2015-79.jpg" title="dot-art Schools Exhibition 2015" alt="dot-art Schools Exhibition 2015"/>
            </div>
            
            <div class="span4">
            <img src="/images/2015-Exhibition/dot-art-Schools-2015-53.jpg" title="dot-art Schools Exhibition 2015" alt="dot-art Schools Exhibition 2015"/>
            </div>
            
            <div class="span4">
            <img src="/images/2015-Exhibition/dot-art-Schools-2015-187.jpg" title="dot-art Schools Exhibition 2015" alt="dot-art Schools Exhibition 2015"/>
            </div>
            </div>

<p>If you are interested in getting involved in dot-art Schools, please see the <a href="/what">What?</a> page for further
details, take a look at our <a href="http://schools.dot-art.com/docs/dot-art-Schools-Teacher-Leaflet.pdf">Teachers Information
Leaflet</a> or download the <a href="http://schools.dot-art.com/docs/dot-art-Schools-Entry-Form.pdf">2015-16 Entry Form.</a></p>

<p>Alternatively, please contact us via email or phone:</p>

<table class="table table-condensed">
    <tr>
        <td>Email:</td>
        <td><a href="mailto:schools@dot-art.com">schools@dot-art.com</a></td>
    </tr>
    <tr>
        <td>Telephone:</td>
        <td>0345 017 6660</td>
    </tr>
    <tr>
        <td>Social Media:</td>
        <td><a href="https://twitter.com/dotartschools" target="_blank">
                <img src="/images/icons/twitter.png" title="Follow dot-art Schools on Twitter" alt="Twitter logo" />
            </a>
            <a href="https://www.facebook.com/dotartSchools" target="_blank">
                <img src="/images/icons/facebook.png" title="Like dot-art Schools on Facebook" alt="Facebook logo" />
            </a>
        </td>
    </tr>
</table>


</div>

</div>

<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//dot-art.us7.list-manage.com/subscribe/post?u=7a47545ee447b15126626bfa3&amp;id=fedcddfeeb" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe to our mailing list</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
</div>
<div class="mc-field-group">
	<label for="mce-MMERGE3">School </label>
	<input type="text" value="" name="MMERGE3" class="" id="mce-MMERGE3">
</div>
<div class="mc-field-group">
	<label for="mce-MMERGE4">Job Title </label>
	<input type="text" value="" name="MMERGE4" class="" id="mce-MMERGE4">
</div>
<div class="mc-field-group input-group">
    <strong>Who are you? </strong>
    <ul><li><input type="checkbox" value="1" name="group[11305][1]" id="mce-group[11305]-11305-0"><label for="mce-group[11305]-11305-0">I am from a school interested in taking part</label></li>
<li><input type="checkbox" value="2" name="group[11305][2]" id="mce-group[11305]-11305-1"><label for="mce-group[11305]-11305-1">I am just interested in keeping in touch</label></li>
</ul>
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_7a47545ee447b15126626bfa3_fedcddfeeb" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
</div>