<?php
   $this->headTitle('Teachers Corner');
   $this->headMeta()->appendName('description', 'Teachers Corner 2020 - an online exhibition showing that teachers are artists too!);
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">News</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">News <span class="divider">/</span></li>
  <li class="active">News</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>

<!-- Put SPAN6 DIVs here for each news item:  -->

<div class="row">
		<h3>Holly Ayre</h3>
</div>
  
<div class="row">
		<h4>Witchford Village college, Ely</h4>
</div>   

<div class="row">
		<p>As an artist I have always been experimental, trying out various techniques and methods to see how far I am able to push myself and the materials I am working with. 

During my degree, where I studied Fine Art, I was primarily interested in the fine line that exists between painting and sculpture. I created pieces using traditional 'painting' materials and turned them into sculptural works Paint Sculpture #8 is an example of one of these pieces.

Portraits have always interested me for the way they capture moments in time. I enjoy working with pencil as I am able to focus on details and learn a person's face and personality whilst studying and replicating them through my drawing. Aneilla #1 is a piece I have only recently created of my daughter, showing her inquisitive nature. 

Acrylic pours are something I found whilst in the early stages of my teacher training. I use this technique with all my classes from years 7 upwards. I have found it to be enjoyable and exciting, especially for my students, who are amazed at all the different effects they can achieve and how everyone is able to access this method and create amazing work, no matter their prior ability. Galaxy and Space #3 was a piece I created to show my students how to use the 'Dirty Flip Pour' technique, which I made as they watched during a demonstration. </p>
</div> 

<div class="row"> 
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/aneilla-h-ayre.jpg">
      
    <p><b>Aneilla #1</b</p>
    <p>Pencil</p>

<div class="row"> 
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/galaxy-and-space-h-ayre.jpg">
      
    <p><b>Galaxy and Space #3</b</p>
    <p>Acrylic Paint and flow mediums</p>
    
<div class="row"> 
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/paint-sculpture-h-ayre.jpg">
      
    <p><b>Paint Sculpture #8</b</p>
    <p>Acrylic Paint</p>
	
</div>

</div>

<!--
	<div class="span6">
		<h3>Video: Beth Explains dot-art Schools</h3>
		<iframe width="550" height="396" src="http://www.baytvliverpool.com/vod/iframe/?vid=JBV527cd70c99492" frameborder="0" scrolling="no" style="overflow:hidden;"></iframe>
	</div> 
--->