<?php
   $this->headTitle('Teachers Corner');
   $this->headMeta()->appendName('description', 'Teachers Corner 2020 - an online exhibition showing that teachers are artists too!');
?>

<div class="container lowered">

<div class="jumbotron news">
<h1 class="what">Teachers Corner</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Exhibitions</li>
</ul>

<div class="row">
<p class="span12"></p>
</div>

<!-- Put SPAN6 DIVs here for each news item:  -->

<div class="row">
<div class="span12">
<p>Teachers Corner 2020 is a celebration of creativity which was extended to all those working in education across the country during the COVID-19 pandemic.
We wanted to demonstrate to students that teachers are artists too, as well as highlight the importance of staying creative during difficult times. 
The response was fantastic, with almost 40 people submitting an amazing array of art works, many created while in lockdown. 
Thanks to everyone who contributed and shared their talents!</p>

<p>We would also like to say a huge thank you to <b>Arts Council England</b> whose Emergency Funding made this project possible!</p>

</div>
</div>

<div class="row">
<div class="span12">

		<h3>Anita Chamberlain, British International School, Stavanger, Norway</h3>
        </div>
        </div>
   
<div class="row">
<div class="span12">
		<p>The work was completed during the lock down period due to Covid-19. They are part of a series of images where I have used lines, shapes and colours to represent feelings. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/daydreaming-a-chamberlain.jpg">
      <p>.</p>  
    <p><i>Daydreaming #1</i>, Ink, pastels</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/eggs-a-chamberlain.jpg">
    <p>.</p>  
    <p><i>Eggs</i>, Ink, pastels</p>
    </div>

    
      
</div>

   
   
   
 <!----------NEXT ARTIST ------>

<div class="row">
<div class="span12">

		<h3>Ann Murphy, St. Michael's Catholic Primary School, Widnes</h3>
        </div>
        </div>
   
<div class="row">
<div class="span12">
		<p>Art has always played a big part in my life. On a warm sunny Saturday morning I would take my sketch book and pencil to the corner of my street and draw what I could see. Buildings at that time fascinated me especially my old school which I first drew aged 9 and have re drawn recently. Pencil is my favourite medium to work with and faces soon became one of my interests for drawing facial features. Painting also allowed me to explore different techniques and styles and allowed me to become creative by introducing a variety of unusual items to paint with which is something I encourage the children in my art classes to explore with also.    </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 

   
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/chief-a-murphy.jpg">
      <p>.</p>  
    <p><i>Indian Chief</i>, Pencil</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/lavender-pot-a-murphy.jpg">
    <p>.</p>  
    <p><i>Lavender Pot</i>, Watercolour</p>
    </div>

       	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/my-old-school-a-murphy.jpg">
    <p>.</p>  
    <p><i>My Old School</i>, Pencil</p>
    </div>

    
      
</div>
   
   
   
 <!----------NEXT ARTIST ------>
 
 <div class="row">
<div class="span12">

		<h3>Anne Kelly, Rice Lane Primary, Liverpool</h3>
        </div>
        </div>
   
<div class="row">
<div class="span12">
		<p>From a very young age, art has always been my passion. It helps me to relax and to switch off from the world. I love to inspire my pupils with art; I believe that art is crucial to their development and well being. Art is accessible to all- it is inclusive- it does not discriminate- art is all around us. I love the excitement on children's faces when they know that we are just about to begin an art lesson; it is so special to them and they know that they will have the opportunity to express themselves. 

I'm not sure if I have a particular style when it comes to my own artwork, I tend to have an idea and then roll with it! I love the use of bright, eye-catching colours and I often like to contrast colour with pencil. Creating art for my friends and family is one of my favourite things to do- I love the opportunity to catch a glimmer of their personality through my art. Animals are one of my favourite subjects when I create a piece of art- they are so wise looking and have so much expression- I love the intricate detail around their eyes! </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 

   
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/frida-covid-a-kelly.jpg">
      <p>.</p>  
    <p><i>Frida Covid</i>, Acrylic Paint and Pencil</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/flower-crowns-a-kelly.jpg">
    <p>.</p>  
    <p><i>Animals in Flower crowns</i>, Acrylic Paint and Pencil</p>
    </div>

       	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/regal-tiger-a-kelly.jpg">
    <p>.</p>  
    <p><i>Regal Tiger</i>, Acrylic</p>
    </div>

    
      
</div>
   
   
   
 <!----------NEXT ARTIST ------>
 
 <div class="row">
<div class="span12">

		<h3>Danny Metz, Blackmoor Park Junior School, Liverpool</h3>
        </div>
        </div>
   
<div class="row">
<div class="span12">
		<p>I’m learning watercolour using a book where you can practise some of Turner’s techniques. I used a chapter about painting moonlight scenes to paint the smaller pictures. The larger beach scene is oil on canvas. I was trying to paint in thin layers. It’s not quite finished but it’s nearly there.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 

   
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/english-bay-vancouver-d-metz.jpg">
      <p>.</p>  
    <p><i>English Bay, Vancouver</i>, Oil on Canvas</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/moonlight-liverpool-d-metz.jpg">
    <p>.</p>  
    <p><i>Moonlight Liverpool</i>, Watercolour and White Goache</p>
    </div>

       	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/moonlight- scene-d-metz.jpg">
    <p>.</p>  
    <p><i>Moonlight Scene</i>, Watercolour and White Goache</p>
    </div>

    
      
</div>
   
   
   
 <!----------NEXT ARTIST ------>
 
            
 <div class="row">
<div class="span12">

		<h3>Diane Sheron, Stepping stones PRU, Lancaster</h3>
        </div>
        </div>
   
<div class="row">
<div class="span12">
		<p>Made from driftwood collected from the beach.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 

   
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/driftwood-d-sheron.jpg">
      <p>.</p>  
    <p><i>Driftwood</i>, Wood</p>
    </div>

    
      	
      
</div>
   
   
   <!----------NEXT ARTIST ------>
 
            
 <div class="row">
<div class="span12">

		<h3>Emma Jacobs, Frith Manor Primary School, London</h3>
        </div>
        </div>
   
<div class="row">
<div class="span12">
		<p>I try not to be too precious about the materials I use, especially during lockdown. I've recycled Amazon brown packaging paper for 
        painting on to make collages. I've used wallpaper lining from under the stairs to paint on and taken inspiration from nature and world 
        events. I've also set myself daily exercises like 1 hour time limits to focus my ideas and approach. I've learnt to value my childlike 
        marks and take them seriously. As an EYFS teacher I am inspired by the work of my pupils and how naturally they express themselves. 
        The artwork I am submitting are painted collages on wallpaper lining and acrylic paint on board.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 

   
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/bristol-e-jacobs.jpg">
      <p>.</p>  
    <p><i>Bristol</i>, Collage</p>
    </div>


         <div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/lockdown-tulips-e-jacobs.jpg">
      <p>.</p>  
    <p><i>Lockdown Tulips</i>, Acrylic on Board</p>
    </div>
    
    
    <div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/poppies-and-crows-e-jacobs.jpg">
      <p>.</p>  
    <p><i>Poppies and Crows</i>, Collage</p>
    </div>
      	
      
</div>
   
   
 <!----------NEXT ARTIST ------>
 
 
 <div class="row">
<div class="span12">

		<h3>Emma Wright, The Oaks Academy, Cheshire</h3>
        </div>
        </div>
   
<div class="row">
<div class="span12">
		<p>I love photography as a vehicle of expression combining technical skills with creativity. I believe that photographs should evoke an emotion or memory that is captured to keep forever. My favourite photographic subjects are found within nature such as flowers, animals and landscapes. I also enjoy experimenting with different techniques and using accessories such as filters and crystals to add additional colour to my photographs and develop my ideas further. I love the creative potential of software such as Lightroom and Photoshop but when I photograph nature I like to keep any editing I do natural so that it suits what I am photographing. I think Ansel Adams who said &#039;you don&#039;t take a photograph, you make it&#039; and also Henri Cartier-Bresson who said &#039;for me, the camera is a sketchbook, an instrument of intuition and spontaneity&#039; perfectly define the power of photography.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 

   
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/cherry-blossom-paradise-e-wright.jpg">
      <p>.</p>  
    <p><i>Cherry Blossom Paradise</i>, Photography</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/meerkat-alert-e-wright.jpg">
    <p>.</p>  
    <p><i>Meerkat Alert</i>, Photography</p>
    </div>

       	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/dandelion-dreams-e-wright.jpg">
    <p>.</p>  
    <p><i>Dandelion Dreams</i>, Photography</p>
    </div>

    
      
</div>
   
   
   
 <!----------NEXT ARTIST ------>
 
 
 <div class="row">
<div class="span12">

		<h3>Fiona Johnston, Simon Balle Through School, Hertford</h3>
        </div>
        </div>
   
<div class="row">
<div class="span12">
		<p>Ultimate art in the garden during lockdown. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 

   
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/mona-lisa-f-johnston.jpg">
      <p>.</p>  
    <p><i>Mona Lisa</i>, Photography</p>
    </div>


   </div>  
   
 <!----------NEXT ARTIST ------>
 
 
 <div class="row">
<div class="span12">

		<h3>Helen Perry, Andover College, Hampshire</h3>
        </div>
        </div>
   
<div class="row">
<div class="span12">
		<p>My work is process driven and largely based around science and materials. Primarily focuses on microscopic detail and chemistry and is print and ceramics based </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 

   
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/kaolin-h-perry.jpg">
      <p>.</p>  
    <p><i>Kaolin</i>, Porcelain and Wood</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/coppercarb-h-perry.jpg">
    <p>.</p>  
    <p><i>Coppercarb</i>, Terracotta and Walnut</p>
    </div>

       	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/gold-h-perry.jpg">
    <p>.</p>  
  <p><i>Gold</i>, Collages collographs</p>
    </div>

    
      
</div>
   
   
   
 <!----------NEXT ARTIST ------>
 
 
 <div class="row">
<div class="span12">

		<h3>Helen Wade, The Heath School, Liverpool</h3>
        </div>
        </div>
   
<div class="row">
<div class="span12">
		<p>Hello everyone, hope you've enjoyed spending time making art while we were all in lockdown. I have. 
My best bits were watching "Grayson's Art Club" on channel4 every week, and then having a go. I love Grayson Perry, his laugh is brilliant and it makes me smile. I loved seeing him in his studio, with his cool wife Phil, Kevin their cat. I enjoyed seeing guests like Noel Fielding and Harry Hill. It's been great fun. 
I messaged our students and sent the link to our staff to watch it too. Loads of them did, they even had a go, and they found it really uplifting. That's what I love about Art.
I liked Animal Week so I decided when I was in school with our keyworkers students, I did an afternoon of art. They all had a go, starting by watching a bit of GraysonsArtClub, then looking through books about animals and choosing one they wanted to have a go at. 
For my go I chose Japanese Koi Carp, theyre beautiful they make ripples in the water when they swim and their colours are so bold. I used oil pastels because they're quick and easy to blend, you can make lots of bright colours and you can even scratch back into them so they're even great for mark-making. It was a hot, sunny day so I did it outside (like Liza Tarbuck in her episode). My cat Foxie joined me and I played  bbc6music so I had a top afternoon.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 

   
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/koi-h-wade.jpg">
      <p>.</p>  
    <p><i>Koi</i>, Oil Pastel on Sugar Paper</p>
    </div>

    
      
</div>
   
   
   
 <!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Holly Ayre, Marshfield's School, Peterborough. </h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>As an artist I have always been experimental, trying out various techniques and methods to see how far I am able to push myself and the materials I am working with. 

During my degree, where I studied Fine Art, I was primarily interested in the fine line that exists between painting and sculpture. I created pieces using traditional "painting" materials and turned them into sculptural works Paint Sculpture #8 is an example of one of these pieces.

Portraits have always interested me for the way they capture moments in time. I enjoy working with pencil as I am able to focus on details and learn a persons face and personality whilst studying and replicating them through my drawing. Aneilla #1 is a piece I have only recently created of my daughter, showing her inquisitive nature. 

Acrylic pours are something I found whilst in the early stages of my teacher training. I use this technique with all my classes from years 7 upwards. I have found it to be enjoyable and exciting, especially for my students, who are amazed at all the different effects they can achieve and how everyone is able to access this method and create amazing work, no matter their prior ability. Galaxy and Space #3 was a piece I created to show my students how to use the "Dirty Flip Pour" technique, which I made as they watched during a demonstration. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/aneilla-h-ayre.jpg">
      <p>.</p>  
    <p><i>Aneilla #1</i>, Pencil</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/galaxy-and-space-h-ayre.jpg">
    <p>.</p>  
    <p><i>Galaxy and Space #3</i>, Acrylic Paint and flow mediums</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/paint-sculpture-h-ayre.jpg">
     <p>.</p> 
    <p><i>Paint Sculpture #8,</i>, Acrylic Paint</p>
    </div>
	
</div>



   <!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Ildiko Szabo, St Hildas, Liverpool</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I use freeform knitting, crochet and fabric manipulation techniques. As a former costume maker, I take inspiration form the world of theatre, books, and fantasy. For technical and construction skills I study natural forms, architecture and folk/tribal arts and crafts. My love of vibrant colours comes from my rich Hungarian heritage of folk embroidery.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/four-seasons-masks-i-szabo.jpg">
      <p>.</p>  
    <p><i>Four Seasons and The Scarlet Pimpernel</i>, Freeform knitting/crochet & fabric manipulation</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/springtime-in-autumn-i-szabo.jpg">
    <p>.</p>  
    <p><i>Springtime in Autumn </i>, Freeform knitting/crochet</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/abstract-i-szabo.jpg">
     <p>.</p> 
    <p><i>Abstract,</i>, Freeform knitting/crochet</p>
    </div>
	
</div>



<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Iraam Naaz, Iqra Academy, Bradford</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>Art is a form of expressing myself. It is a therapeutic outlet which enables me to escape from busy, everyday life. Art is my favourite subject to teach because it never fails to put a smile on the faces of those I teach. I believe every child is an artist and as their teacher, I hope to encourage them with my own artwork. My art is inspired by the beautiful world around me. I like to use a range of materials, but I have recently enjoyed the challenge of mastering the art of coloured pencils. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/parrot-iram-naaz.jpg">
      <p>.</p>  
    <p><i>Colours of Nature</i>, Coloured Pencils</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/tranquility-iram-naaz.jpg">
    <p>.</p>  
    <p><i>Tranquility</i>, Coloured Pencils</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/wild-tiger-iram-naaz.jpg">
     <p>.</p> 
    <p><i>Wild,</i>, Coloured Pencils</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Ivan McKane, Ballymoney High, County Antrim, Northern Ireland</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>Digital art produced using XP Pen tablet and Clip Studio Software. My graphic Design background has steered me in working with clean cut realism. The ability to zoom in really close to render, especially when your eyesight is failig, is a blessing.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/patience-of-a- king-i-mckane.jpg">
      <p>.</p>  
    <p><i>Patience of a King</i>, Digital</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/redeemed-i-mckane.jpg">
    <p>.</p>  
    <p><i>Redeemed</i>, Digital</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/furlough-i-mckane.jpg">
     <p>.</p> 
    <p><i>Furlough,</i>, Digital</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Jayne Worrall, Meadowside CP & Nursery School, Warrington</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I love all kinds of creative arts; especially watercolours and mixed media. I have been taking watercolour lessons for a couple of years now and the artwork I have submitted have been inspired by those lessons. I like nature and landscapes and am slowly finding my 'style'.  Art helps to relax and focus me and I love getting 'lost in the moment' through painting. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/winter-j-worrall.jpg">
      <p>.</p>  
    <p><i>Winter</i>, Watercolour</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/teasles-j-worrall.jpg">
    <p>.</p>  
    <p><i>Teasles</i>, Watercolour</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/reflections-j-worrall.jpg">
     <p>.</p> 
    <p><i>Reflection,</i>, Watercolour</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>


   
<div class="row">
<div class="span12">

		<h3>Jena Olsen, One School Global, Biggleswade</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>Drawing has always given me a deep sense of satisfaction, delving deep into the intricate details and the meditative affects brought on by the repetitive process of looking, shading, mark making, checking, assessing, correcting, each drawing being a challenging and fulfilling journey. 
During lockdown I have been exploring my creative voice and how I can use art to comment on the challenges we face as human beings at this the defining, pivotal point in our history. 
"In My Lifetime" is about racial inequality and discrimination experienced in the lifetimes of some still living today and how we need to learn from history to create a fairer world for all.
"The Last Elephant" represents how the fragile balance of earths’ future lies in our hands and the possible outcomes if we continue on our destructive trajectory.
"We Will Not Be Silenced" pays tribute to all those who demonstrate against inequality and the earths destruction and the strength of today’s youth in having their voices heard.
My process is to draw from photographs using a variety of materials including biro, pen, chalks and colour pencils. I then use photoshop for editing and background compositions
</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/jena-olsen-in-my-lifetime.jpg">
      <p>.</p>  
    <p><i>In My Lifetime</i>, Biro and Photoshop</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/jena-olsen-we-will-not-be-silenced.jpg">
    <p>.</p>  
    <p><i>We Will Not Be Silenced</i>, Chalk, Charcoal and Photoshop</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/jena-olsen-the-last-elephant.jpg">
     <p>.</p> 
    <p><i>The Last Elephant</i>, Biro Photoshop </p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Jim Collis, Alsop High, Liverpool</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p></p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/iglesia-j-collis.jpg">
      <p>.</p>  
    <p><i>Iglesia Espanola </i>, Acrylic on Canvas</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/moroccan-bird-j-collis.jpg">
    <p>.</p>  
    <p><i>Moroccan Bird</i>, Acrylic on Canvas</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/almond-blossom-j-collis.jpg">
     <p>.</p> 
    <p><i>Almond Blossom,</i>, Acrylic and Plaster on Canvas</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Josephine Riley, The Oldershaw Academy, Liverpool</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>Shell art , collection from local beaches in acrylic, pen and varnish, I started by creating local landscapes for friends and family who were isolated bringing a little bit of the coast to their doorstep and this then inspired miniatures of famous icons and paintings that people have requested and then framed them as gifts </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/shell-art-1-j-riley.jpg">
      <p>.</p>  
    <p><i>Shell Art</i>, Acrylic</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/shell-art-2-j-riley.jpg">
    <p>.</p>  
   <p><i>Shell Art</i>, Acrylic</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/shell-art-3-j-riley.jpg">
     <p>.</p> 
   <p><i>Shell Art</i>, Acrylic</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Kari Fry, Luttons Primary School, North Yorkshire</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I wrote a poem about two pet rabbits that I used to have. They were exceedingly funny and I thought the poem would work as a children's book. I have been waiting for an opportunity to illustrate the poem and with Covid 19, I have had a lot of extra time on my hands!

My favourite illustrators are Colin Thompson, Jill Barklem and Graeme Base. They all have this unique ability to enhance their texts with detailed illustrations depicting quirky characters that capture imaginations and inspire and challenge ideas. 

I really liked the concept of creating a book where within the pages, other narratives are being told, a myriad of short stories wrapped up in one spine -all it needs is one reader to spot the details and be inspired.

When creating the pages within my 'book' I hummed and hawed about its layout. Initially thinking A4 sheets with one single picture would be enough, but no matter how I plotted it out, it didn't flow. I eventually had a 'Eureka' moment and changed the layout to a 'comic book'style. This has allowed me to have free rein on each page and just let my imagination take flight.

I sketched all the work first onto Bristol board, then used a black fine tip pen to go over all of the lines, adding any depth with cross hatching and shade. I then used pro-markers to colour in the pictures, adding liquid acrylic on top to give a greater depth and intensity to specific scenes such as the grass and Bert's food.  

Finally, I printed the text onto acetate and changed font, size and shape depending on the words to accentuate the context.  
I have included the firsy three pages of Bert and Houdini's adventure. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/bert-and-houdini-k-fry.jpg">
      <p>.</p>  
    <p><i>Bert and Houdini</i>, Pen, Promarker, Liquid Acrylics and Acetate</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/bert-stopped-k-fry.jpg">
    <p>.</p>  
    <p><i>Bert Stopped</i>, Pen, Promarker, Liquid Acrylics and Acetate</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/so-the-bunnies-k-fry.jpg">
     <p>.</p> 
    <p><i>So The Bunnies,</i>, Pen, Promarker, Liquid Acrylics and Acetate</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Kate Roberts, St.Hilda's CE High School, Liverpool</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I had to rethink my approach during lockdown. As my family and I are all working at home, I have less space to work. With nowhere to get my paints out,  I have taught myself to use Procreate on the IPad. I have been doing animal portraits for friends and family. I find being immersed in a creative process really therapeutic, which has been really important to me during lockdown. Drawing is such a mindful activity and I have loved learning a new technique. I have drawn animals I know well and tried to capture their character. Cocoa was a pony at my local riding school who taught so many children, including my daughter to ride. He sadly died this year and his gentle nature is much missed. Coco is my own dog, she is such good company, full of mischief and we all adore her. Timor is a beautiful Lusitano stallion trained in dressage. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/cocoa-k-roberts.jpg">
      <p>.</p>  
    <p><i>Cocoa</i>,  Digital painting</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/coco-k-roberts.jpg">
    <p>.</p>  
    <p><i>Coco</i>,  Digital painting</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/timor-k-roberts.jpg">
     <p>.</p> 
    <p><i>Timor,</i>,  Digital painting</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Katie Corner, The Federation of Abbey Schools, Darlington</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I work with linocut print I am inspired by lots of things including history, nature and popular culture. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/good-queen-bess-k-corner.jpg">
      <p>.</p>  
    <p><i>Good Queen Bess</i>, Linocut print hand painted with watercolour</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/tawny-owl-k-corner.jpg">
    <p>.</p>  
    <p><i>Tawny Owl</i>, Linocut Print</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/the-mandalorian-k-corner.jpg">
     <p>.</p> 
    <p><i>The Mandalorian,</i>, Ink Marbeling and Linocut print</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Lauran Hopkins, St Martin’s School, Caerphilly</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I like to paint figures in colour. There’s an element of mystery in the paintings as you can’t see the faces. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/acceptance-l-hopkins.jpg">
      <p>.</p>  
    <p><i>Acceptance</i>, Acrylic</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/embrace-l-hopkins.jpg">
    <p>.</p>  
    <p><i>Embrace</i>, Acrylic</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/she-l-hopkins.jpg">
     <p>.</p> 
    <p><i>She,</i>, Acrylic</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Lauren Kelly, The Colne Community School, Colchester</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I have been making lino prints for the last 10 years. It stemmed from an MA in Education that I did after my NQT year and I got to take part in some practical modules, including printmaking. 
I mainly make my prints during school holidays. I am fascinated with objects and try to draw one thing a day. 
This first print started at the beginning of lockdown when I drew a different packet of sweets each day (I started buying from the local shop, then found a local sweet shop that did deliveries). I put the best sweet drawings together to make this reduction print called Retro Sweets. 
The second entry is from a series of drawings I did around Christmas time inspired by tarot cards and natural forms. I used an encyclopaedia of plant and animal species along with diagrams of the moon phases and symbols to help create the design. It led to 3 more similar prints, it is very different to my usual style! 
My third print has been made during lockdown and is inspired by the connections we have lost during our time separated from family and friends. 
</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/retro-sweets-l-kelly.jpg">
      <p>.</p>  
    <p><i>Retro Sweets</i>, Lino Print</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/pale-pink-moonlight-l-kelly.jpg">
    <p>.</p>  
    <p><i>Pale Pink Moonlight</i>, Lino Print</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/connection-l-kelly.jpg">
     <p>.</p> 
    <p><i>Connection,</i>, Lino Print</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Libby Witney, The Hurst Community College, Tadley, Hampshire</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>Drawing is where all my artwork starts off, then I either work into the original or transfer them into a screen print so that I can easily experiment with different colours and colour combinations. I love drawing animals in all their expressions, as it makes me laugh and gives me insight into their character.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/mrs-rhino-l-witney.jpg">
      <p>.</p>  
    <p><i>Mrs Rhino</i>, Ink and Pen</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/mr-toucan-l-witney.jpg">
    <p>.</p>  
    <p><i>Mr Toucan</i>, Ink and Pen</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/miss-ele-l-witney.jpg">
     <p>.</p> 
    <p><i>Miss Ele,</i>, Ink and Pen</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Linda Harvey, Archbishop Holgate's School, York</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>The inspiration for my work mainly comes from the places I visit. I take photographs of anything that catches my eye as I like to capture a moment instantly.  My photographs then give me a starting point from which my work evolves. I will often work on several pieces at a time, as I enjoy an expressive and experimental way of working.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/radial-engine-l-harvey.jpg">
      <p>.</p>  
    <p><i>Radial Engine</i>, Textiles</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/under-attack-l-harvey.jpg">
    <p>.</p>  
    <p><i>Under Attack</i>, Textiles</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/castaway-l-harvey.jpg">
     <p>.</p> 
    <p><i>Castaway,</i>, Textiles</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Lucy Prime, Dr Challoner's Grammar School, Buckinghamshire</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I have an illustrative approach to my work and create drawings, lino prints and collages inspired by everyday observations. This selection of work reflects my time spent living and teaching in Egypt, Malaysia and now back in England.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/pomegranate-l-prime.jpg">
      <p>.</p>  
    <p><i>Pomegranate</i>, Coloured Pencil and Brown Paper</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/harmony-stitch-by-stitch-l-prime.jpg">
    <p>.</p>  
    <p><i>Stitch by Stitch</i>, Lino Print and Watercolour</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/ cranes-l-prime.jpg">
     <p>.</p> 
    <p><i>Cranes,</i>, Lino Print and Collaged Papers</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Lynn Mason, Childwall Abbey School, Liverpool</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I made these portraits of my daughter retrospectively, using photographs I had taken of her as a baby.  I chose to work in clay because I love the permanence of ceramic objects.  I like to imagine that fragments of my work might be unearthed centuries from now just as Roman pottery is excavated today!  Making these pieces was very labour-intensive and time-consuming. I could get lost in the making process which was very therapeutic, a bit like meditation.  I also like the transformative and elemental qualities of working with clay.  Potters utilise earth, water, fire and air in their creative process and you never quite know what finished result you might get when you finally open up the kiln door, which is very exciting.  </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/leap-baby-l-mason.jpg">
      <p>.</p>  
    <p><i>Lepa Baby</i>, Terracotta, Slip, Underglaze and Glaze</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/red-hat-l-mason.jpg">
    <p>.</p>  
    <p><i>Red Hat</i>, Terracotta, Slip, Underglaze and Glaze</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/asleep-l-mason.jpg">
     <p>.</p> 
    <p><i>Asleep,</i>, Terracotta, Slip, Underglaze and Glaze</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Lynne Calland, All Hallows Catholic High School, Liverpool</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I used the time during lockdown to learn a new technique. I wanted to use local wildflowers and pieces of seaweed from my nearest beach (St Anne’s) to incorporate into the work. These pieces require sunshine to process so the months of April and May were ideal.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/crow-l-calland.jpg">
      <p>.</p>  
    <p><i>Crow</i>, Cyanotype</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/wildflowers-l-calland.jpg">
    <p>.</p>  
    <p><i>Wildflowers</i>, Cyanotype</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/seahorse-l-calland.jpg">
     <p>.</p> 
    <p><i>Seahorse,</i>, Cyanotype</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Maxine Mason, South Charnwood High School, Leicestershire</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I have always loved to draw and paint since childhood. I like to use photographs for inspiration and pretty much make up my methods as I go along, having never had any formal training in art.  I love to experiment with all kinds of mediums and styles and learn from tutorials on the internet.  I was introduced to oils by an elderly neighbour who kindly gave me a set after seeing some acrylic paintings I had done. When I told him I had no idea how to use oils, he encouraged me to 'just have a go' and I am so glad I did. I always turn to oils when I have time for a larger project and I have produced several pet portraits for friends. These are just a few examples my work.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/stanley-and-alfie-m-mason.jpg">
      <p>.</p>  
    <p><i>Stanley and Alfie</i>, Oil on Canvas</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/amsterdam-sunset-m-mason.jpg">
    <p>.</p>  
    <p><i>Amsterdam Sunset</i>, Oil on Canvas</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/marks-cat-m-mason.jpg">
     <p>.</p> 
    <p><i>Marks Cat,</i>, Oil on Canvas</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Nadia Zuberi, Edmonton County School, London</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I am a multi disciplinary artist. My degree was in theatre and costume and design, and I've always been interested in working in and using a variety of media, materials and techniques. Recently however, I have been painting more, focusing on documenting and repetitions of experiences, people, or objects. I also like to create work that is surreal, or has unusual combinations.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/skull-and-bows-n-zuberi.jpg">
      <p>.</p>  
    <p><i>Skulls and Bows</i>, Acrylic on Canvas</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/outside-in-n-zuberi.jpg">
    <p>.</p>  
    <p><i>Outside In</i>, Acrylic on Paper</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/abstract-cell-n-zuberi.jpg">
     <p>.</p> 
    <p><i>Abstract Cell,</i>, Ink, pen, and stamps, digital repeat print</p>
    </div>
	
</div>

  <!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Natalie Walford, Aldercar High School, Derbyshire</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>Following relocation I struggled to get a teaching position. During that term I turned my hand to pet portrait commissions, who knew they would be so popular? They saw me through before I landed my current job. Was good to remind myself what I could actually do</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/miffy-n-walford.jpg">
      <p>.</p>  
    <p><i>Miffy</i>, Acrylic</p>
    </div>

    
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Peter Radburn, St Julie's, Liverpool</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>These are my latest portraits using colour pencil as my chosen medium.
The first portrait is of Dennis Hardiman and he is the Executive Head Teacher at St Cuthbert's and St Sebastian's and he (like me) is retiring from teaching this year. He hasn't seen this yet so he might be in for a surprise when he logs in to the DOT Art site!
The second portrait is of my Nana Pat who graced the lives of all who met her for 96 years. Great Nan to my own kids she was truly great in every respect. Our Saturday's have never been the same since our Nan said 'night and god bless' to this world.
The third portrait is of me and my brother Mike who lives in Tasmania and is from a photograph that was taken of us when we were at St Cecilia's junior school around 1972. On a recent visit to the UK, we recreated the photo as a more 'mature' version with alarming similarity to the original (allegedly)!</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/mr-dennis-hardiman-p-radburn.jpg">
      <p>.</p>  
    <p><i>Mr Dennis Hardiman</i>, Colour Pencil</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/great-nana- pat-p-radburn.jpg">
    <p>.</p>  
    <p><i>Great Nana Pat</i>, Colour Pencil</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/pete-and-mike-p-radburn.jpg">
     <p>.</p> 
    <p><i>Pete and Mike,</i>, Colour Pencil</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Rachael Marchant, Tividale Community Primary School, West Midlands,</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I draw things that inspire me. From seeing something in real life, to looking at artists work.  The art that I create makes me feel happy...content. During this uncertain time, I need to feel that I’m giving something back to those around me. That I have a purpose while not teaching. Art and being creative is my way of doing this. It makes me feel complete. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/baxter-r-marchant.jpg">
      <p>.</p>  
    <p><i>Baxter</i>, Ink, Chalk and pencil</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/peacock-r-marchant.jpg">
    <p>.</p>  
    <p><i>Peacock</i>, Pencil</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/snoopy-britto-r-marchant.jpg">
     <p>.</p> 
    <p><i>Snoopy Britto,</i>, Pencil, Chalk</p>
    </div>
	
</div>


<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Rachel Veldtman, Caterham School, Surrey</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>Recently I have been developing digital paint and collage fusions using a range of drawing apps.
I explore botanicals and places that evoke memory or imagination.
I also painted my air plants in a glass orb as a visual metaphor of lockdown </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/horniman-hothouse-r-veldtman.jpg">
      <p>.</p>  
    <p><i>Horniman Hothouse </i>, Digital Painting</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/airplants-r-veldtman.jpg">
    <p>.</p>  
    <p><i>Airplants in glass orb (lockdown 2020)</i>, Digital Painting</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/deptford-montage-r-veldtman.jpg">
     <p>.</p> 
    <p><i>Deptford Montage</i>, Digital Painting</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Samantha Rugen, Arnot St Mary, Liverpool</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>To celebrate my son’s 16th birthday (in lockdown!) I was inspired to draw for the first time in years! </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/elias-s-rugen.jpg">
      <p>.</p>  
    <p><i>Elias</i>, Pencil</p>
    </div>

    
      
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Sol Marles, West Kirby School and College, Wirral</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>"The purpose of art is to wash the daily dust of life from our souls" (Pablo Picasso) </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/owl-s-marles.jpg">
      <p>.</p>  
    <p><i>Owl</i>, Pastels</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/moon-tree-s-marles.jpg">
    <p>.</p>  
    <p><i>Moon Tree</i>, Ink</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/elephants-s-marles.jpg">
     <p>.</p> 
    <p><i>Elephants</i>, Charcoal and pen</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Sophie Jimenez, Edmonton County School, London</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I am a printmaker, but I have been experimenting with all types of media recently.  My last big project was an illustrated children's story based on a Chinese princess. These images have all been created while in 'lock down'.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/artistic-pebbles-s-jimenez.jpg">
      <p>.</p>  
    <p><i>Artistic Pebbles</i>, Acrylic paint and posca pens on pebbles</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/sketchbook-chinese-princess-s-jimenez.jpg">
    <p>.</p>  
    <p><i>Sketchbook Chinese Princess</i>,Pen on Paper</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/covid-19-ear-s-jimenez.jpg">
     <p>.</p> 
    <p><i>Covid-19 Ear</i>, Digital</p>
    </div>
	
</div>


<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Susan Smart, Acton Primary Academy, Cheshire</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I have a very open approach to different techniques and mediums. I enjoy exploring how to create art using many layers to achieve the finished piece.</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/stormy-skies-s-smart.jpg">
      <p>.</p>  
   <p><i>Stormy Skies</i>, Chalk Pastels</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/girl-with-emerald-earring-s-smart.jpg">
    <p>.</p>  
    <p><i>Girl With Emerald Earring</i>, Multimedia</p>
    </div>

    
      
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Tracey Evans, Heolddu Comprehensive School, Caerphilly</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I have submitted three portraits. I have always been fascinated by the human face. First portrait is of Claire Balding as I am taking part in sky portrait artist of the week. The second is of Abby, my niece, for her birthday. The third is one of give different portraits I have done for Tom Croft's initiative to offer free portraits for nhs heroes. </p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/claire-balding-t-evans.jpg">
      <p>.</p>  
    <p><i>Clare Balding</i>, Soft Pastels</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/abby-t-evans.jpg">
    <p>.</p>  
    <p><i>Abby</i>, Pencil</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/becky-t-evans.jpg">
     <p>.</p> 
    <p><i>Becky</i>, Oils</p>
    </div>
	
</div>

<!----------NEXT ARTIST ------>
   
<div class="row">
<div class="span12">

		<h3>Vanessa Heron, Rainham Mark Grammar School, Kent</h3>
        </div>
        </div>   

<div class="row">
<div class="span12">
		<p>I am a ceramics enthusiast and have helped introduce clay work into our school since we bought a kiln two years ago. I also go to pottery evening classes at my local adult education centre. I miss both! I’m working on a series of pots for Oscar Wilde’s family and friends, as Im Secretary of the Oscar Wilde Society. www.oscarwildesociety.co.uk Since lockdown and school closing, I’ve made a lot of pots, which are sitting in my cellar unfired!</p>
</div> 
</div>

<p>.</p> 

<div class="row"> 
    
    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/lockdown-pots-v-heron.jpg">
      <p>.</p>  
    <p><i>Lockdown Pots</i>, Hand coloured porcelain</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/three-green-carnation-v-heron.jpg">
    <p>.</p>  
    <p><i> Three Green carnation pots for Oscar Wilde’s followers</i>, Stoneware clay, one glazed</p>
    </div>

    
      	<div class="span4">
      <img src="http://schools.dot-art.com/images/teachers-corner-20/curse-of-drinking-classes-v-heron.jpg">
     <p>.</p> 
    <p><i> Work is the Curse of the Drinking Classes. A pot for Actors who’ve played Oscar Wilde</i>, Porcelain Unfired</p>
    </div>
    
      <div class="row">
            
            <a href="https://www.artscouncil.org.uk/" target="_blank">
                <img src="/images/ACE-logo-black.jpg" class="span6" alt="Arts Council England" />
            </a>
             </div>
	
</div>
