<?
   $this->headTitle('Thank You');
?>

<div class="container lowered">

<div class="jumbotron who">
<h1 class="what">Thank You For Confirming</h1>
</div>

<p>Thank you for confirming your vote in the dot-art Schools competition 2014!</p>
<p>You are only allowed to vote once.  However, if you wish to change your mind, just vote again to
replace this one.</p>
<p>An exhibition will take place at the Walker Art Gallery in Liverpool from the 17th of May showcasing the winning
artwork from each school. Details will be published on this website when voting closes. For more information, visit
the <a href="/what">What?</a> page.</p>

<a href="/what" class="btn">Visit the What? page</a>

</div>
